### ISSUE TITLE
DEV_FHIR_API_ENDPOINT value post successful installation 

### ISSUE THREAD

**Issue by vagarwal77** [awslabs/fhir-works-on-aws-deployment#100]
As per console logs, seems like, Fhir deployment has been successful - 

Please suggest where and at which port FHIR server will be running? I need this info to test with Postman and also to test the APIs. 
Normally, every service prints the url in the last

  {
      "enabled": true,
      "key": "API_URL",
      "value": "<DEV_FHIR_API_ENDPOINT>",
      "type": "text"
    },
    {
      "enabled": true,
      "key": "API_KEY",
      "value": "<DEV_API_KEY>",
      "type": "text"
    },
    {
      "enabled": true,
      "key": "COGNITO_TOKEN",
      "value": "<COGNITO_AUTH_TOKEN>",
      "type": "text"
    }

#########
You can also set up the server to archive logs older than 7 days into S3 and delete those logs from Cloudwatch Logs.
You can also do this later manually, if you would prefer.

Would you like to set the server to archive logs older than 7 days? (yes/no): no

Would you like to set up daily DynamoDB Table backups?

Selecting 'yes' below will set up backups using the default setup from the cloudformation/backups.yaml file.
DynamoDB Table backups can also be set up later. See the README file for more information.

Note: This will deploy an additional stack, and can lead to increased costs to run this server.

Would you like to set up backups now? (yes/no): no

**Setup completed successfully.**
You can now access the FHIR APIs directly or through a service like POSTMAN.

For more information on setting up POSTMAN, please see the README file.
All user details were stored in 'Info_Output.yml'.

You can obtain new Cognito authorization tokens by using the init-auth.py script.

Syntax: 
python3 init-auth.py <USER_POOL_APP_CLIENT_ID> <REGION>

For the current User:
python3 init-auth.py  us-east-1

**Comment by rsmayda** [comment]
> Please suggest where and at which port FHIR server will be running?

The system is running off of API Gateway using default ports (80, 443) so no port is required to be specified. To get your system attributes please run: `serverless info --verbose --region <REGION> --stage <STAGE>`

More advice/instructions here: https://github.com/awslabs/fhir-works-on-aws-deployment#user-variables

**Comment by jcarta** [comment]
I am also have issues testing this out. 

When I run `serverless info --verbose --region <REGION>  --stage <STAGE>` I get a `developer-key-dev` and `ServiceEndpoint` key/value pair. Is this what's used for the `API_KEY` and `API_URL`  respectively in the curl command below? 

`curl -H "Accept: application/json" -H "Authorization:<COGNITO_AUTH_TOKEN>" -H "x-api-key:<API_KEY>" <API_URL>`

**Comment by vagarwal77** [comment]
2 observations - 
1. All over the place, hetting error "serverless: command not found". 

FHIR Works is deploying. A fresh install will take ~20 mins
./scripts/install.sh: line 313: serverless: command not found
Deployed Successfully.
[xx@ip-1xxxx fhir-works-on-aws-deployment]$ serverless info --verbose --region us-east-1 --stage dev
-bash: serverless: command not found

2. I don't see any new API Gateway APIs got created. Do we have a list of AWS assets which will get created as part of Fhir deployment? 

Just feeling lost with this service :(

Thanks
-Vivek

**Comment by vagarwal77** [comment]
Also, Info_Output.yml of size 0. 

-rw-r-----. 1 root                       root                                0 Sep 11 17:06 Info_Output.yml

**Comment by jcarta** [comment]
> Also, Info_Output.yml of size 0.
> 
> -rw-r-----. 1 root root 0 Sep 11 17:06 Info_Output.yml

Sounds the package didn't install correctly on your machine. Check to see if your scripts/install.sh script returned any errors.

I got it to work using a t2.medium EC2 instance running the Amazon Linux 2 OS

**Comment by rsmayda** [comment]
> I am also have issues testing this out.
> 
> When I run `serverless info --verbose --region <REGION> --stage <STAGE>` I get a `developer-key-dev` and `ServiceEndpoint` key/value pair. Is this what's used for the `API_KEY` and `API_URL` respectively in the curl command below?
> 
> `curl -H "Accept: application/json" -H "Authorization:<COGNITO_AUTH_TOKEN>" -H "x-api-key:<API_KEY>" <API_URL>`

@jcarta -- Yep those are the right values, though we recommend you to use postman to interact with the API (it is 1000x easier)

https://github.com/awslabs/fhir-works-on-aws-deployment#using-postman-to-make-api-requests

**Comment by rsmayda** [comment]
@vagarwal77 I think jcarta is right it sounds like the installation is not successful.

Could you provide this information so we can help debug?

- What is the operating system you are using for the installation?
- What is the command you are running to start your install?

**Comment by jcarta** [comment]
> > I am also have issues testing this out.
> > When I run `serverless info --verbose --region <REGION> --stage <STAGE>` I get a `developer-key-dev` and `ServiceEndpoint` key/value pair. Is this what's used for the `API_KEY` and `API_URL` respectively in the curl command below?
> > `curl -H "Accept: application/json" -H "Authorization:<COGNITO_AUTH_TOKEN>" -H "x-api-key:<API_KEY>" <API_URL>`
> 
> @jcarta -- Yep those are the right values, though we recommend you to use postman to interact with the API (it is 1000x easier)
> 
> https://github.com/awslabs/fhir-works-on-aws-deployment#using-postman-to-make-api-requests

Thanks. I did get it to work with Postman. I added the token and API key to the headers and posted `{"resourceType": "Binary", "contentType": "image/jpeg"}` to `{{API_URL}}/Binary` and got a pre-signed PUT URL back.

I would like to experiment with other requests but I don't have an intuition for how to structure the body of the message. Are there examples for making requests to `{{API_URL}}/Patient`?

**Comment by vagarwal77** [comment]
Retried and same error - 
Full terminal output below - 

```
[xxx@xxx@ip-i-i-1-i fhir-works-on-aws-deployment]$ sudo "PATH=$PATH" -E ./scripts/install.sh --region us-east-1 --stage dev
[sudo] password for dfdf@dfdfdfdfd: 


Found AWS credentials for the following User/Role:

{
    "UserId": "cvcvc",
    "Account": "cvcvc",
    "Arn": "arn:aws:sts::ghghghghghgh:assumed-role/c3-dev-linux-terminal1-Role/i-ghghghghgg"
}


Is this the correct User/Role for this deployment? (yes/no): yes
Setup will proceed with the following parameters: 

  Stage: dev
  Region: us-east-1

Are these settings correct? (yes/no): yes

In order to deploy the server, the following dependencies are required:
	- nodejs
	- npm
	- python3
	- yarn
	- serverless

These dependencies will be installed (if not already present).
Would you like to continue? (yes/no): yes

Installing dependencies...

...
Package 1:nodejs-6.17.1-1.el7.x86_64 already installed and latest version
Nothing to do
npm is /usr/local/bin/npm
npm is /usr/bin/npm
./scripts/install.sh: line 70: type: serverless: not found
npm WARN deprecated @types/chalk@2.2.0: This is a stub types definition for chalk (https://github.com/chalk/chalk). chalk provides its own type definitions, so you don't need @types/chalk installed!
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/bin/sls -> /usr/lib/node_modules/serverless/bin/serverless.js
/usr/bin/serverless -> /usr/lib/node_modules/serverless/bin/serverless.js

> protobufjs@6.10.1 postinstall /usr/lib/node_modules/serverless/node_modules/protobufjs
> node scripts/postinstall


> serverless@2.0.0 postinstall /usr/lib/node_modules/serverless
> node ./scripts/postinstall.js

/usr/lib/node_modules/serverless/node_modules/boxen/index.js:26
			...detail
			^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/serverless/scripts/postinstall.js:3:15)
/usr/lib
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/serverless/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ws@7.3.1 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@7.3.1 requires a peer of utf-8-validate@^5.0.2 but none was installed.
npm ERR! Linux 4.14.186-146.268.amzn2.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "-g" "serverless"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! serverless@2.0.0 postinstall: `node ./scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serverless@2.0.0 postinstall script 'node ./scripts/postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serverless package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serverless
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serverless
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/dfdf@dfdfdfdfd/fhir-works-on-aws-deployment/scripts/npm-debug.log
npm ERR! code 1
python3 is /usr/bin/python3
pip3 is /usr/local/bin/pip3
pip3 is /usr/bin/pip3
Traceback (most recent call last):
  File "/bin/pip3", line 7, in <module>
    from pip import main
ImportError: cannot import name 'main' from 'pip' (/usr/local/lib/python3.7/site-packages/pip/__init__.py)
./scripts/install.sh: line 76: type: yarn: not found
[yarn]
name=Yarn Repository
baseurl=https://dl.yarnpkg.com/rpm/
enabled=1
gpgcheck=1
gpgkey=https://dl.yarnpkg.com/rpm/pubkey.gpg
Loaded plugins: extras_suggestions, langpacks, update-motd
yarn                                                                                                                                                                                                                                 | 2.9 kB  00:00:00     
No packages marked for update
Loaded plugins: extras_suggestions, langpacks, update-motd
Resolving Dependencies
--> Running transaction check
---> Package yarn.noarch 0:1.22.5-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

============================================================================================================================================================================================================================================================
 Package                                                    Arch                                                         Version                                                           Repository                                                  Size
============================================================================================================================================================================================================================================================
Installing:
 yarn                                                       noarch                                                       1.22.5-1                                                          yarn                                                       1.2 M

Transaction Summary
============================================================================================================================================================================================================================================================
Install  1 Package

Total download size: 1.2 M
Installed size: 5.1 M
Downloading packages:
warning: /var/cache/yum/x86_64/2/yarn/packages/yarn-1.22.5-1.noarch.rpm: Header V4 RSA/SHA512 Signature, key ID 6963f07f: NOKEY
Public key for yarn-1.22.5-1.noarch.rpm is not installed
yarn-1.22.5-1.noarch.rpm                                                                                                                                                                                                             | 1.2 MB  00:00:00     
Retrieving key from https://dl.yarnpkg.com/rpm/pubkey.gpg
Importing GPG key 0x6963F07F:
 Userid     : "Yarn RPM Packaging <yarn@dan.cx>"
 Fingerprint: 9a6f 73f3 4beb 7473 4d8c 6914 9cbb b558 6963 f07f
 From       : https://dl.yarnpkg.com/rpm/pubkey.gpg
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : yarn-1.22.5-1.noarch                                                                                                                                                                                                                     1/1 
  Verifying  : yarn-1.22.5-1.noarch                                                                                                                                                                                                                     1/1 

Installed:
  yarn.noarch 0:1.22.5-1                                                                                                                                                                                                                                    

Complete!
Loaded plugins: extras_suggestions, langpacks, update-motd
No packages marked for update

node is /usr/local/bin/node
node is /usr/bin/node
npm is /usr/local/bin/npm
npm is /usr/bin/npm
python3 is /usr/bin/python3
pip3 is /usr/local/bin/pip3
pip3 is /usr/bin/pip3
yarn is /usr/bin/yarn
./scripts/install.sh: line 113: type: serverless: not found
ERROR: package 'serverless' failed to install.
Done!
Node version 0.8.10 is not supported, please use Node.js 4.0 or higher.
Node version 0.8.10 is not supported, please use Node.js 4.0 or higher.


FHIR Works is deploying. A fresh install will take ~20 mins


./scripts/install.sh: line 313: serverless: command not found
Deployed Successfully.

./scripts/install.sh: line 318: serverless: command not found
Setting up AWS Cognito with default user credentials to support authentication in the future...
This will output a token that you can use to access the FHIR API.
(You can generate a new token at any time after setup using the included init-auth.py script)

ACCESS TOKEN:

***

Warning: Cognito has already been initialized.
If you need to generate a new token, please use the init-auth.py script.
Continuing...

***


In order to be able to access the Kibana server for your ElasticSearch Service Instance, you need create a cognito user.
You can set up a cognito user automatically through this install script, 
or you can do it manually via the Cognito console.

Do you want to set up a cognito user now? (yes/no): yes

Okay, we'll need to create a cognito user using an email address and password.

Enter your email address (<youremail@address.com>): vagarwal@concertohealthai.com


Is vagarwal@concertohealthai.com your correct email? (yes/no): yes


Please create a temporary password. Passwords must satisfy the following requirements: 
  * 8-20 characters long
  * at least 1 lowercase character
  * at least 1 uppercase character
  * at least 1 special character (Any of the following: '!@#$%^\&*()[]_+-")
  * at least 1 number character

Enter password: 
Please confirm your password: 

Parameter validation failed:
Invalid length for parameter ClientId, value: 0, valid range: 1-inf


Audit Logs are placed into CloudWatch Logs at <CLOUDWATCH_EXECUTION_LOG_GROUP>. The Audit Logs includes information about request/responses coming to/from your API Gateway. It also includes the Cognito user that made the request.

You can also set up the server to archive logs older than 7 days into S3 and delete those logs from Cloudwatch Logs.
You can also do this later manually, if you would prefer.

Would you like to set the server to archive logs older than 7 days? (yes/no): no


Would you like to set up daily DynamoDB Table backups?

Selecting 'yes' below will set up backups using the default setup from the cloudformation/backups.yaml file.
DynamoDB Table backups can also be set up later. See the README file for more information.

Note: This will deploy an additional stack, and can lead to increased costs to run this server.

Would you like to set up backups now? (yes/no): no


Setup completed successfully.
You can now access the FHIR APIs directly or through a service like POSTMAN.


For more information on setting up POSTMAN, please see the README file.
All user details were stored in 'Info_Output.yml'.

You can obtain new Cognito authorization tokens by using the init-auth.py script.

Syntax: 
python3 init-auth.py <USER_POOL_APP_CLIENT_ID> <REGION>



For the current User:
python3 init-auth.py  us-east-1


[xxx@xxx@ip-i-i-1-i fhir-works-on-aws-deployment]$ serverless info --verbose --region us-east-1 --stage dev
-bash: serverless: command not found
[xxx@xxx@ip-i-i-1-i fhir-works-on-aws-deployment]$ ls -l
total 1436
drwxr-x---. 2 dfdf@dfdfdfdfd domain users@dfdfdfdfd   4096 Sep 11 02:39 auditLogMover
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd    155 Sep 11 02:39 CHANGELOG.md
drwxr-x---. 2 dfdf@dfdfdfdfd domain users@dfdfdfdfd   4096 Sep 11 02:39 cloudformation
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd    309 Sep 11 02:39 CODE_OF_CONDUCT.md
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd   4875 Sep 11 02:39 CONTRIBUTING.md
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd   4215 Sep 11 02:39 CUSTOMIZE.md
drwxr-x---. 2 dfdf@dfdfdfdfd domain users@dfdfdfdfd   4096 Sep 11 02:39 ddbToEsLambda
drwxr-x---. 2 dfdf@dfdfdfdfd domain users@dfdfdfdfd   4096 Sep 11 02:39 docker
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd      0 Sep 11 02:55 Finished
-rw-r-----. 1 root                       root                                0 Sep 11 20:05 Info_Output.yml
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd  19808 Sep 11 02:39 INSTALL.md
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd  10142 Sep 11 02:39 LICENSE
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd     81 Sep 11 02:39 NOTICE
-rw-r-----. 1 root                       root                           724116 Sep 11 16:59 npm-debug.log
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd      0 Sep 11 02:55 Package
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd   3158 Sep 11 02:39 package.json
drwxr-x---. 2 dfdf@dfdfdfdfd domain users@dfdfdfdfd   4096 Sep 11 02:39 postman
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd  12049 Sep 11 02:39 README.md
drwxr-x---. 2 dfdf@dfdfdfdfd domain users@dfdfdfdfd   4096 Sep 11 02:39 resources
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd      0 Sep 11 02:55 Running
drwxr-x---. 2 dfdf@dfdfdfdfd domain users@dfdfdfdfd   4096 Sep 11 20:04 scripts
-rw-r-----. 1 root                       root                              119 Sep 11 20:05 serverless_config.json
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd     41 Sep 11 02:39 serverless_config.template.json
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd  11714 Sep 11 02:39 serverless.yaml
drwxr-x---. 2 dfdf@dfdfdfdfd domain users@dfdfdfdfd   4096 Sep 11 02:39 src
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd 218336 Sep 11 02:39 THIRD-PARTY
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd    901 Sep 11 02:39 tsconfig.json
-rw-r-----. 1 dfdf@dfdfdfdfd domain users@dfdfdfdfd 387747 Sep 11 02:39 yarn.lock
[xxx@xxx@ip-i-i-1-i fhir-works-on-aws-deployment]$ 
```

**Comment by vagarwal77** [comment]
> @vagarwal77 I think jcarta is right it sounds like the installation is not successful.
> 
> Could you provide this information so we can help debug?
> Amazon Linux
> * What is the operating system you are using for the installation?
sudo "PATH=$PATH" -E ./scripts/install.sh --region us-east-1 --stage dev

> * What is the command you are running to start your install?

**Comment by rsmayda** [comment]
> Thanks. I did get it to work with Postman. I added the token and API key to the headers and posted `{"resourceType": "Binary", "contentType": "image/jpeg"}` to `{{API_URL}}/Binary` and got a pre-signed PUT URL back.
> 
> I would like to experiment with other requests but I don't have an intuition for how to structure the body of the message. Are there examples for making requests to `{{API_URL}}/Patient`?

@jcarta - information on Binary resources (they are handled in a special way) https://github.com/awslabs/fhir-works-on-aws-deployment#accessing-binary-resources

As for resource examples: in postman you go to 'POST Patient' then click on the 'Body' tab you should see an example body of what a Patient request would look like. If you want other examples the FHIR site gives at least 1 example per base resource. ie: https://www.hl7.org/fhir/patient-examples.html

![Patient_img](https://user-images.githubusercontent.com/5750407/92973370-0ebd3d00-f452-11ea-8b7d-270b043b9857.PNG)

**Comment by rsmayda** [comment]
> ```
> serverless@2.0.0 postinstall /usr/lib/node_modules/serverless
> node ./scripts/postinstall.js
> 
> /usr/lib/node_modules/serverless/node_modules/boxen/index.js:26
> 			...detail
> ```

@vagarwal77  Interesting the version of serverless that is being installed looks to be broken see the existing unit test from serverless team: https://github.com/serverless/serverless/runs/1096482528

For the time being you can try to install serverless manually by specifying a working version, by using these commands:
```bash
npm install -g serverless@~1.62.0
sudo npm install -g serverless@~1.62.0
```

Then you can try the install.sh script

We will look more into this issue next week! Thanks for bringing this to our attention

**Comment by rsmayda** [comment]
TODO: 
- Update script to stop if serverless fails to install
- Update script to install a specific version of serverless

**Comment by vagarwal77** [comment]
Seems like, serverless is broken badly :- 

[vagarwal@ConcertoHealth.AI@ip-10-164-1-105 fhir-works-on-aws-deployment]$ sudo npm install -g serverless@~1.62.0
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
/usr/bin/serverless -> /usr/lib/node_modules/serverless/bin/serverless.js
/usr/bin/slss -> /usr/lib/node_modules/serverless/bin/serverless.js
/usr/bin/sls -> /usr/lib/node_modules/serverless/bin/serverless.js

> serverless@1.62.0 postinstall /usr/lib/node_modules/serverless
> node ./scripts/postinstall.js

module.js:478
    throw err;
    ^

Error: Cannot find module 'boxen'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/serverless/scripts/postinstall.js:3:15)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
/usr/lib
└── (empty)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/serverless/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ws@7.3.1 requires a peer of bufferutil@^4.0.1 but none was installed.
npm WARN ws@7.3.1 requires a peer of utf-8-validate@^5.0.2 but none was installed.
npm ERR! Linux 4.14.186-146.268.amzn2.x86_64
npm ERR! argv "/usr/bin/node" "/bin/npm" "install" "-g" "serverless@~1.62.0"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! serverless@1.62.0 postinstall: `node ./scripts/postinstall.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serverless@1.62.0 postinstall script 'node ./scripts/postinstall.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the serverless package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./scripts/postinstall.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs serverless
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls serverless
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/vagarwal@ConcertoHealth.AI/fhir-works-on-aws-deployment/npm-debug.log
npm ERR! code 1

**Comment by rsmayda** [comment]
Hey @vagarwal77! 

I believe we are helping you offline. Is there anything else we can help you with?
