### ISSUE TITLE
Adding other FHIR Resources and DSTU2

### ISSUE THREAD

**Issue by jcarta** [awslabs/fhir-works-on-aws-deployment#103]
The tutorial implemented the Patient and Binary resources. How would we go about adding the remaining resources? How would we go about adding the DSTU2 capability?

**Comment by SanketD92** [comment]
Hello @jcarta, thanks for the question. For other observations you could navigate to fhir.com/Observation. 

For the DSTU2 capability, could you elaborate as to why that suits your use-case better than R4?

**Comment by jcarta** [comment]
> fhir.com/Observation

I was looking at the EPIC sandbox, https://fhir.epic.com, and some resources such as FamilyMemberHistory only support DSTU2.
