### ISSUE TITLE
'ResourceNotFoundError' when updating a Resource

### ISSUE THREAD

**Issue by steve1973** [awslabs/fhir-works-on-aws-deployment#108]
Good afternoon

We noticed that when updating a resource with a document status of 'AVAILABLE' and vid of 10 we were receiving a 'ResourceNotFoundError' error. The latest 2 versions of the resource should be returned from the 'getMostRecentValidResource' query, but we were actually getting versions 8 & 9 back, which were both set to 'DELETED'. The problem appears to be related to the vid, which is defined as a string in ddb and therefore affects the sort order, as a string of '10' is less than '8' & '9'. I did think about updating the vid to be a number in ddb, but the vid is passed in as a string parameter.

I just wanted to check if this was a real issue or if I was doing something wrong?

Kind regards

Steve

**Comment by rsmayda** [comment]
@steve1973 Good callout here -- We will take a moment to confirm and get back to you by EOD

**Comment by steve1973** [comment]
Thanks Robert.

**Comment by rsmayda** [comment]
Confirmed - will prioritize ASAP

**Comment by rsmayda** [comment]
We are looking to have this in by end of week -- will update when pushed

**Comment by steve1973** [comment]
I presume the AttributeType for vid in serverless.yaml will be updated to 'N'?

**Comment by rsmayda** [comment]
Both PRs have been merged! As mentioned in our [change log](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/CHANGELOG.md#added) if you want to keep your data you must run the [migration script](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/scripts/sort-key-migration.js)

Thanks for bringing this to our attention! Have a great weekend
