### ISSUE TITLE
Fhir support for RedShift 

### ISSUE THREAD

**Issue by vagarwal77** [awslabs/fhir-works-on-aws-deployment#109]
We use AWS RedShift as data warehouse and would like to use current infrastructure behind fhir lambda..

Please suggest if any RedShift connector or blueprints for fhir exist?

**Comment by Bingjiling** [comment]
Hi @vagarwal77, thanks for reaching out! I'll check with the team tomorrow and get back to you.

**Comment by Bingjiling** [comment]
Hi @vagarwal77 , FHIR Works on AWS (FWoA) doesn't have any RedShift connector or blueprints. FWoA was designed in a way where all components can be easily swapped except for the deployment and interface components. The idea here is if customers using FWoA like to use other technology or database for a certain component, they can build it out and plug it into FWoA while keeping all the other components the same. So if you are interested in building a RedShift persistence layer, you can follow the example of the existing [DDB implementation](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb) and the [persistence interface](https://github.com/awslabs/fhir-works-on-aws-interface/blob/mainline/src/persistence.ts). Hope this helps :)
