### ISSUE TITLE
OMOP CDM data model support through fhir

### ISSUE THREAD

**Issue by vagarwal77** [awslabs/fhir-works-on-aws-deployment#110]
Please suggest if fhir can support OMOP CDM data models or having it on its roadmap for near time support?

**Comment by Bingjiling** [comment]
Hi @vagarwal77, thanks for reaching out! I'll check with the team tomorrow and get back to you.

**Comment by jn1119** [comment]
Hi  @vagarwal77 We are currently not planning to store data natively in analytical data formats any time soon. It is possible though for you to build your own storage abstraction layer that will allow for this. Let me know if you have any follow up questions.

**Comment by joekendal** [comment]
@Bingjiling have you developed your own Glue job for this transformation? We are looking to run an ETL on the DynamoDB FHIR to store it in S3 OMOP and are looking for an open-source implementation. Or we will just share ours in the end if not.
