### ISSUE TITLE
list of supported resources

### ISSUE THREAD

**Issue by vagarwal77** [awslabs/fhir-works-on-aws-deployment#117]
I can see the working example of Patient resources.
Where i can see the list of supported resourceType like Encounter, Observation etc? 

Please suggests if these are the supported resourceType?

**Comment by carvantes** [comment]
The default installation supports the FHIR 4.0.1 resource types. The complete list of supported resource types can be found here:

https://github.com/awslabs/fhir-works-on-aws-deployment/blob/b68d6387b2c748194cd13cb598754c9afb395809/src/constants.ts#L8-L14

**Comment by carvantes** [comment]
Both Encounter and Observation are supported.

I'm closing this issue, but feel free to reopen if you have further questions
