### ISSUE TITLE
Search based on dates not working

### ISSUE THREAD

**Issue by PrimKruskal** [awslabs/fhir-works-on-aws-deployment#129]
Search based on birthDate on patient api is not working and it is returning  zero results even though date are available. 

 {{API_URL}}/Patient?birthdate=1987-02-20 or {{API_URL}}/Patient?birthDate=1987-02-20 

![image](https://user-images.githubusercontent.com/72479878/97390413-d27f5800-18aa-11eb-92bb-ee73dd4ae935.png)

**Comment by rsmayda** [comment]
Confirmed 

Reproducible:
1. post this Patient: https://www.hl7.org/fhir/patient-example.json
1. search {{API_URL}}/Patient?birthDate=1974-12-25

Some ideas: 
- Perhaps elastic search requires some sort of format for searching on a `date` type

Next steps:
- see how to search on it via Kibana


![image](https://user-images.githubusercontent.com/5750407/97438010-9ecc1e80-18fa-11eb-814e-319e108a5297.png)

**Comment by SanketD92** [comment]
@PrimKruskal Thanks for bringing up this issue, and @rsmayda for the prompt confirmation. 

We're creating a backlog task for this to be prioritized into one of our upcoming sprints.

**Comment by lwarren01** [comment]
Any status update you might be able to provide here? We were also able to reproduce the issue. We were wondering if it has to do with the name of the field. The search parameter and the field name stored in ES don't match, "birthdate"  vs. "birthDate". Looking at the ES query, we can see that it is providing the name of the search parameter:


`
GET patient/_search
{
    "query": {
        "bool": {
            "must": [
                {
                    "query_string": {
                        "query": "1985-08-23",
                        "fields": [
                            "birthdate.*^1.0"
                        ],
                        "type": "best_fields",
                        "default_operator": "and",
                        "max_determinized_states": 10000,
                        "enable_position_increments": true,
                        "fuzziness": "AUTO",
                        "fuzzy_prefix_length": 0,
                        "fuzzy_max_expansions": 50,
                        "phrase_slop": 0,
                        "lenient": true,
                        "escape": false,
                        "auto_generate_synonyms_phrase_query": true,
                        "fuzzy_transpositions": true,
                        "boost": 1
                    }
                }
            ],
            "filter": [
                {
                    "match": {
                        "documentStatus": {
                            "query": "AVAILABLE",
                            "operator": "OR",
                            "prefix_length": 0,
                            "max_expansions": 50,
                            "fuzzy_transpositions": true,
                            "lenient": false,
                            "zero_terms_query": "NONE",
                            "auto_generate_synonyms_phrase_query": true,
                            "boost": 1
                        }
                    }
                }
            ],
            "adjust_pure_negative": true,
            "boost": 1
        }
    }
}
`

**Comment by rsmayda** [comment]
In our most recent release we fixed a lot of date related search issues: https://github.com/awslabs/fhir-works-on-aws-deployment/tree/v2.6.0

Could you ensure you are using the latest versions? If issues persist please reopen this issue 😄
