### ISSUE TITLE
Working Bundle Example?

### ISSUE THREAD

**Issue by matthewjcable** [awslabs/fhir-works-on-aws-deployment#136]
I am having problems getting a Bundle Transaction to work.    Is there a good working example, from the API interface somewhere?  I desperately need to get some data loaded.  Some observations:

- It would be incredibly nice to have a working **Bundle example added to the  Fhir.postman_collection.json** in the Deployment project.  Especially one that creates a new resource WITH a supplied ID for the resource.  Especially, if I cannot do it any other way at the moment (It sounds like individual creates with an ID are in the backlog yet).
- The **openapi.yaml** file in the Interface project documents a supposed "_bundle\transaction_" route:
  - This only returns a "Forbidden" error for me.  Which can take you down a rabbit hole wondering why it was forbidden.  It seems that the proper route is actually "**Bundle\transaction" with an upper case "B"** on "Bundle".
  - It reportedly accepts a request body type of "**TransactionRequest**".  The schema definition for "TransactionRequest" embedded within the yaml does not seem to align with the class definitions found in the project.
  -  The route is listed as only supporting a POST method.  POST does align with FHIR 4.0.1 specs.  So far, no matter what I do with a payload, I am only getting to tell me that it "**Cannot POST /Bundle/transaction**".  Should I be able to POST to this route?
- NOTE: I attempted a PUT, which I do not think I want, and I get a "Can not update resource with ID[transaction], while the given request payload has an ID[undefined]"

**Comment by Bingjiling** [comment]
Hi Matthew, thanks for reaching out to us! I'll check with my team on bundle examples and get back to you today.

**Comment by Bingjiling** [comment]
Hi Matthew, we do not have an example of a bundle request in the repo for now. I'll create a ticket for us to add it in the near future. In the mean time, please feel free to take a stab at it if you would be so kind to help out. 

Here's an example of a bundle request body: 

```
{
  "resourceType": "Bundle",
  "type": "transaction",
  "entry": [
    {
      "resource": {
        "resourceType": "Patient",
        "name": [
          {
            "family": "Smith",
            "given": [
              "John"
            ]
          }
        ],
        "gender": "male"
      },
      "request": {
        "method": "POST",
        "url": "Patient"
      }
    }
  ]
}
``` 
![Screen Shot 2020-11-03 at 10 39 57 AM](https://user-images.githubusercontent.com/14276357/98007633-a2134e80-1dc1-11eb-8afa-16e9f7617160.png)

Another thing to note here is **openapi.yaml** defines the API between FWoA packages, not the api to the FHIR server itself. To make a bundle request, the request need to be sent to the root URL, and you can check this [link](https://www.hl7.org/fhir/http.html#transaction) for more information on this.

**Comment by matthewjcable** [comment]
Thank you for the clarification.   I am able to get Bundles to go in now using that root route.

Unfortunately it looks like my desire to create (or update as new) with a specified ID, is not yet possible.  It seems to be constrained by the same "updateCreate" bug [#17](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/issues/17) also discussed in the Persistence library.

**Comment by nguyen102** [comment]
We now include Bundle examples in our POSTMAN collection. The commit where we added these changes is here.
https://github.com/awslabs/fhir-works-on-aws-deployment/commit/42966b5e3c4e51c09314b7107ca0a8ba2130b37a

Please use the new POSTMAN files here.
https://github.com/awslabs/fhir-works-on-aws-deployment/tree/mainline/postman
