### ISSUE TITLE
How to use an AWS named profile ?

### ISSUE THREAD

**Issue by Nabellaleen** [awslabs/fhir-works-on-aws-deployment#159]
I use AWS named profiles to handle my various AWS accounts, and I wonder how I should use the install.sh script with a named profile ?

I've tried something like `AWS_PROFILE=myprofile && sudo "PATH=$PATH" -E ./scripts/install.sh -r eu-west-3 -s dev` but I still have the following error message :
```
Could not find any valid AWS credentials. You can configure credentials by running 'aws configure'. If running this script with sudo you must configure your awscli with 'sudo aws configure'
For more information about configuring the AWS CLI see: https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html
```

**Comment by carvantes** [comment]
Hi, 

I don't see anything wrong with your command. That exact command works for me(I'm testing on macOS) 

The `install.sh` script does not have code specific for aws profiles. If the `AWS_PROFILE` env variable is set correctly things should work. 

Could you double check that the profile you are using is valid by running:
```bash
AWS_PROFILE=myprofile && sudo -E aws sts get-caller-identity
```

**Comment by Nabellaleen** [comment]
The profile is not found by the command while using sudo

I think the problem is that the profile has to exists in the `~/.aws/*` files and, while using the previous command, it looking for root home directory and not original user home :/

```
$ aws configure list-profiles
myprofile
$ sudo aws configure list-profiles
# nothing
```

Any tips to handle that ? (I'm on Fedora, an UNIX system ; maybe MacOS has some hackish behaviours)

**Comment by Nabellaleen** [comment]
It worked by doing :
```
export AWS_PROFILE=myprofile
export AWS_CONFIG_FILE=~/.aws/config
export AWS_SHARED_CREDENTIALS_FILE=~/.aws/credentials
sudo -E aws sts get-caller-identity
```

Without these 2 variables defined, sudo aws cli is not able to find the configuration files, with or without the `-E`

**Comment by carvantes** [comment]
You are right. This issue explains the aws cli sudo behavior quite nicely: https://github.com/aws/aws-cli/issues/3121

Our initial recommendation is to run `sudo aws configure`. But in order to use the existing credentials file then setting the additional env variables you propose is correct.

**Comment by carvantes** [comment]
I just merged your PR with the troubleshooting notes.

Thanks again for your contribution!
