### ISSUE TITLE
Info_Output.yml is empty

### ISSUE THREAD

**Issue by Nabellaleen** [awslabs/fhir-works-on-aws-deployment#161]
Hi,

I'm on Linux Fedora 32.

I've launched the `./scripts/install.sh`, let it install the dependencies.
No ACCESS TOKEN was output, because Cognito wal already initialized. (which seems not true : there is nothing setup in Cognito while looking via the console)

I've let the CLI create a Cognito user, and the tool said :
```
Parameter validation failed:
Invalid length for parameter ClientId, value: 0, valid range: 1-inf
```

Then I've answered `no` to the question about logs and backup.

And at the end, the `Info_Output.yml` file is empty, so I don't have any information about the running instance.

Note : at the end of the logs, the command lien says :
```
Syntax: 
python3 scripts/init-auth.py <USER_POOL_APP_CLIENT_ID> <REGION>

For the current User:
python3 scripts/init-auth.py  eu-west-3
```
So it seems there is no `USER_POOL_APP_CLIENT_ID` configured

**Comment by Nabellaleen** [comment]
I have the same issue by using the docker installation

**Comment by nguyen102** [comment]
Hi,

Thanks for your feedback. You can check the CloudFormation Stack in `eu-west-3` to see what the error was and where the installation failed. The CloudFormation stack should be named `fhir-service-<stage>`, by default it would be `fhir-service-dev`. 

Can you check the CloudFormation stack and see what the status is?

Also can you please c/p the full console output from your terminal into this ticket?

Thanks,
Tim

**Comment by Nabellaleen** [comment]
There is absolutely nothing :
![image](https://user-images.githubusercontent.com/3717607/100126575-66c6e580-2e7e-11eb-8afc-93098b249a6d.png)

**Comment by nguyen102** [comment]
It looks like the UI is currently set to filter for "Active" stacks. Can you check the other filters to see if there are any other stacks? For example, the "Failed", "Deleted", and "In Progress" filters. Also can you confirm that the you're trying to deploy to `eu-west-3` and that the screenshot above is displaying CloudFormation stack from `eu-west-3`?

Can you also copy and paste all the commands and output on your terminal when running `install.sh`?

**Comment by nguyen102** [comment]
Another option is to try deploying the stack in another region in which you don't have any resources yet. For example, to deploy in London (eu-west-2)
`sudo ./install.sh --region eu-west-3`

**Comment by Nabellaleen** [comment]
> It looks like the UI is currently set to filter for "Active" stacks. Can you check the other filters to see if there are any other stacks? For example, the "Failed", "Deleted", and "In Progress" filters.

Yes, nothing in the other filters

> Also can you confirm that the you're trying to deploy to `eu-west-3` and that the screenshot above is displaying CloudFormation stack from `eu-west-3`?

Yes, I am

**Comment by Nabellaleen** [comment]
Note : have to launch the installation script with sudo seems a very strong security risk, in particular as you are running a `yarn install` with these granted rights, and as yarn can run post install system scripts and that history have shown that with the atomicity of NPM packages, it's "easy" to have hands on a little very used package ...

Just provide the dependencies should be sufficient :)

**Comment by Nabellaleen** [comment]
I'm sorry, I can't spend more time with FHIR Works :/

**Comment by nguyen102** [comment]
We're sorry we were unable to get FHIR Works working on your system. If you ever decide to come back to FHIR Works, please let us know.

That's a good point about the `sudo` command. The `sudo` command for the installation script is there because the script installs any dependency on your system that is needed, but might not be there, for example `node`. 

An alternative way to install FHIR Works on the system is using the [Manual installation](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/INSTALL.md) steps. With these steps you won't need `sudo` when running yarn.
