### ISSUE TITLE
Docker installation is not working on Fedora 32

### ISSUE THREAD

**Issue by Nabellaleen** [awslabs/fhir-works-on-aws-deployment#162]
To make it work, I had to add `--network=host` to the build command. Without it, docker is not able to reach debian servers for the apt-get commands

```sh
docker build -t fhir-server-install --network=host -f docker/Dockerfile .
```

**Comment by Nabellaleen** [comment]
I also had to use `--network=host` with the `docker run` command

**Comment by nguyen102** [comment]
Thanks for your feedback. I'll look into including this in our documentation as a troubleshooting tip.

**Comment by nguyen102** [comment]
PR with this troubleshooting tip merged.
