### ISSUE TITLE
Support Multi-tenancy

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-deployment#165]
Add support for multi-tenancy for a more economic Saas offering without affecting the existing non-tenant based approach.

### Initial design proposal:
![](https://app.lucidchart.com/publicSegments/view/e1af0fb0-f821-40ff-a315-2ac19876ff86/image.png)

- API Gateway will be enhanced to pass tenant-id as part of URL - https://fhir.server.com/tenant/{tenant-id}/{resource}

- API Gateway - extract tenant-id and pass it as parameter

- Lambda write into tenant based table - resource-db-dev-1-tenant-id 

- DynamoDB - streaming pass this data to ElasticSearch

- Separate - index per tenant/resource OR - global resource index

- Meta-data/conformance page need to incorporate tenant-id based approach

- lack of a tenant id would use the existing non-tenant design

### Open design items:

- Tenant S3 bucket binary storage

- Finalize ES design decision

**Comment by Dunmail** [comment]
+1 We use FWoA as a facade on multiple systems. We would benefit from the `tenant-id` in the URL and as a parameter.

**Comment by rsmayda** [comment]
Thanks for opening this issue -- If folks from our community are interested in this please 'thumbs-up' up the issue.

We would love to get diverse use-cases to ensure FWoA is built to support flexibility

**Comment by asrour-vytalize** [comment]
Any updates on this?

**Comment by ghost** [comment]
> Any updates on this?

Thanks for the interest - our team is wrapping up work on this and hope to have a PR up in the near future

**Comment by asrour-vytalize** [comment]
Can you share the code/branch?
Because I am working on a solution for us.

**Comment by rashedoumar** [comment]
hey @medhost-bfindeisen   you are doing a great job here , what's the update on the Multi-tenancy  ?

**Comment by phackwer** [comment]
In FHIR, the Patient Resource has "Assigner".

https://www.hl7.org/fhir/datatypes.html#Identifier

Use this. Have fun

**Comment by phackwer** [comment]
> Can you share the code/branch?
> Because I am working on a solution for us.

https://www.hl7.org/fhir/datatypes.html#Identifier

You don't need "multi-tenancy". If this is really required you can have as many installs as required for each of your "tenants" to be isolated.

**Comment by ericfuxealth** [comment]
@@medhost-bfindeisen We are interested to contribute to the multi-tenant solution. Would love to connect.

**Comment by rsmayda** [comment]
We will be merging in this feature by end of this week!

**Comment by rsmayda** [comment]
Merged and released! https://github.com/awslabs/fhir-works-on-aws-deployment/releases/tag/v4.0.0
