### ISSUE TITLE
Project timeline

### ISSUE THREAD

**Issue by joekendal** [awslabs/fhir-works-on-aws-deployment#174]
Why do you keep releasing new versions of this repository / is there a checkbox of features you plan to add in future versions that we should know about? What is incomplete / what is missing?

**Comment by rsmayda** [comment]
New versions indicate that we have 'launched' something. So as we improve this package and subpackages we will create new versions. To see a list of what we have launched so far, check out our [CHANGELOG](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/CHANGELOG.md). To understand the version numbering please checkout [semantic versioning](https://semver.org/).

We have not published our roadmap, but we are currently working on support for SMART on FHIR and Implementation Guides.

As for missing or incomplete -- we try to track these things via GitHub issues, like: https://github.com/awslabs/fhir-works-on-aws-deployment/issues/87, https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/issues/6 or https://github.com/awslabs/fhir-works-on-aws-search-es/issues/8.

Hope this helps!
