### ISSUE TITLE
Deploy Local Packages to AWS -- missing node_modules dependencies.

### ISSUE THREAD

**Issue by medhost-jshaver** [awslabs/fhir-works-on-aws-deployment#182]
Following the instruction under [Deploy Local Packages to AWS](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/DEVELOPMENT.md#deploy-local-packages-to-aws) and I ran into an issue where the packaged fhir-service.zip is missing dependencies. 

cloudformation fails with the following error for the FhirServerProvConcLambdaAlias event

> Provisioned Concurrency configuration failed to be applied. Reason: FUNCTION_ERROR_INIT_FAILURE

Example of an error in cloudwatch
```
2021-01-11T17:45:17.249Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'qs'\nRequire stack:\n- /var/task/node_modules/express/lib/middleware/query.js\n- /var/task/node_modules/express/lib/application.js\n- /var/task/node_modules/express/lib/express.js\n- /var/task/node_modules/express/index.js\n- /var/task/node_modules/fhir-works-on-aws-routing/lib/app.js\n- /var/task/node_modules/fhir-works-on-aws-routing/lib/index.js\n- /var/task/src/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'qs'",
        "Require stack:",
        "- /var/task/node_modules/express/lib/middleware/query.js",
        "- /var/task/node_modules/express/lib/application.js",
        "- /var/task/node_modules/express/lib/express.js",
        "- /var/task/node_modules/express/index.js",
        "- /var/task/node_modules/fhir-works-on-aws-routing/lib/app.js",
        "- /var/task/node_modules/fhir-works-on-aws-routing/lib/index.js",
        "- /var/task/src/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:1015:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)",
        "    at Module.load (internal/modules/cjs/loader.js:879:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:724:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```
^ normally I see an error for the "methods" module missing. but I ran into this this error when trying to deploy with "methods" defined as a dependency in the fhir-works-on-aws-routing package.json. 

Steps to reproduce:
1. Clone the fhir-works projects into a directory
2. Copy/Paste these two scripts from fhir-works-on-aws-deployment into same folder as the cloned projects 
  fhir-works-deploy.sh
  fhir-works-deploy-one-time-setup.sh
3. Run fhir-works-deploy-one-time-setup.sh
4. Run fhir-works-deploy.sh
5. cd into fhir-works-on-aws-deployment 
6. run sudo -E serverless deploy --stage=\<stage\> --region=\<region\>

You can get away with running serverless package instead of deploy. Under the .serverless directory you can see the "methods" and "qs" modules are missing from fire-servize.zip node_modules. 

One interesting thing to mention is that simply cloning the fhir-works-on-aws-deployment, running yarn install, and then running serverless package/deploy appears to correctly package these dependencies. 

Node version: v12.20.1
yarn version: 1.22.10
yalc version: 1.0.0-pre.47

Update:
I tried running serverless package but added the value package.excludeDevDependencies = false within serverless.yaml. The dependencies did show up in the fhir-service package after this. So I assume these are being removed sometime in the exclude dev dependency step of serverless package/deploy. Granted the fhir-service.zip package is too large to deploy after doing this, but atleast this might be helpful information while troubleshooting.

**Comment by rsmayda** [comment]
Thanks for posting this -- I am looking at it now. In the meantime common trouble-shooting step to try is to re-run step 4 `Run fhir-works-deploy.sh`

**Comment by ghost** [comment]
@rsmayda Is there a work around that would get us past this that you have seen?

**Comment by rsmayda** [comment]
You still should be able to test locally via `sls offline`. I confirm I am seeing the problem on my end too

**Comment by rsmayda** [comment]
Another alternative to perhaps avoid some of these dependency issues is to limit the deployment to just the local packages you are working on. Say for example you are just updating the [persistence layer](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb) then you can modify the script to just look for those specific packages. You could find those lines [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/scripts/fhir-works-deploy-one-time-setup.sh#L11) or [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/scripts/fhir-works-deploy.sh#L10).

Also you could remove the interface steps, as most likely you are not changing the interface; remove [these lines](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/scripts/fhir-works-deploy.sh#L17-L35). I am still debugging a bit and know this is a pain-point

**Comment by ghost** [comment]
> You still should be able to test locally via `sls offline`. I confirm I am seeing the problem on my end too

@rsmayda Have you ever had an issue where when running offline some of the environment variables like process.env.RESOURCE_TABLE are not set? I am not sure if it is related to this issue or not. We are seeing  Value '[object Object]' at 'tableName'

**Comment by medhost-jshaver** [comment]
Looks like these packages are getting marked as extraneous by npm and this flag omits them from the output of the command "npm ls --prod=true --parseable=true". This npm ls --prod=true ... command is used by serverless to determine the packages to keep in the zip file for deployment.

I believe the issue stems from the git checkout [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/scripts/fhir-works-deploy.sh#L50). When these  package versions do not match the node_module versions it causes them to be flagged as extraneous. I have successfully packaged these dependencies by referencing the exact version + checksum that yarn put into the node_modules 

I will test this in a deployment in a moment to see if it completely resolved the issue.

I see this warning [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/scripts/fhir-works-deploy.sh#L3) and it makes me think that perhaps a command like "yarn check --integrity" could be used after the git checkout to warn the user of potential package.json & node_modules issues.

**Comment by rsmayda** [comment]
@medhost-gkersting I should have been more specific, the sls offline command is `AWS_ACCESS_KEY_ID=<Access-Key> AWS_SECRET_ACCESS_KEY=<Secret-Key> OFFLINE_BINARY_BUCKET=<FHIRBinaryBucket> OFFLINE_ELASTICSEARCH_DOMAIN_ENDPOINT=<ElasticSearchDomainEndpoint> serverless offline start`. Also found in the [DEVELOPMENT.md](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/DEVELOPMENT.md)

If you don't know the values above you can run `serverless info --verbose` to get them again or via AWS console

**Comment by rsmayda** [comment]
@medhost-jshaver 👏 👏 Excellent research -- I'd love to hear the results :)

**Comment by ghost** [comment]
> @medhost-gkersting I should have been more specific, the sls offline command is `AWS_ACCESS_KEY_ID=<Access-Key> AWS_SECRET_ACCESS_KEY=<Secret-Key> OFFLINE_BINARY_BUCKET=<FHIRBinaryBucket> OFFLINE_ELASTICSEARCH_DOMAIN_ENDPOINT=<ElasticSearchDomainEndpoint> serverless offline start`. Also found in the [DEVELOPMENT.md](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/DEVELOPMENT.md)
> 
> If you don't know the values above you can run `serverless info --verbose` to get them again or via AWS console

@rsmayda We are currently using that command. We found a way of getting past it by reverting a few of the changes in https://github.com/awslabs/fhir-works-on-aws-deployment/pull/170

    RESOURCE_TABLE: !Ref ResourceDynamoDBTableV2
    EXPORT_REQUEST_TABLE: !Ref ExportRequestDynamoDBTable
back to 
    RESOURCE_TABLE: '${self:custom.resourceTableName}'
    EXPORT_REQUEST_TABLE: '${self:custom.exportRequestTableName}'

I am still reviewing to see what might be causing our issue.

**Comment by medhost-jshaver** [comment]
It worked! Updating + committing the package.json dependencies in the deployment package before the scripts were ran was the fix. The node modules matched the package.json afterwards.

In case anyones runs into this:

so if yarn/yalc put these in the node_modules:

fhir-works-on-aws-authz-rbac@4.1.0+97caac97
fhir-works-on-aws-persistence-ddb@3.0.0+7f1d59ed
fhir-works-on-aws-routing@4.0.0+60259b47
fhir-works-on-aws-search-es@2.0.0+75ad6c2c
fhir-works-on-aws-interface@7.0.0+ceec8029

Then the package.json just needs to match versions with node modules so that serverless doesn't count them out of the production dependencies later on. Seems like it doesn't care about the checksum in that check so the below dependencies would work just fine fhir-works-on-aws-deployment package.json

```
  "dependencies": {
    "aws-sdk": "^2.785.0",
    "axios": "^0.21.1",
    "fhir-works-on-aws-authz-rbac": "4.1.0",
    "fhir-works-on-aws-interface": "7.0.0",
    "fhir-works-on-aws-persistence-ddb": "3.0.0",
    "fhir-works-on-aws-routing": "4.0.0",
    "fhir-works-on-aws-search-es": "2.0.0",
    "serverless-http": "^2.3.1"
  },
```

**Comment by Bingjiling** [comment]
[sls offline bugfix](https://github.com/awslabs/fhir-works-on-aws-deployment/commit/57fafb54e972f796a93a0c22aa72c3c8afae2847) and [trouble-shooing tips](https://github.com/awslabs/fhir-works-on-aws-deployment/pull/189) have been added. Thanks @medhost-jshaver and @medhost-gkersting for sharing all the details and tips!
