### ISSUE TITLE
Lambda too big; Initial deployment failing on UploadGlueScriptsLambdaFunction

### ISSUE THREAD

**Issue by joeportela** [awslabs/fhir-works-on-aws-deployment#184]
I'm trying to get an initial setup deployed in my account, but it keeps failing on this step. I'm deploying from the mainline branch with no edits.

Logical ID in the CloudFormation stack is UploadGlueScriptsLambdaFunction. 

The Status Reason is:
Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 5e143636-d418-4fc8-a031-3d3128a4f6c0; Proxy: null)

<img width="1162" alt="Screen Shot 2021-01-13 at 8 57 13 PM" src="https://user-images.githubusercontent.com/2459638/104534475-5dd2d480-55e2-11eb-85f8-be8a36d842cb.png">

Edit: To clarify, this was deploying via macOS with the `sudo ./scripts/install.sh` command. I was able to get it working using the docker install.

**Comment by rsmayda** [comment]
Thanks for alerting us! Could you share the sls version you are running? `sls --version`

**Comment by joeportela** [comment]
For sure, here's the output:
```
Serverless: Running "serverless" installed locally (in service node_modules)
Framework Core: 1.73.1
Plugin: 3.6.13
SDK: 2.3.1
Components: 2.31.2
```

Thanks for looking into this!

**Comment by Bingjiling** [comment]
Thanks for sharing the information! We had a similar issue before for [Lambda function is too big](https://github.com/awslabs/fhir-works-on-aws-deployment/issues/166), and it was resolved by cleaning up npm dependencies locally. Could you please try the commands mentioned in [this comment](https://github.com/awslabs/fhir-works-on-aws-deployment/issues/166#issuecomment-742025641) and see if it works? Meanwhile, I'll discuss with the team to add trouble shooting information in the documentation for this issue.

**Comment by silverslingshot1** [comment]
I've received exactly the same error and I have tried clearing the npm cache. It didn't make a difference. Any other suggestions?
I'm using Win 64.

Your Environment Information ---------------------------
     Node Version:              14.4.0
     Framework Version:         2.20.1 (standalone)
     Plugin Version:            4.4.2
     SDK Version:               2.3.2
     Components Version:        3.5.1

**Comment by rsmayda** [comment]
Hmm with multiple folks seeing this issue it will be worth-while to dig deeper here. @dilyes I would recommend seeing if these steps from our community will be helpful; for the time being: https://github.com/awslabs/fhir-works-on-aws-deployment/issues/166#issuecomment-742025641

**Comment by silverslingshot1** [comment]
@rsmayda thanks for looking into this.
I was able to deploy the stack using Docker so that is working fine.
