### ISSUE TITLE
Any support for Synthea?

### ISSUE THREAD

**Issue by jeffbonasso-ambifi** [awslabs/fhir-works-on-aws-deployment#187]
I am trying to populate some synthetic patients using Synthea (https://github.com/synthetichealth/synthea).

For records that have references getting an error like this...

`This entry's reference is not recognized. Entry's reference is: Practitioner?identifier=http://hl7.org/fhir/sid/us-npi|9999999459 . Valid format includes <url>/resourceType/id or <urn:uuid:|urn:oid:><id>`

Curious if this may be a bug with the validation in FWoA or potential issue with the ID's Synthea is generating?

**Comment by Bingjiling** [comment]
Hi @jeffbonasso-ambifi , thanks for reaching out! I'm wondering if you could provide an example of a record you tried to add?

**Comment by jeffbonasso-ambifi** [comment]
Sure, this is a patient generated with default options of Synthea. Basically follows them through their life as they interact with the healthcare system.

[Leonard963_Zboncak558_e54889d8-0779-6ac5-5688-7d1c87a7979a.json.zip](https://github.com/awslabs/fhir-works-on-aws-deployment/files/5849413/Leonard963_Zboncak558_e54889d8-0779-6ac5-5688-7d1c87a7979a.json.zip)

**Comment by Bingjiling** [comment]
Thanks for the example! Currently FWoA only support reference in format  `<url>/resourceType/id` or `<urn:uuid:|urn:oid:><id>`, search URL is not supported at the moment. We tried using FWoA with Synthea generated data, here's an example that works: 

[Horacio317_Dare640_cbe1ff84-8b75-73e5-bba4-5dca2a5bc62f.json.zip](https://github.com/awslabs/fhir-works-on-aws-deployment/files/5851160/Horacio317_Dare640_cbe1ff84-8b75-73e5-bba4-5dca2a5bc62f.json.zip)

Steps to create the above test data:

* Generate test data in Synthea with `run_synthea Alaska Juneau` 
* Truncate the data to 25 entries 

Hope this helps.

**Comment by joekendal** [comment]
We've had this working with Synthea just fine

**Comment by yonghaochen-nt** [comment]
> Thanks for the example! Currently FWoA only support reference in format `<url>/resourceType/id` or `<urn:uuid:|urn:oid:><id>`, search URL is not supported at the moment. We tried using FWoA with Synthea generated data, here's an example that works:
> 
> [Horacio317_Dare640_cbe1ff84-8b75-73e5-bba4-5dca2a5bc62f.json.zip](https://github.com/awslabs/fhir-works-on-aws-deployment/files/5851160/Horacio317_Dare640_cbe1ff84-8b75-73e5-bba4-5dca2a5bc62f.json.zip)
> 
> Steps to create the above test data:
> 
> * Generate test data in Synthea with `run_synthea Alaska Juneau`
> * Truncate the data to 25 entries
> 
> Hope this helps.

Could you please give more details how can we generate a sample data as the one you provided? What configurations did you set up?

**Comment by yonghaochen-nt** [comment]
I tried to use synthea version 2.6.1 https://github.com/synthetichealth/synthea/releases/tag/v2.6.1 to generate the data and got what I expected. Set use_us_core_ig=false, transaction_bundle = true, hospital.fhir.export = false and practitioner.fhir.export = false. Hope this helps.
