### ISSUE TITLE
Add support for visual studio code remote containers

### ISSUE THREAD

**Issue by chafey** [awslabs/fhir-works-on-aws-deployment#194]
For development I really like using visual studio code with the remote containers extension.  This gives you the same benefits of your docker installation path but cleanly integrates with visual studio code.  You can see an example of how I used this for another project here:

https://github.com/chafey/dumbo-drop

I would be happy to submit a PR if this is of interest - please let me know!

**Comment by rsmayda** [comment]
Feel free to open a PR if you think it’d benefit the community! I don’t have any experience using this tool
