### ISSUE TITLE
[Feature Request] Capabilities defined by the `persistence` package

### ISSUE THREAD

**Issue by AllanHodkinson** [awslabs/fhir-works-on-aws-deployment#200]
Hi AWS team,
Are you looking at the possibility of deriving the fields that go into the FHIRConfig router definition automatically from the server ".capabilities" method?
The FWoA router provides the "/metadata" route which builds a CapabilityStatement from the server config but there is scope for having a mismatch between what is set in the FHIRConfig and what the server describes in its ".capabilities" method response.

I see that there is some use of `resource.typeSearch.getCapabilities()` method so wondering if this is something you will take further?
Many thanks,
Allan

**Comment by carvantes** [comment]
Hi,

The goal is for the capability statement in the response from `/metadata` to truly describe the capabilities of a FWoA FHIR Server.

`FHIRConfig` is the source of truth for the capabilities of the server. The capability statement is derived from `FHIRConfig`

There were some inconsistencies among the 2 in the past. The biggest one being the search parameters which was addressed by implementing `resource.typeSearch.getCapabilities()` as you pointed out.

**Comment by carvantes** [comment]
It is true that some capabilities are hard-coded right now. i.e. `conditionalRead: 'not-supported',` at [cap.rest.resource.template.ts](https://github.com/awslabs/fhir-works-on-aws-routing/blob/mainline/src/router/metadata/cap.rest.resource.template.ts#L28)

That's good enough for customers using the default configuration, but it wouldn't be accurate if customers bring their own implementation of persistence that supports conditional reads. I think that it makes sense for Persistence to expose its capabilities in a method similar to `Search.getCapabilities()` and use it to build the cap statement.

We don't have an immediate plan for adding such method to the `Persistence` interface, but it sounds like a good idea to implement in the future

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
