### ISSUE TITLE
HTTP Delete request does not work

### ISSUE THREAD

**Issue by fatemeh91** [awslabs/fhir-works-on-aws-deployment#211]
I tried to delete  my recourse via below code but it returns me an error that url not found.

String pt_url0 = "BASEURL/dev/Patient?identifier=1234";
		URL url0 = new URL(pt_url0);
		HttpURLConnection connection0 = (HttpURLConnection) url0.openConnection();
		connection0.setRequestProperty("Content-Type", "application/json; charset=utf-8");
		connection0.setRequestProperty("Authorization", cognitoAuthToken);
		connection0.setRequestProperty("x-api-key", API_KEY);
		connection0.setRequestMethod("DELETE");
		connection0.connect();
		System.out.println(connection0.getResponseCode());

**Comment by rsmayda** [comment]
Hey thanks for reaching out!

It looks like you are trying to delete off of a search query. The FHIR specification calls for a delete url to look like: 'DELETE [base]/[type]/[id]' 

https://www.hl7.org/fhir/http.html#delete

Please adjust your url and try again!

**Comment by fatemeh91** [comment]
Hi Thanks, 
I even change the url but the operation is not working.

String pt_url0 = "https://uwiv2v70ia.execute-api.us-west-2.amazonaws.com/dev/Patient?identifier=1234#delete";
		URL url0 = new URL(pt_url0);
		HttpURLConnection connection0 = (HttpURLConnection) url0.openConnection();
		connection0.setRequestProperty("Content-Type", "application/json; charset=utf-8");
		connection0.setRequestProperty("Authorization", cognitoAuthToken);
		connection0.setRequestProperty("x-api-key", API_KEY);
		connection0.connect();
		connection0.getInputStream();
It return ok status but it did not delete my record.

**Comment by rsmayda** [comment]
You would want the url to look like: DELETE https://uwiv2v70ia.execute-api.us-west-2.amazonaws.com/dev/Patient/1234￼

The DELETE in the beginning is the HTTP verb

**Comment by fatemeh91** [comment]
Then it returns me an 404 http request "Not Found "

**Comment by nguyen102** [comment]
Hi,

Your id is probably not `1234`. It should be in a `uuid` format. For example `b6addf75-f239-45e0-b262-52de197616c4`.

So you should be sending a DELETE request with a url that looks something like this
`https://uwiv2v70ia.execute-api.us-west-2.amazonaws.com/dev/Patient/b6addf75-f239-45e0-b262-52de197616c4`

**Comment by fatemeh91** [comment]
Hi,
I want to delete a patient record through his Encounter number (I declare  it in my patient recourse as Identifier). So I want to delete patient via its Encounter not the Id of the messages.

**Comment by nguyen102** [comment]
Ah, I see. In this case, it looks like you're trying to a [conditional delete](https://www.hl7.org/fhir/http.html#3.1.0.7.1).

"Unlike this rest of this page, the conditional create, update, patch and delete are trial use until further experience is gained with their use. Their status will be reviewed in a future version of FHIR."

The conditional delete is in trial use and we currently don't support that API. We currently only support delete using a `logical id`.

**Comment by fatemeh91** [comment]
okay thank you
