### ISSUE TITLE
SMART Backend Services: Server-to-server FHIR connections

### ISSUE THREAD

**Issue by rhinozD** [awslabs/fhir-works-on-aws-deployment#213]
Hi AWS Team,
Thanks for implementing the SMART on FHIR.
1. As I can see that [SMART Backend Services: Server-to-server FHIR connections](https://hl7.org/fhir/uv/bulkdata/authorization/index.html) was not supported yet, isn't it?
2. Can you show me how to deploy `patientPickerEndpoint`? Can I use the endpoint I have deployed using [fhir-works-on-aws-deployment mainline](https://github.com/awslabs/fhir-works-on-aws-deployment/tree/mainline)

Thanks in advance!

**Comment by rsmayda** [comment]
> 1. As I can see that [SMART Backend Services: Server-to-server FHIR connections](https://hl7.org/fhir/uv/bulkdata/authorization/index.html) was not supported yet, isn't it?

That is right, it is not supported. We are looking for customer feedback on server to server communications. We would love to learn of your use-case.

> 2\. Can you show me how to deploy `patientPickerEndpoint`? Can I use the endpoint I have deployed using [fhir-works-on-aws-deployment mainline](https://github.com/awslabs/fhir-works-on-aws-deployment/tree/mainline)

That Patient Picker Endpoint is used to get a Patient's launch context and the launch context is something that your Authorization server will handle. For an example Authorization Server implementation we recommend checking out [Okta's open source repository](https://github.com/dancinnamon-okta/okta-smartfhir-docs)

When you are ready to install the Resource Server side of things be sure to install from the `smart-mainline` branch: https://github.com/awslabs/fhir-works-on-aws-deployment/tree/smart-mainline. If your interested in seeing the AuthZ logic/code check out: https://github.com/awslabs/fhir-works-on-aws-authz-smart

For a clearer diagram of the flow see the below image: 
![SMART flow](https://user-images.githubusercontent.com/5750407/107907373-8a4f7880-6f21-11eb-9aa5-b89792cbe3a1.png)

**Comment by rmharrison** [comment]
@rsmayda Would you be open updating and adding this diagram to the README of both branch `mainline` and `smart-mainline`?

**Context**
> Prior to installing this stack you must know three things of your authorization server:
https://github.com/awslabs/fhir-works-on-aws-deployment/blob/55e9619c15d210290f643345d5c0f93b939d0854/README.md#prerequisites

This language is unclear to newcomers.
Indeed, without a (higher-level) component diagram in the main README.md, I don' think it will be clear what AWS FHIR Works does and doesn't offer.



**Proposed resolution**
> As you can tell from the architecture we expect the SMART compliant OAuth2 server to be set-up outside of this stack. If you have questions or concerns on how to do this please open an issue or check out SMART authorization server implementations like Okta's
https://github.com/awslabs/fhir-works-on-aws-deployment/blob/55e9619c15d210290f643345d5c0f93b939d0854/README.md#architecture

Burying the lead. The overall component diagram should come first, laying out what fhir-works-on-aws offers,THEN the component detail for fhir-works-on-aws.

For `smart-mainline`
Authorization Server: Not provided by fhir-works-on-aws. 
- Mention of your okta recommendation goes here.
- Optionally, link to [HL7 Confluence SMART on FHIR server implementations](https://confluence.hl7.org/display/FHIR/SMART+on+FHIR+server+implementations)

FHIR Works on AWS: Resource server.
- Show a sub-compnent for the authorization interface, specifically for SMART on FHIR.
- The diagram in `mainline`, would have the Cognito RBAC authorizer

Front-end: Not provided by fhir-works-on-aws.
- Optionally, link to front-end reference clients like canonical [growth chart app](https://github.com/smart-on-fhir/growth-chart-app)

**Comment by nguyen102** [comment]
Thanks for the detailed suggestions Harrison. Would you be willing to open a PR and contribute these changes to the community?

**Comment by rsmayda** [comment]
I will be working on this today, updating our docs

**Comment by rsmayda** [comment]
Merged in new docs to the `smart-develop` branch. If you have further questions or improvements please let us know!
