### ISSUE TITLE
[Feature Request] Patient $merge process 

### ISSUE THREAD

**Issue by PrimKruskal** [awslabs/fhir-works-on-aws-deployment#226]
Hello All,  Is there any plans for implementing patient Merge process.

https://www.hl7.org/fhir/patient.html#merge

Patient Merge/split is one of the frequently happening issue with HealthCare.

- John Smith’s record is created in the system with IOI id 12345 and Patient records get added in FHIR server with FHIR Patient “Resource id” as “abd5t-kiun4-u4li-d3rc”. Questions : Whether the same IOI “12345” is updated in member profile of identity provider for data access enablement via 3rd Party App?

- Later point of time, some source system sends the John Smith records and a new IOI 67891 is created due to some mismatch in demographic. A new FHIR Patient resource is being added in FHIR Server with FHIR Patient Resource id “kjkjl-iui34-qx3kx-apo98” and associated records are referenced to new FHIR Patient Resource id and updated in FHIR server.

- System (ETL process) identified that both 12345 and 67891 belongs to same patient and de-duplicate 6789. All the systems are updated to reflect 12345 instead of 67891 except FHIR Server. We would require strategy / process to de-link all the resources from resource id “kjkjl-iui34-qx3kx-apo98” and link to “abd5t-kiun4-u4li-d3rc” and remove the Patient resource with resource id “kjkjl-iui34-qx3kx-apo98”.

**Comment by rsmayda** [comment]
Hey! This is currently not on our near-term roadmap. We would be happy to support a contributor building this feature via design reviews and PRs

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
