### ISSUE TITLE
win_install.ps1 will raise an error stating that the 'StackName' parameter is not specified

### ISSUE THREAD

**Issue by rye442** [awslabs/fhir-works-on-aws-deployment#233]
I'm currently trying a Windows installation of FHIRWorks using [this page](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/INSTALL.md#windows-installation) as a reference.

scripts/win_install.ps1 will raise an error stating that the 'StackName' parameter is not specified.

Is this the intended behavior?

## Run command
```
.\scripts\win_install.ps1 -Region us-east-2 -Stage dev
```

## error details
```
Get-CFNStack : パラメーター 'StackName' の引数が指定されていません。型 'System.String' のパラメーターを指定し、再試行し
てください。
発生場所 C:\fhir\fhir-works-on-aws-deployment\scripts\win_install.ps1:216 文字:28
+     $redep = (Get-CFNStack -StackName -Region $region fhir-service-$s ...
+                            ~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Get-CFNStack]、ParameterBindingException
    + FullyQualifiedErrorId : MissingArgument,Amazon.PowerShell.Cmdlets.CFN.GetCFNStackCmdlet
```

**Comment by Bingjiling** [comment]
Hi @rye442 , thanks for sharing the details. I'll try recreating the issue on my end for Windows deployment. At the meantime, you could use Docker installation as a work around.

**Comment by nguyen102** [comment]
Closing this issue in favor of this issue.
https://github.com/awslabs/fhir-works-on-aws-deployment/issues/234

Steps for resolution will be discussed in that issue.
