### ISSUE TITLE
Error during win_install.ps1 execution - Lambda function is too large

### ISSUE THREAD

**Issue by rye442** [awslabs/fhir-works-on-aws-deployment#234]
I am trying to use FHIRWorks with Windows Install. when I run scripts/win_install.ps1, I get the InvalidParameterValueException.

I checked #184 and #166 before writing this issue. ```npm prune``` and ```npm dedupe``` were also tried, but they did not solve the problem.

I was not able to try the following commands because there was no awk command in my environment.
```sudo npm list -g --depth=0. | awk -F ' ' '{print $2}' | awk -F '@' '{print $1}' | sudo xargs npm remove -g```

## Run commands

```
npm prune
npm dedupe
.\scripts\win_install.ps1 -Region us-east-2 -Stage dev
```

## Error ditails
```
  Serverless Error ---------------------------------------

  An error occurred: UpdateStatusLambdaFunction - Unzipped size must be smaller than 262144000 bytes (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: eb10a477-29a7-4162-bab4-3d9a498564b9; Proxy: null).
```

## Environment Information
```
  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              14.4.0
     Framework Version:         1.83.2 (standalone)
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9
```

## Note
I got error #233 when I ran win_install.ps1, but this was not an error that could not be continued. For this reason, I ignored the #233 error and continue the program, which confirmed this error. I don't think this is relevant, but just in case, I'll mention it.

**Comment by Bingjiling** [comment]
Hi @rye442 , thanks for sharing the details. I'll try recreating the issue on my end for Windows deployment. At the meantime, you could use [Docker installation](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/INSTALL.md#docker-installation) as a work around.

**Comment by rye442** [comment]
Hi @Bingjiling, thanks for the reply. I am going to try Docker installation.

However, keep in mind that even if I can Docker installation, it will not solve the problem of not being able to Windows installation.

**Comment by Bingjiling** [comment]
Hi @rye442, thanks for the update. I recreated the issue with a Windows environment. We'll look further into the issue and keep you posted on the progress.

**Comment by nguyen102** [comment]
Hi @rye442 I currently have code in PR that might fix your issue.

https://github.com/awslabs/fhir-works-on-aws-deployment/pull/240

If you can try the code there.

Be sure to remove `serverless` and `node` that was installed through `choco`.

You can remove them using these commands 
```
choco uninstall nodejs.install
choco uninstall serverless
```

**Comment by rye442** [comment]
Hi @nguyen102, thanks for the reply. I tried it. It generally worked fine, but it produced two errors.

The first one is identical to #233. I got the following error message:
```
Get-CFNStack : Stack with id fhir-service-dev does not exist
発生場所 C:\work\mhir\fhir-works-on-aws-deployment\scripts\win_install.ps1:208 文字:1
+ Get-CFNStack -StackName fhir-service-$stage -Region $region 2>&1 | ou ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Amazon.PowerShe...tCFNStackCmdlet:GetCFNStackCmdlet) [Get-CFNStack]、I
    nvalidOperationException
    + FullyQualifiedErrorId : Amazon.CloudFormation.AmazonCloudFormationException,Amazon.PowerShell.Cmdlets.CFN.GetCFN
   StackCmdlet
```

The second error is that Info_Output.yml does not exist after the deployment is completed. The error message is shown below:
```
rm : パス 'C:\work\mhir\fhir-works-on-aws-deployment\Info_Output.yml' が存在しないため検出できません。
発生場所 C:\work\mhir\fhir-works-on-aws-deployment\scripts\win_install.ps1:277 文字:1
+ rm Info_Output.yml
+ ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\work\mhir\fh...Info_Output.yml:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
```

At any rate, the fix-warnings branch FHIR Works is now working as intended on my AWS account. Thanks for your help!

**Comment by nguyen102** [comment]
@rye442 That's great! I'm glad it's working for you. 
These two errors should really be warnings, as they don't affect the success of the script. 
The first error on line 208 occurs because the script is calling Cloudformation to see if the FHIR Service has already been deployed. Since it hasn't been deployed yet, it prints out the error you mentioned. Line 209 uses the result from line 208 to decided which code path to take.

The error on line 277 is because since this is the first time you're deploying the stack, you don't have an `Info_Output` file yet. Therefore, since there is nothing to delete, there is a delete error.

Noted, we should see if there is a way to not print these errors, as it can be misleading to users.

**Comment by rye442** [comment]
@nguyen102, Yes. It was printed out as an error, but since it was actually possible to continue, we assume that it did not affect the deployment operation. However, as you mentioned, I think it needs to be changed(e.g. using try-catch) to a warning as it may mislead the user.

**Comment by nguyen102** [comment]
Thanks for the suggestion @rye442  , we'll add this issue to our backlog, and will prioritize it accordingly.

I'll close this issue for now, since the original Bug reported in this issue is now resolved.

**Comment by nguyen102** [comment]
@rye442 There was a recent bug fix that might  have impacted you. The fix is in `mainline` now, so please pull the latest change from `mainline` and redeploy.

More details here
https://github.com/awslabs/fhir-works-on-aws-deployment/pull/243

You can deploy by running in the root director of the project
`yarn serverless-deploy --region <REGION> --stage <STAGE>`

**Comment by rye442** [comment]
Hi @nguyen102, thank you for letting me know. I have applied it to my environment.
