### ISSUE TITLE
Search based on identifier.system field on Patient api is not working

### ISSUE THREAD

**Issue by rye442** [awslabs/fhir-works-on-aws-deployment#242]
I tried to search for a patient by specifying the identifier.system in the Patient resource, but when I specify the system, it also returns unrelated patients.

## Request and Expected and Actual
The Expected and Actual is show the total value of the response (the number of patients that matched the condition).

|No.|Request|Expected|Actual|Result|
|:--:|--|:--:|:--:|:--:|
|1|GET {{API_URL}}/Patient?identifier=http://www.example.com\||2|4|**NG**|
|2|GET {{API_URL}}/Patient?identifier=http://www.example.com\|test1|1|4|**NG**|
|3|GET {{API_URL}}/Patient?identifier=test1|2|2|OK|
|4|GET {{API_URL}}/Patient?identifier=test2|1|1|OK|

## Registered patients
<details>
<summary>Registered patients</summary>

Patient1:
<code>
{
  "resourceType": "Patient",
  "identifier": [
    {
      "use": "official",
      "system": "http://example.com",
      "value": "test1"
    }
  ],
  "name": [
    {
      "given": ["test1"],
      "family": "Tester"
    }
  ]
}
</code>

Patient2:
<code>
{
  "resourceType": "Patient",
  "identifier": [
    {
      "use": "official",
      "system": "http://example.com",
      "value": "test2"
    }
  ],
  "name": [
    {
      "given": ["test2"],
      "family": "Tester"
    }
  ]
}
</code>

Patient3:
<code>
{
  "resourceType": "Patient",
  "identifier": [
    {
      "use": "official",
      "system": "http://www.example.com",
      "value": "test1"
    }
  ],
  "name": [
    {
      "given": ["test3"],
      "family": "Tester"
    }
  ]
}
</code>

Patient4:
<code>
{
  "resourceType": "Patient",
  "identifier": [
    {
      "use": "official",
      "system": "http://www.example.com",
      "value": "test4"
    }
  ],
  "name": [
    {
      "given": ["test4"],
      "family": "Tester"
    }
  ]
}
</code>
</details>

**Comment by nguyen102** [comment]
Hi, 
It looks like for request 1 and 2, you're trying to do a `token` search. We currently do not support `token` search. We currently search using string matching.

**Comment by rye442** [comment]
Hi @nguyen102, thanks for the reply.
Hmmm.... The ```token``` search is not supported....

Is there any way for me or other users to find out what search parameter type are supported by FHIR Works? In the Capabilities section of this repository, it only says "Search capabilities per resource type".
You said "We currently search using string matching.", do you mean that FHIR Works currently only supports String in [this](https://www.hl7.org/fhir/search.html) search parameter type?

**Comment by SanketD92** [comment]
Hello @rye442, we can search on all fields that are specified in our Capability Statement, which is available at `fhirServer/metadata`. However, even if those fields are not strings we can still search on them (in such cases we use string matching instead of the actual types). For example, with dates we should parse it as a date, but we parse it as a string. We're working on supporting the data types properly, especially dates.

**Comment by rye442** [comment]
Hello @SanketD92, thanks for letting me know the status of FHIR Works.

Our team considers it very important to be able to search for `Date` and `Token` (including `URI`) among the FHIR search parameter types shown on [this page](https://www.hl7.org/fhir/search.html) (followed by `Quantity`, `Number` and `Refelence`). I think it is important to support proper retrieval of data types when using the FHIR API. So, glad to know that you guys are working towards resolving this issue. Thank you for your cooperation.

**Comment by rsmayda** [comment]
In our most recent release we added token search enhancement: https://github.com/awslabs/fhir-works-on-aws-deployment/tree/v2.6.0

Could you ensure you are using the latest versions? If issues persist please reopen this issue 😄
