### ISSUE TITLE
Data of the wrong type can be registered. It can't be searched.

### ISSUE THREAD

**Issue by rye442** [awslabs/fhir-works-on-aws-deployment#255]
I believe that registering data of the wrong type should result in an error in the check during registration. And if we allow the registration of data of the wrong type, then we should be able to retrieve it in the GET resource as well. Am I wrong in my thinking?

## Detail
I first tried to register the following AllergyIntolerance And it was successful.
```
POST {{API URL}}/AllergyIntolerance

{
  "resourceType": "AllergyIntolerance",
  "patient": {
    "reference": "{{API URL}}/Patient/{{Patient ID}}"
  },
  "code": {
    "coding": [
      "code1"
    ]
  }
}
```

However, I was not able to get it in the Get All Resource Data. There were zero results.
```
GET {{API URL}}/AllergyIntolerance
```

I'm able to retrieve the data by directly referring to the DynamoDB data and performing a search conditional on the ```id```.
```
GET {{API URL}}/AllergyIntolerance/{{id}}
```

I noticed there that code.coding was registered as a String type, not a Coding type. I then re-registered the correct data.
```
POST {{API URL}}/AllergyIntolerance

{
  "resourceType": "AllergyIntolerance",
  "patient": {
    "reference": "{{API URL}}/Patient/{{Patient ID}}"
  },
  "code": {
    "coding": [
      {
        "display": "code2"
      }
    ]
  }
}
```

At this time, when we fetched the resource, one was returned (the one we registered the second time, of course).
```
GET {{API URL}}/AllergyIntolerance
```

**Comment by rsmayda** [comment]
This issue is the same as https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/issues/18. ElasticSearch indices are dynamically generated but once they are generated for a parameter the index is set.  

In this example your first POST makes `coding` a string array, then in your second POST you are trying to save `coding` as a array of objects. This will fail in the ddbToEs sync lambda. To fix we need to normalize the incoming data so that Elastic search can have static indexes.

**Comment by rye442** [comment]
Hi @rsmayda, thank you for your reply. Also, sorry about the duplicate issue.

Let me confirm to make sure that you have made the following statements in your references, is this situation still the same?
>We will start working on fixing this bug in early April. We plan to address the identification of this issue by putting in a DLQ and Cloudwatch Alarms. As for the static mapping, we do not currently have this on our roadmap, but would love to discuss more in our next stand-up.

**Comment by rsmayda** [comment]
Yep this is still accurate!
