### ISSUE TITLE
Question - Allow multiple values for search parameters in a GET request

### ISSUE THREAD

**Issue by shrutivardhan1411** [awslabs/fhir-works-on-aws-deployment#273]
We want to support for allowing multiple search values for a couple of search parameters such as Patient.Identifiers and Patient.Name
As part of FHIR specs(https://www.hl7.org/fhir/search.html#composite), single parameter with multiple values must be separated by a comma. 
How to distinguish between the values that might have a comma in them? 
For Example:  name in (user1, user2) versus name in ("**usersLastName ,user1**", user2 ). Should we use an escape character for the comma in the search value? 

Thanks!
Shruti

**Comment by SanketD92** [comment]
Thank you for your question, @shrutivardhan1411.

Currently FHIRWorks on AWS does not support searching for a single parameter with multiple values separated by a comma. I've opened a backlog ticket for the team to work on it according to feature priority. Once completed, the escape mechanism would work similar to the one specified [here](https://www.hl7.org/fhir/search.html#escaping).

**Comment by SanketD92** [comment]
Thank you for this question @shrutivardhan1411. 

Currently we do not support escape mechanism as mentioned in the FHIR [specs](https://www.hl7.org/fhir/search.html#escaping) in our search API call, but we'd like to understand your use-case better.

I'm assuming you're planning to use the search patient API to filter users based on specific params (eg. name). If so, does this example better fit your question:

Patient 1: Given name: `John`; Last name: `Smith`
Patient 2: Given name: `Jane`; Last name: `Doe, Mary`
Search API call: `{{API_URL}}/Patient?name=Doe,Smith`
Results in entry: [Patient 1, Patient 2]

**Comment by shrutivardhan1411** [comment]
> Thank you for this question @shrutivardhan1411.
> 
> Currently we do not support escape mechanism as mentioned in the FHIR [specs](https://www.hl7.org/fhir/search.html#escaping) in our search API call, but we'd like to understand your use-case better.
> 
> I'm assuming you're planning to use the search patient API to filter users based on specific params (eg. name). If so, does this example better fit your question:
> 
> Patient 1: Given name: `John`; Last name: `Smith`
> Patient 2: Given name: `Jane`; Last name: `Doe, Mary`
> Search API call: `{{API_URL}}/Patient?name=Doe,Smith`
> Results in entry: [Patient 1, Patient 2]

@SanketD92  The result here is not correct as currently Partial search for names is not supported.
> Search API call: `{{API_URL}}/Patient?name=Doe,Smith` would only result [Patient 1]
if I change the search API call to `{{API_URL}}/Patient?name=Doe, Mary, Smith`  then the result should return [Patient 1, Patient 2].
**Comma in** "Doe, Mary" is a part of the search value.  
Input received at backend` {name: ["Doe, Mary, Smith"]} `which will be interpreted as 3 separate values for search
How should it be escaped in the query string so that backend interprets this as 2 values rather than 3 search values.

**Comment by SanketD92** [comment]
Thank you for confirming your use-case, @shrutivardhan1411. 

We have created a backlog item for this to work toward which will be factored in by priority. 
Let us know if you deem this requirement urgent.

**Comment by shrutivardhan1411** [comment]
@SanketD92 It will be great if this feature is added. However we are thinking to customize this at our end for now. It would be helpful if you could share insights on interpreting the input that has a comma in the search values as discussed above.

Thanks in advance!

**Comment by SanketD92** [comment]
@shrutivardhan1411 we'd love to help you customize this feature to your needs.

The search query is formed [here](https://github.com/awslabs/fhir-works-on-aws-routing/blob/b57b54c7ee0ef67799a14ffb6bc66a7e25977659/src/router/handlers/resourceHandler.ts#L74) on the routing package, which is then sent over to the elastic search service.

This [file](https://github.com/awslabs/fhir-works-on-aws-search-es/blob/623c75af291c7c795b263a785f1d73a1dcffd066/src/elasticSearchService.ts#L85) in the elastic search package might serve as a good entry point in breaking down incoming query params. If the params contain an escaped comma, it would need to be sent as-is, whereas if contains a comma without an escape character, it is to be handled as an OR condition.

For testing your changes locally, please use these [instructions](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/dc9d0beb091263e55ea244f51703041615da03b5/DEVELOPMENT.md) for a smoother development experience.

**Comment by shrutivardhan1411** [comment]
Thanks!! @SanketD92
