### ISSUE TITLE
Errors running install

### ISSUE THREAD

**Issue by phackwer** [awslabs/fhir-works-on-aws-deployment#292]
On Linux Ubuntu 20.10, dist-updated last 12/04/21 after all dependencies were solved (minor problem between node-js and node-doc manually solved by running

```
# apt install -y libnode72 nodejs-doc
# apt remove  nodejs-doc
# apt install -y nodejs
```

I've ended up with 3 errors

```
Done!
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'
```

and 

`Serverless plugin "serverless-step-functions" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.`

![image](https://user-images.githubusercontent.com/4871786/115439027-060dc000-a206-11eb-8d2d-7b881bace697.png)

All versions I could think of are in the screenshots. 

Let me know if you need more information from us.

**Comment by phackwer** [comment]
Manually ran

```
npm install --save-dev serverless-step-functions
```

Now I have 

![image](https://user-images.githubusercontent.com/4871786/115440444-a2849200-a207-11eb-8a27-e1227c8fa47b.png)

**Comment by phackwer** [comment]
ran
```
npm install --save-dev serverless-bundle
```

and now gotta

![image](https://user-images.githubusercontent.com/4871786/115440780-08711980-a208-11eb-96ab-5e03302b49d4.png)

Seems to me that dependencies were not installed by the script.I will try to map all of the missing dependencies here, ok? Hope that helps.

**Comment by phackwer** [comment]
Ok, seems that the cause of the problems was Yarn. For some reason the yarn I had here was why I had those messages here:

```
Done!
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'
```

I've ran 
```
npm remove --global yarn
npm install --global yarn
yarn install
yarn run release
```

manually and it is now working. I've ran yarn --version and got 0.32+git as response before removing it. Now I've got yarn --version 1.22.10. I don't use Yarn so I'm unsure where this yarn I had came from, but seems that a version check on yarn would avoid problems.

Script is running ok. I will leave this ticket open as there is something there, maybe not important, but there is something that seems to be missing in the install script on Linux.

Cheers.

![image](https://user-images.githubusercontent.com/4871786/115442523-04de9200-a20a-11eb-80ba-3a840cba7ba6.png)

**Comment by phackwer** [comment]
Obs: had an infinite loop on a password setting. Had to CTRL+C as there is no info on where this is happening. Some feedback on this would also help. Left it running for over 2 minutes and no return that I could debug. If I only knew where to set this password, would help a lot. 

![image](https://user-images.githubusercontent.com/4871786/115458251-652aff00-a21d-11eb-90aa-1625b0449e43.png)

**Comment by nguyen102** [comment]
Looking at the code, it looks like the error is caused by this step
https://github.com/awslabs/fhir-works-on-aws-deployment/blob/12ea6bfe0a2953caa2bd567b560fcda1c8747ce2/scripts/install.sh#L355

It looks like at this step the FHIR Server has been successfully deployed, so you should be able to start using it. You will need a Cognito user to log in though. 

You can follow the instructions [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/1d613edcd437decc3101ce4fcea53ab6c949419c/INSTALL.md#initialize-cognito) to create a Cognito user for logging in.

**Comment by nguyen102** [comment]
> Ok, seems that the cause of the problems was Yarn. For some reason the yarn I had here was why I had those messages here:
> 
> ```
> Done!
> 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
> 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'
> ```
> 
> I've ran
> 
> ```
> npm remove --global yarn
> npm install --global yarn
> yarn install
> yarn run release
> ```
> 
> manually and it is now working. I've ran yarn --version and got 0.32+git as response before removing it. Now I've got yarn --version 1.22.10. I don't use Yarn so I'm unsure where this yarn I had came from, but seems that a version check on yarn would avoid problems.
> 
> Script is running ok. I will leave this ticket open as there is something there, maybe not important, but there is something that seems to be missing in the install script on Linux.
> 
> Cheers.
> 
> ![image](https://user-images.githubusercontent.com/4871786/115442523-04de9200-a20a-11eb-80ba-3a840cba7ba6.png)

Hmm, I tried to reproduce the issue by launching a new Ubuntu 20.04 instance (ami-0ca5c3bd5a268e7db). From that instance, it was able to complete the install process from start to finish. I wonder if your system, might have inadvertently have `yarn` installed already by another piece of software. The command in the `install.sh` script that installs yarn is `sudo $PKG_MANAGER install yarn -y`, which should install the latest version of yarn. In this case it should be `1.22.5`

**Comment by phackwer** [comment]
> Looking at the code, it looks like the error is caused by this step
> https://github.com/awslabs/fhir-works-on-aws-deployment/blob/12ea6bfe0a2953caa2bd567b560fcda1c8747ce2/scripts/install.sh#L355
> 
> It looks like at this step the FHIR Server has been successfully deployed, so you should be able to start using it. You will need a Cognito user to log in though.
> 
> You can follow the instructions [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/1d613edcd437decc3101ce4fcea53ab6c949419c/INSTALL.md#initialize-cognito) to create a Cognito user for logging in.

Oh, ok, I've found my error. :-D I've piped "yes | ./script/install..."...

**Comment by phackwer** [comment]
> > Ok, seems that the cause of the problems was Yarn. For some reason the yarn I had here was why I had those messages here:
> > ```
> > Done!
> > 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'
> > 00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'run'
> > ```
> > 
> > 
> > I've ran
> > ```
> > npm remove --global yarn
> > npm install --global yarn
> > yarn install
> > yarn run release
> > ```
> > 
> > 
> > manually and it is now working. I've ran yarn --version and got 0.32+git as response before removing it. Now I've got yarn --version 1.22.10. I don't use Yarn so I'm unsure where this yarn I had came from, but seems that a version check on yarn would avoid problems.
> > Script is running ok. I will leave this ticket open as there is something there, maybe not important, but there is something that seems to be missing in the install script on Linux.
> > Cheers.
> > ![image](https://user-images.githubusercontent.com/4871786/115442523-04de9200-a20a-11eb-80ba-3a840cba7ba6.png)
> 
> Hmm, I tried to reproduce the issue by launching a new Ubuntu 20.04 instance (ami-0ca5c3bd5a268e7db). From that instance, it was able to complete the install process from start to finish. I wonder if your system, might have inadvertently have `yarn` installed already by another piece of software. The command in the `install.sh` script that installs yarn is `sudo $PKG_MANAGER install yarn -y`, which should install the latest version of yarn. In this case it should be `1.22.5`

Yeah, it got solved when I removed and reinstall yarn. Maybe a version check would be nice.

Anyway, most of the problems were my environment, so, I'm closing the issue. Only suggestion I can give is to check the yarn version as it lead to all types of "missing packages" errors and I had the wrong impression that the script was not getting it.

Cheers.
