### ISSUE TITLE
Info_Output.yml is full of deprecation notices from Serverless

### ISSUE THREAD

**Issue by phackwer** [awslabs/fhir-works-on-aws-deployment#293]
Hi,

Although it's manually easy to solve, there are deprecation notes from Serverless being written in Info_Output.yml.

![image](https://user-images.githubusercontent.com/4871786/115525918-73156a00-a287-11eb-81da-24100356ebec.png)

**Comment by phackwer** [comment]
I'm assuming it's safe to delete up to line 25, correct?

**Comment by nguyen102** [comment]
Yep, you're correct. You can delete all of the warning lines. I've added a PR to fix this issue in the install script
https://github.com/awslabs/fhir-works-on-aws-deployment/pull/294

**Comment by phackwer** [comment]
Thanks. Cheers
