### ISSUE TITLE
[Feature Request] Subscriptions Support

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#297]
Is [subscriptions](https://www.hl7.org/fhir/subscription.htm) support on the roadmap? Seems like it would match up nicely with SNS.

**Comment by nguyen102** [comment]
Hi, Zambonilli.

Subscriptions is in our backlog, but is not currently on our near term road map. Can you provide more details about your use case for subscription and it's urgency?

This will provide us with an additional data point on customer needs, and will help us prioritize our back log items to reflect that.

**Comment by Zambonilli** [comment]
Sure, no problem.

The short term need is for syncing up other internal systems through a strongly typed application level API. For example, syncing up our internal BI and data lakes via subscriptions would be better than using dynamodb Change Data Capture because we can keep an API that talks FHIR between the systems. Not a show stopper but as more FWoA internal bits get added to dynamoDB the more coordination of changes would be required with subscribers. Whereas, using subscriptions we'd be able to say it's a FHIR R4 API and stick to that interface with all the open documentation, tooling, etc.

The medium term need is for data exchange with health systems. A use case for us would be exchanging admissions data for patients in near time for both automatic retraining of models and as input factors to models. More examples would be pushing near time predictions for interventions to compliance or potentially new admissions.

**Comment by nguyen102** [comment]
This was very helpful. Thanks for those detailed use case. I'll add this information to our backlog ticket for subscription. I'll update this issue when I have more information on when we can start working on subscription.

**Comment by Zambonilli** [comment]
Since subscriptions are pretty core to FHIR but the implementation is a beast, can the community help with some of the more independent and tricky bits? If I play out the psuedo code in my head for the implementation, 3 independent and tricky spots jump out.

1. typescript/javascript way to evaluate all subscription's criteria against resources when writen -This seems like the most challenging due to the complexity of the search spec and poor CPU performance of js runtimes. This smells like it could be pulled out into it's own module and it's implementation would be similar to that of the elastic search module where we'd go from a spec -> BNF -> AST -> js operators.
2. Evaluation of security - Find a way to extend the reuse or extend the security interfaces to evaluate the identity associated with the subscription against the resource. This seems pretty natural from a code standpoint but the subscription spec is a bit ambiguous on the implementation.
3. channel support - Finding a way to not rewrite the wheel to do channel support. Since SNS supports most of the channel options find a way to map subscriptions effectively to SNS. Possibly find a way to do a webhook pool effectively and integrate with SNS so we can keep the publisher interface SNS only.

Let me know if this lines up with what you guys are seeing and if the community can help here.

**Comment by Zambonilli** [comment]
FYI, FHIR R4b and R5 look to be reworking the subscriptions model to the more classical topics and subscriptions (that can include filters). This should make the implementation here a bit more tenable than register random query and get answers.

**Comment by Zambonilli** [comment]
https://onedrive.live.com/view.aspx?cid=cfea2adeb18402af&page=view&resid=CFEA2ADEB18402AF!78090&parId=CFEA2ADEB18402AF!77955&authkey=!APp9BdFprziM8j0&app=PowerPoint

**Comment by Zambonilli** [comment]
Implemented with fwoa release 4.2.0. Awesome work fwoa team!

https://github.com/awslabs/fhir-works-on-aws-deployment/releases/tag/v4.2.0
