### ISSUE TITLE
Cognito App Client is not created with a secret

### ISSUE THREAD

**Issue by phackwer** [awslabs/fhir-works-on-aws-deployment#303]
After running install I've noticed the Cognito App Client has no Secret to it. Please, add secret on this for better security, as this would require us to hash the secret and then hash it with the client to get the correct SecretHash/SECRET_HASH value for the Cognito API

**Comment by phackwer** [comment]
PS: Secret can be acquired from the Cognito AWS Console, but having it on Info_Output.yml would be handy

**Comment by carvantes** [comment]
Hi,

We decided to default to a User Pool App Client without a secret for flexibility. Clients with secrets are notably not a good fit for browser-based applications.

It is good practice to have multiple App Clients, one per application. e.g. you could have an App Client without secret for a FHIR web application, and another App Client with secret for a mobile application.

I'd suggest that you create an additional UserPoolClient with a secret if that fits better the use case of your application(or simply update the existing one to enable a secret if you don't plan to have browser-based apps)

https://docs.aws.amazon.com/cognito/latest/developerguide/user-pool-settings-client-apps.html

**Comment by phackwer** [comment]
Ok. In our case browser and apps won't talk to any of the FHIR components directly, so this is why I thought this could be a problem. I'm closing this issue, happy with the comment. Cheers!
