### ISSUE TITLE
How can I get the lastN observations? 

### ISSUE THREAD

**Issue by luisberga** [awslabs/fhir-works-on-aws-deployment#309]
I'm trying to use the LastN Operation in my rest request, something like `{{API_URL}}/Observation/$lastn`, but i get the following error: 

`{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">error</td><td>[]</td><td><pre>Resource Observation/$lastn is not known</pre></td></tr></table></div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "not-found",
            "diagnostics": "Resource Observation/$lastn is not known"
        }
    ]
}`

Does FHIR WORKS suports LastN operation? 

Thank you

**Comment by rsmayda** [comment]
As `$lastn` is still in trial use and hasn't been moved to the normative status, we haven't prioritized supporting this operation. To get a better grasp on what FHIR Works support I suggest hitting the `/metadata` endpoint to get the capability statement.

For our planning purposes could you let us know how important this operation is for your success?

Context:
- https://www.hl7.org/fhir/observation-operation-lastn.html

**Comment by luisberga** [comment]
Hello! 

My need is always to show the last data from the observation resource when making the REST request. Would you have any idea how to do it without having the $ lastN operation?

For example, in the Observation me resource I have N records. I need to make the REST request and get the latest one.

**Comment by rsmayda** [comment]
> Would you have any idea how to do it without having the $ lastN operation?

I would look into using the `_sort` field as describe by [FHIR](https://www.hl7.org/fhir/search.html#sort) and the `_lastUpdated` parameter to get the most recent results. 

We recently added support for sort too: https://github.com/awslabs/fhir-works-on-aws-search-es/commit/a7d9bf02228cf6d2b0efd5de608cd3ee4b5b3089

**Comment by luisberga** [comment]
Ok! Thank you =D
