### ISSUE TITLE
Accessing FHIR API from another API

### ISSUE THREAD

**Issue by gopalp19** [awslabs/fhir-works-on-aws-deployment#314]
Hi,
My team has built an API that directly accesses resources from the FHIR Works API. We're currently using the default FHIR Works implementation and have been generating Cognito tokens in our API to interact with the FHIR API. Our API will be accessible from a front-end and have it's own IDP and auth protocol. Is accessing the FHIR API (using Cognito) from another API a recommended approach or is there another way to go about doing this? Thanks!

**Comment by rsmayda** [comment]
I would definitely recommend running any security related changes to your security leads, but for some ideas this is probably the best place to start: https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-control-access-to-api.html

For system to system communication the Cognito approach maybe overkill, but that depends on if the FHIR Works server should "trust" the calling service. An alternative is to use IAM Roles which allow access to call the FHIR Works API GW
