### ISSUE TITLE
Best way to show fhir data from fhir works api in real time on a dashboard

### ISSUE THREAD

**Issue by luisberga** [awslabs/fhir-works-on-aws-deployment#315]
Goodnight!

I need to show the coming data (like values from Observation resource) from the FHIR WORKS api on a dashboard, in real time...

I saw that Grafana has the SimpleJson plugin, but it is necessary to change the api gateway of the FHIR WORK solution. I didn't see opportunities in quicksight, either.

How could I send data from an AWS FHIR server resource to a real-time dashboard? Would you have any suggestions? 

Thanks

**Comment by rsmayda** [comment]
If you want more system level metrics (number or POSTs, Writes to DB, etc) CloudWatch is your best bet. But if you want to a dashboard of real-time real patient data...

Just a quick caution you may be sharing PHI (be careful)! Assuming that is what you want to do you could add write these events to an SNS topic and that topic can then be used/read in many different ways (almost like a pub/sub)

**Comment by nguyen102** [comment]
If you're building the dashboard yourself, another option is to use the [setInterval](https://www.w3schools.com/jsref/met_win_setinterval.asp) function to repeatedly call the FHIR API. Doing this will allow you to get updated data from the FHIR server based on the time interval that is set.

**Comment by luisberga** [comment]
Hello! 

In my case, I want to build a real-time dashboard with patient data. Since it's a real-time dashboard, I need to retrieve data directly from FHIR API, making a rest requisition. This will be my data source. 

What you guys think about the Kafka Superset? 

Thank you.

**Comment by rsmayda** [comment]
I honestly don't know much about Kafka or Superset but a quick read: https://medium.com/streamthoughts/how-to-build-a-real-time-analytical-platform-using-kafka-ksqldb-and-clickhouse-bfabd65d05e4. It seems to be event processing (similar to SNS/SQS) and I don't see why that wouldn't work. 

A question you should figure out is how "real-time" this dashboard needs to be, the closer to true real-time the more complex the system will be. If you are okay with user driven or say hourly updates (i.e. user clicks refresh) you could just query the DDB directly for data and not worry about streaming.

**Comment by luisberga** [comment]
Helo!

Thanks for the suggestions.

I chose to use Grafana and make a REST request to the FHIR server as a database.

A doubt... I am viewing the data on the dashboard through a query in the request URL to obtain the data every five minutes, that is, the data "now" until five minutes later.

I'm using the _count feature to limit the number of records to a maximum of 10000, which is the maximum that FHIR server accepts... Would you know to tell me if there is a possibility of not limiting, that is, showing all records, for example, more that 10000?

Thanks

**Comment by nguyen102** [comment]
At this time we do not support showing more than 10,000 records. We use ElasticSearch to search for data and by default this is the limit ElasticSearch places on the search request. I would be careful of trying to query for more than 10,000 records as that might cause performance issue on your ES cluster.

**Comment by luisberga** [comment]
Understood... Is there a way to query the URL with code.coding.display? 

```
"code": {
    "coding": [
        {
            "system": "http://loinc.org",
            "code": "883-9",
            "display": "O2"
        }
    ]
}
```

I'm trying to query like `{{API_URL}}/Observation?code.coding.display=O2`, but it shows the following error: 

`Invalid search parameter 'code.coding.display' for resource type Observation`
