### ISSUE TITLE
S3 buckets do not have server side encryption 

### ISSUE THREAD

**Issue by lindenquan** [awslabs/fhir-works-on-aws-deployment#317]
After deploying the FHIR, all S3 buckets have server side encryption except one "fhir-service-dev-fhirbinarybucket".  Could you make sure all buckets have server side encryption? 

I'm also curious why there are multiple binary/log buckets.  Could it be possible that if a bucket is created dynamically by lambda function, then it could not have enabled server-side encryption ?
Thanks

**Comment by rsmayda** [comment]
Binary buckets do have a CMK SSE: https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/serverless.yaml#L338

**Comment by lindenquan** [comment]
Thanks for quick replying. I found the root cause. Destroying fhir-service at CloudFormation console doesn't delete s3 log and binary bucket, but deletes associated keys. And these buckets are displayed with no service side encryption. 

As you pointed out, it did create buckets with server-side encryption.

**Comment by lindenquan** [comment]
It would be great if destroying would delete all buckets. But this issue I opened up can be marked as resolved. Thanks again

**Comment by rsmayda** [comment]
Yep 100% agree -- This feature is a Cloud formation setting, and is there to protect customer data (prevents accidentally deleting important information) 

Can learn more here: https://stackoverflow.com/questions/40383470/can-i-force-cloudformation-to-delete-non-empty-s3-bucket
