### ISSUE TITLE
updating deployed version

### ISSUE THREAD

**Issue by DanGrund** [awslabs/fhir-works-on-aws-deployment#318]
I initially deployed using the cloud formation template linked from the [aws docs](https://docs.aws.amazon.com/solutions/latest/fhir-works-on-aws/aws-cloudformation-template.html), which is labeled as 'latest', but seems to be pointing to  v2.1.3 line 58: `"S3Key": "fhir-works-on-aws/v2.1.3/fhir-service.zip"`. I need to incorporate a fix that's in v2.6.0, but can't find a template that points to the newer version. I'm a cloud formation amateur, is there something simple I'm missing to update to latest fhir works?

**Comment by rsmayda** [comment]
Hey Dan!

Thanks for reaching out and sorry for the confusion the AWS Solution page is unfortunately out of date with our main GitHub repository. To get the newest code we recommend following the GitHub related installation guide: https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/INSTALL.md
