### ISSUE TITLE
Search for exactly subject reference 

### ISSUE THREAD

**Issue by luisberga** [awslabs/fhir-works-on-aws-deployment#329]
I was testing a feature in FHIR Server... For example, If I have only have 2 records with reference `Device/03684ba8-a2aa-4096-a848-61af6305fb58` and 38 records with reference `Device/03684ba8-a2aa-4096-a848-61af6305fb59`.

When I do the following query:

`{{API_URL}}/Observation/?device=Device/03684ba8-a2aa-4096-a848-61af6305fb58`

I get the response of 40 records, including the 2 records of `Device/03684ba8-a2aa-4096-a848-61af6305fb58` and another 38 records with reference `Device/03684ba8-a2aa-4096-a848-61af6305fb59`.

I only need to get the response of the 2 `Device/03684ba8-a2aa-4096-a848-61af6305fb58` records. 

How can I do it? I tried [device:reference](https://www.hl7.org/fhir/search.html#reference) but I get the following error: 

`    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "Invalid search parameter 'device:reference' for resource type Observation"
        }
    ]`

Thank you.

**Comment by luisberga** [comment]
For example, my body request could be: 

```
{
   "resourceType":"Bundle",
   "type":"transaction",
   "entry":[
      {
         "resource":{
            "resourceType":"Observation",
            "code":{
               "coding":[
                  {
                     "system":"http://loinc.org",
                     "code":"883-9",
                     "display":"Pulse Rate"
                  }
               ]
            },
            "valueQuantity":{
               "value":90,
               "unit":"1/min",
               "system":"http://unitsofmeasure.org"
            },
            "device":{
               "reference":"urn:uuid:luis-e509-4bfd-abed-b45cfefccfa2"
            },
            "status":"final"
         },
         "request":{
            "method":"POST",
            "url":"Observation"
         }
      },
      {
         "resource":{
            "resourceType":"Observation",
            "code":{
               "coding":[
                  {
                     "system":"http://loinc.org",
                     "code":"883-9",
                     "display":"Endtidal CO2 in %"
                  }
               ]
            },
            "valueQuantity":{
               "value":2,
               "unit":"%",
               "system":"http://unitsofmeasure.org"
            },
            "device":{
               "reference":"urn:uuid:luis-e509-4bfd-abed-b45cfefccfaf"
            },
            "status":"final"
         },
         "request":{
            "method":"POST",
            "url":"Observation"
         }
      },
      {
         "resource":{
            "resourceType":"Observation",
            "code":{
               "coding":[
                  {
                     "system":"http://loinc.org",
                     "code":"883-9",
                     "display":"Oxygen Saturation"
                  }
               ]
            },
            "valueQuantity":{
               "value":98,
               "unit":"%",
               "system":"http://unitsofmeasure.org"
            },
            "device":{
               "reference":"urn:uuid:luis-e509-4bfd-abed-b45cfefccfa2"
            },
            "status":"final"
         },
         "request":{
            "method":"POST",
            "url":"Observation"
         }
      }
   ]
}
```

**Comment by luisberga** [comment]
I'm trying to query display, too: 

```
"code":
{
    "coding": [
            {
                "system": "http://loinc.org",
                "code": "883-9",
                "display": "O2"
            }
    ]
}
```

But I can't, either... Please, could you help me? 

Thank you

**Comment by carvantes** [comment]
Hi, 

the query `{{API_URL}}/Observation/?device=Device/03684ba8-a2aa-4096-a848-61af6305fb58` is correct. There was a bug where querying for references was using full text search instead of exact string matching and that lead to unwanted search results as you described.

The fix is https://github.com/awslabs/fhir-works-on-aws-search-es/pull/74 and will be part of the next release

**Comment by carvantes** [comment]
I believe that the correct syntax to query `display` within a code would be `{{API_URL}}/Observation?code:text=02`, but the `:text` modifier for token parameters is not currently supported in FHIR Works.

Would you mind telling us a bit more about your use case for querying the `display` field of a code? That would help us get this feature prioritized

https://www.hl7.org/fhir/search.html#token

**Comment by luisberga** [comment]
Thank you for the advice. About the `:text` feature, to search display info, like: 

`{{API_URL}}/Observation?code:text=headache`

Any idea when it will be available? Or, is there any other way to get information from the display field?

```
"code":
{
    "coding": [
            {
                "system": "http://loinc.org",
                "code": "883-9",
                "display": "O2"
            }
    ]
}
```

I've tried  `{{API_URL}}/Observation?code=O2` but it returns no values.

Thank you

**Comment by luisberga** [comment]
Hello Carvantes, how are you? 

Thank you for the update. 

About the display... I use the REST call of the FHIR Works API as the Grafana database. There, I show the data in real time, with an 1 second update time. 

At the moment, I have a lot of data from specific sensors, for example, Oximetry, Pulsation, CO2 level, among others... It would be ideal and inevitable that I could query the `display`, that is, where it informs the type of measurement, for that the request for each Grafana panel for the FHIR server is specific to each sensor, not overloading the network.

That is, each request in the FHIR API would be unique for each sensor. There would be no data from other sensors, only the one that I've filtered in request URL. 

Today, each request for each grafana panel receives all data from all sensors at a given time. After completing the request, I configured the grafana to filter the data and show only the sensor corresponding to the panel I want to show (for example, the CO2 panel only shows the CO2 data).

**Comment by carvantes** [comment]
Thanks for sharing more details.

The fix for the issue of searching for exact subject reference was released as part of `fhir-works-on-aws-search-es@2.6.1`. We'll update the version on `fhir-works-on-aws-deployment` alongside a few other changes later this week, but you can update to the latest `fhir-works-on-aws-search-es` to get the fix now.

**Comment by rsmayda** [comment]
With our most recent release: https://github.com/awslabs/fhir-works-on-aws-deployment/releases/tag/v2.8.0 (Search version 2.6.1). This issue is resolved!

Please reopen if you have further questions or concerns
