### ISSUE TITLE
[Feature Request] [RFC] Auto-archiving support (DDB -> S3)

### ISSUE THREAD

**Issue by rsmayda** [awslabs/fhir-works-on-aws-deployment#340]
## Request for Comment

To the community please express your opinion for this issue. You can use 👍 for "we will use it" or 👎 "we wouldn't use it".

### Overview of change

A patient's online data is archived out of DynamoDB after 6 months and moved into S3 for a period of 10 years. The requestor is planning on using the archiving functionality to support privacy and regulatory requirement of keeping audit events online for only 6 months in the EU. This is for GDPR and HDS.

#### Technical impact/approach

* Optional configuration; turning this feature "on" will make the [persistence-ddb package](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb) use time to live logic auto-deleting a resource after the specified amount of time.
* Adding a firehose script into the persistence-ddb package which will catch the resource delete actions and move them to S3. 
* After the resource has been archived it will also be removed from ElasticSearch
* The current approach treats are resources the same
* If a resource is updated then it and all the historical elements will have a "fresh" time to live (TTL). For example Patient/1234 expires on 5/30/2021 but it is updated on 5/28/2021: version 1 will have a new TTL of 11/28/2021 AND the newly created version 2 will have a TTL of 11/28/2021

### Concerns

* Is this a too specialized feature for the persistence package to "own"?
  * Is there a better way to shift some of the "ownership" out of the persistence package? (perhaps moving the firehose script to the custom deployment package)

### Requestor

@Zambonilli

### Appendix additional information

Related original issue: https://github.com/awslabs/fhir-works-on-aws-deployment/issues/290
Existing PRs: https://github.com/awslabs/fhir-works-on-aws-deployment/pull/330 & https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/pull/73

**Comment by rsmayda** [comment]
Hey @Zambonilli! So we haven't got a lot of traction on adding this feature to FWoA. There could be some middle ground, of adding some but not all of the https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/pull/73 PR. Any thoughts on that? Does you having to maintain your own persistence package serve as a blocker?

**Comment by Zambonilli** [comment]
No worries, we have a release branch of 3.0.0 in our public fork that includes the archiving logic and the private API gateway. This prevents any blockers in the short term and gives us breathing room to do this right.

Long term, we obviously want to get archiving to be a 1st class citizen in fwoa so we can minimize the delta between upstream and our forks. Is there a path here where we can create infrastructure+module(s) that are optional not part of the normal persistence paths and not installed by default? I'm thinking maybe an optional module that listens for dyanmoDB writes from the ddb stream and updates resource records with the ttl field based on the archive configuration.

**Comment by rsmayda** [comment]
+1 to this idea:

> I'm thinking maybe an optional module that listens for dyanmoDB writes from the ddb stream and updates resource records with the ttl field based on the archive configuration.

That could be a good path -- We are unfortunately pretty loaded until mid August. We should try to reconvene then to determine what that would/could look like

**Comment by rsmayda** [comment]
Due to limited interest more broadly on this feature at this time we will close this ticket. In the future if interest changes please re-open this ticket!
