### ISSUE TITLE
[Feature Request] Composite search with multiple patient ids in Observation (OR searches).

### ISSUE THREAD

**Issue by ericfuxealth** [awslabs/fhir-works-on-aws-deployment#341]
**Describe the bug**
Passing multiple patient ids in observation search returns empty result. 
Composite search in some situations work though, e.g. 
GET <BaseURL>/Patient?name=smith, james works as expected.

**To Reproduce**
1. Create two patients, with id p1 and p2
2. Create an observation for each patient
3. `GET <BaseURL>/Observation?subject=Patient/p1` and `GET <BaseURL>/Observation?subject=Patient/p2 `both works as expected.
4. `GET <BaseURL>/Observation?subject=Patient/p1,Patient/p2 `returns bundle with empty array

**Expected behavior**
Would expect  `GET <BaseURL>/Observation?subject=Patient/p1,Patient/p2` to return observations for both patients.

**Screenshots**

**Versions (please complete the following information):**
2.8.0

**Additional context**
Composite search in some situations work though, e.g. 
`GET <BaseURL>/Patient?name=smith, james` works as expected.

**Comment by rsmayda** [comment]
Thanks for reporting this we will try to replicate and confirm this soon

**Comment by nguyen102** [comment]
Status update: I was able to reproduce this by running the following commands

**Create Observation and Patients**
```
{
  "resourceType": "Bundle",
  "type": "transaction",
  "entry": [
    {
      "fullUrl": "https://API_URL.com/Patient/1",
      "resource": {
        "resourceType": "Patient",
        "id": "1",
        "name": [
          {
            "family": "Simpson",
            "given": [
              "Homer"
            ]
          }
        ],
        "gender": "male"
      },
      "request": {
        "method": "POST",
        "url": "Patient"
      }
    },
    {
      "fullUrl": "https://API_URL.com/Patient/2",
      "resource": {
        "id": "2", 
        "resourceType": "Patient",
        "name": [
          {
            "family": "Simpson",
            "given": [
              "Lisa"
            ]
          }
        ],
        "gender": "female"
      },
      "request": {
        "method": "POST",
        "url": "Patient/2"
      }
    },
    {
      "fullUrl": "https://API_URL.com/Observation/1",
      "resource": {
        "resourceType": "Observation",
        "status": "final",
        "id": "1",
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "15074-8",
              "display": "Glucose [Moles/volume] in Blood"
            }
          ]
        },
        "subject": {
          "reference": "Patient/1"
        }
      },
      "request": {
        "method": "POST",
        "url": "Observation"
      }
    },
    {
      "fullUrl": "https://API_URL.com/Observation/2",
      "resource": {
        "resourceType": "Observation",
        "id": "2",
        "status": "final",
        "code": {
          "coding": [
            {
              "system": "http://loinc.org",
              "code": "15074-8",
              "display": "Glucose [Moles/volume] in Blood"
            }
          ]
        },
        "subject": {
          "reference": "Patient/2"
        }
      },
      "request": {
        "method": "POST",
        "url": "Observation"
      }
    }
  ]
}
```

**Search for Patient (Use the IDs autogenerated by FWoA)**
`{{API_URL}}/Observation?subject=Patient/7b21ab46-30d7-4eac-9913-5a0db078f78f,Patient/2c83ce16-de84-4be7-9091-e1dd1aa08298`


I'll continue to look into this further.

**Comment by nguyen102** [comment]
Hi,

Supporting `OR` in search parameters is something that we haven't fully supported yet. It's currently in our backlog, and we will update this ticket once it's been implemented.

In this case, searching on `name` happens to work because our current ES search queries tokenize `smith,james` as `[smith,james]` and does a full text search for any of the tokens. However, for non text fields like `subject` we perform exact string matching. `subject` is an object with the `reference` field.

**Comment by rsmayda** [comment]
We now support OR searching, please upgrade `search` to >3.2.0: https://github.com/awslabs/fhir-works-on-aws-search-es/blob/mainline/CHANGELOG.md#320-2021-07-28
