### ISSUE TITLE
VALIDATOR_LAMBDA_ALIAS is not set properly causing serverless offline to fail

### ISSUE THREAD

**Issue by ericfuxealth** [awslabs/fhir-works-on-aws-deployment#342]
**Describe the bug**

VALIDATOR_LAMBDA_ALIAS is not set properly, causing serverless offline to fail validation.

The error is: 

`Unhandled Error ValidationException: 1 validation error detected: Value '[object Object]' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:(aws[a-zA-Z-]*)?:lambda:)?([a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?`

**To Reproduce**
1. Check out mainline
2. Deploy to AWS and debug locally with serverless offline.
3. Create a patient, e.g. 
```
curl -v -X POST -d @patient.json -H "x-api-key: <apikey" -H "Accept: application/json" -H "Content-Type: application/json" http://localhost:3000/Patient | jq
```
4. Call failed with exception
```
`Unhandled Error ValidationException: 1 validation error detected: Value '[object Object]' at 'functionName' failed to satisfy constraint: Member must satisfy regular expression pattern: (arn:(aws[a-zA-Z-]*)?:lambda:)?([a-z]{2}((-gov)|(-iso(b?)))?-[a-z]+-\d{1}:)?(\d{12}:)?(function:)?([a-zA-Z0-9-_\.]+)(:(\$LATEST|[a-zA-Z0-9-_]+))?`
```

**Expected behavior**
The patient is created.

**Screenshots**
N/A

**Versions (please complete the following information):**
2.8.0

**Additional context**
This can be fixed by modifying the following line in the config: 
Change https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/src/config.ts#L38 to 
` if (!IS_OFFLINE && process.env.VALIDATOR_LAMBDA_ALIAS) { `

**Comment by nguyen102** [comment]
Thanks for the filing this Bug request Eric. I've started a PR to fix this issue [here](https://github.com/awslabs/fhir-works-on-aws-deployment/pull/343)

**Comment by nguyen102** [comment]
PR has been merged to fix this issue. Closing ticket.
https://github.com/awslabs/fhir-works-on-aws-deployment/pull/343
