### ISSUE TITLE
[package.json] Undefined variables npm_package_samtemplate, npm_package_cftemplate, and npm_package_stackname

### ISSUE THREAD

**Issue by ilyash-b** [awslabs/fhir-works-on-aws-deployment#357]
While investigating how to deploy FHIR Works using CodePipeline, I came across this:

https://github.com/awslabs/fhir-works-on-aws-deployment/blob/c4441a6b8afdfd1d000a2641db3d3e585d9cdca5/package.json#L28-L30

The variables npm_package_samtemplate, npm_package_cftemplate, and npm_package_stackname don't appear anywhere else. Is it some leftover code from previous deployment mechanism?

**Comment by SanketD92** [comment]
@ilyash-b You're right. Currently the `launch` command (which relies on these variables ultimately) is not being used.

**Comment by ilyash-b** [comment]
Then "todo" here is to remove these commands? ... together with `launch`?

**Comment by rsmayda** [comment]
Removed!
