### ISSUE TITLE
[Misc] Deploying using CodePipeline

### ISSUE THREAD

**Issue by ilyash-b** [awslabs/fhir-works-on-aws-deployment#358]
**What's on your mind?**

I am figuring out how to deploy FHIR Works using CodePipeline. Main steps would be:

* Build step, where Serverless generates CloudFormation template.
* Deploy step, where CloudFormation template from previous step is used to deploy the application

Does that sound OK?

**Versions (please complete the following information):**
 - `mainline` branch

**Comment by ilyash-b** [comment]
Encountered a problem.

The operation of `sls` and `sam` differs: `sam` application uploads the artifacts to S3 during build/package file. `sls` doesn't, it uploads the artifacts during `deploy`. This breaks the usual build/deploy separation in CodePipeline which works with CloudFormation.

Edit 1:

As of now, we will probably follow documentation of `serverless deploy`

> Use this in your CI/CD systems, as it is the safest method of deployment.

Source: https://www.serverless.com/framework/docs/providers/aws/guide/deploying/

Edit 2:

Also https://www.serverless.com/blog/cicd-for-serverless-part-2 - place `serverless deploy` in `buildspec.yml`

**Comment by Zambonilli** [comment]
We've done something similar internally and focused on deploy only. We leveraged the scripts/install.sh script which sets enough context for initial deploy and subsequent deploys via `serverless deploy`.

Long term, we were looking at building and open sourcing codepipeline and codebuild jobs for:
1. CI/CD in dev of everything
2. deploying code changes only
3. deploying infrastructure only
4. deploying configuration only

Might even make sense to leverage AWS proton for the above separation of concerns for deployment. Does this line up with what you're trying to do?

**Comment by ilyash-b** [comment]
@Zambonilli, we are small team and currently only focused on number one above.

I was hoping that the deployment will be more aligned with what we do for SAM applications. Apparently it's not straightforward for the reason I mentioned above - "package" doesn't upload the artifacts to S3, "deploy" does both upload and CloudFormation update. Looks like we will be using CodeBuild for `sls deploy` which is annoying, mildly phrased.

I was looking into AWS Proton and I have the impression that it might make sense for us later.

What would make even more sense - if project like FHIR Works would come with CloudFormation for CodePipeline.

Edit: ... and would use SAM, &*^%*&^, not Serverless

**Comment by ilyash-b** [comment]
Related: https://github.com/awslabs/fhir-works-on-aws-deployment/issues/357 - [package.json] Undefined variables npm_package_samtemplate, npm_package_cftemplate, and npm_package_stackname

**Comment by ilyash-b** [comment]
Related: https://github.com/awslabs/fhir-works-on-aws-deployment/issues/359 - [Misc] Why Serverless and not SAM?

**Comment by SanketD92** [comment]
@ilyash-b, I want to understand your use-case correctly. Do you mean you would like FHIR Works to leverage CFN that helps you perform CI/CD using CodePipeline and SAM?

**Comment by ilyash-b** [comment]
@SanketD92 , separate issues:

We would like to have CI/CD using CodePipeline - that's correct.

CodePipeline has [integrations with different AWS services](https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference.html). One of them is [CloudFormation deployment](https://docs.aws.amazon.com/codepipeline/latest/userguide/action-reference-CloudFormation.html). It works well with SAM applications and I imagine with plain CloudFormation too. It doesn't work with Serverless the same way. The reason is the difference in how `package` command works (emphasis mine):

* [Plain CloudFormation](https://docs.aws.amazon.com/cli/latest/reference/cloudformation/package.html) - "... **uploads** local artifacts, such as source code for an AWS Lambda function or a Swagger file for an AWS API Gateway REST API, to an S3 bucket."
* [SAM](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-package.html) - "This command creates a .zip file of your code and dependencies, and **uploads** the file to Amazon Simple Storage Service (Amazon S3)"
* [Serverless](https://www.serverless.com/framework/docs/providers/aws/cli-reference/package/) - "... packages your entire infrastructure into the .serverless directory ..." - **does not upload artifacts to s3**

With Serverless, even though it does produce CloudFormation template during `package`, there is no straightforward way of utilizing CloudFormation integration in CodePipeline - the referenced artifacts are not in S3.

For Serverless:

> Use this in your CI/CD systems, as it is the safest method of deployment.

Where "this" refers to running `serverless deploy` command.

Source: https://www.serverless.com/framework/docs/providers/aws/guide/deploying/

Which in my mind translates into using CodeBuild for deploying. Which doesn't fit well in my head -- "build" for "deploying"...

**Comment by SanketD92** [comment]
@ilyash-b, thanks for responding back.

CodeBuild allows flexibility such that it could be used for actions like build, deploy, as well as triggering tests. It all depends on how you structure your `buildspec.yml` file.

For linking your code to CodePipeline, you can link your Source stage to your `<repository>/<branch>` (GitHub/CodeCommit etc.)

As for storing artifacts in an S3 bucket, you can store them once while creating the pipeline. These artifacts could hold your user-config settings, if needed, which can be downloaded by buildspec commands.

Let us know if this makes sense.

**Comment by ilyash-b** [comment]
Hello @SanketD92!

It sounds like we are talking about different things.

> CodeBuild allows flexibility such that it could be used for actions like build, deploy, as well as triggering tests. It all depends on how you structure your buildspec.yml file.

We are aware of this.

> As for storing artifacts in an S3 bucket, you can store them once while creating the pipeline.

I was talking about artifacts which are result of `serverless package`. These are per build.


Let's summarize my struggle again:

SAM - CodeBuild is used to build the app and upload the artifacts to S3; in a separate step, CodePipeline deploys the app using CloudFormation integration. **Fits neatly into CodePipeline features**.

Serverless - CodeBuild is used to both build and deploy which sounds less "the right thing to do". The step of uploading artifacts to S3 looks inseparable from the deploy step. That's why CloudFormation integration in CodePipeline can not be utilized. **Does not fit neatly into CodePipeline features**.

**Comment by Zambonilli** [comment]
Yeah, serverless is nice as long as you commit to its model and unfortunately its model doesn't lend itself well to playing with others since it's all or nothing. You're spot on that the best you're probably going to get here is a codepipeline that runs codebuilds to run serverless commands. There's a level of separation with serverless package vs serverless deploy/deploy function but all of that is most easily driven from codebuild buildspecs.
