### ISSUE TITLE
[Misc] Why Serverless and not SAM?

### ISSUE THREAD

**Issue by ilyash-b** [awslabs/fhir-works-on-aws-deployment#359]
What's the reason that FHIR Works uses Serverless and not AWS SAM?

**Comment by SanketD92** [comment]
Hello @ilyash-b, and thank you for the question. There's no strong reason on why we chose Serverless over AWS SAM other than the fact that we were more experienced with the former and AWS SAM at the time of FWoA inception was lacking key development features. Now though the gaps have been closed.

If you've used AWS SAM in any of your other projects, could you provide some details as to how that fared for you?

**Comment by ilyash-b** [comment]
We have some experience with AWS SAM. It works fine for us except for some corner cases.

> AWS SAM at the time of FWoA inception was lacking key development features. Now though the gaps have been closed

Is switching to AWS SAM on the table?

Serverless is not as straightforward to use with CodePipeline - https://github.com/awslabs/fhir-works-on-aws-deployment/issues/358#issuecomment-865882581

Edit: which features specifically were missing?

**Comment by SanketD92** [comment]
Hi @ilyash-b, thanks for responding back.

What we meant by "lacking key features" was that at the time of implementing this product, AWS SAM was was in its beta phase and therefore not as mature as Serverless.

We have not planned to add support for AWS SAM as of now. We can prioritize it in upcoming sprints once we evaluate the volume of similar feature requests.

**Comment by ilyash-b** [comment]
Hi @SanketD92!

No promises, I need to think a bit more and check with the team here but ...

What if we made a pull request to change from Serverless to AWS SAM? (Supporting both sounds like more complicated maintenance).

**Comment by rsmayda** [comment]
> What if we made a pull request to change from Serverless to AWS SAM? 

We would love to support this! Some criteria:
- Not backwards breaking 
- Easily do local development (equivalent to `sls offline`)

Before starting this change please look into using CDK too: https://aws.amazon.com/blogs/compute/better-together-aws-sam-and-aws-cdk/. Also, just an FYI, with a change like this it maybe a bit drawn out due to testing on our side

**Comment by rsmayda** [comment]
@ilyash-b If you end up wanting to make a PR moving to SAM/CDK please open a new feature request and we can track the progress there :)
