### ISSUE TITLE
Trying to set up environment per "Development.MD"

### ISSUE THREAD

**Issue by robertlario** [awslabs/fhir-works-on-aws-deployment#360]
I am using MS Visual Studio Code on a windows box with powershell.

The DEVELOPMENT.MD file states 

"Then you can run this command in the `deployment` package directory to spin up your local environment:

`AWS_ACCESS_KEY_ID=<Access-Key> AWS_SECRET_ACCESS_KEY=<Secret-Key> OFFLINE_BINARY_BUCKET=<FHIRBinaryBucket> OFFLINE_ELASTICSEARCH_DOMAIN_ENDPOINT=<ElasticSearchDomainEndpoint> serverless offline start`
"

I understand that I need to "plugin" my own values for Access-Key, Secrect-key, etc.  But how do I "spin up" my local environment.  The archetype above is not a command that I understand.

How do I "Spin up" the server?

Thanks for the help.

**Comment by SanketD92** [comment]
@robertlario, thanks for your question.

For plugging in your values, you'd need to set them in Windows environment variables and verify that Powershell recognizes them to be set.

Once you run the `serverless offline start` command, an output containing the API Key (defined as "Key with token") will be generated. You will need to use this (for the header `x-api-key`) along with the API URL (localhost:3000) to make FHIR API requests during local testing.

Hope this helps.

**Comment by robertlario** [comment]
Thanks!

________________________________
