### ISSUE TITLE
Debugging in MS Visual Studio Code

### ISSUE THREAD

**Issue by robertlario** [awslabs/fhir-works-on-aws-deployment#361]
Is it possible to set breakpoints and debug the code while running "serverless offline start"? What is the recommend method for debugging FHIR Works lambda's?  Putting console.log's thought out the code to locate a bug is real old school debugging I'd like to avoid.

**Comment by Zambonilli** [comment]
I'm assuming you mean debug the entire FHIR works and not just the unit tests for a module. The latter is a pretty straight forward solution where you create a .vscode/launch.json and the program is jest.

For debugging the entire FHIR works locally, you'll need to follow the local development setup documentation first. From there, you can add a .vscode/launch.json to the deployment package. From there, one of the configurations was to set the program to serverless with params `offline`, `start`, `-s`, `dev`. iirc, I was then able to debug routes although some of the TS -> js mappings didn't line up all the time but I think that was not a FHIR Works problem but a common TS problem.

I have it on my list to create PRs for all the launch.json for each module. I just need to tidy up some things 1st.

Here's the .vscode/launch.json for deployment I use for debugging the entire thing:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Attach by Process ID",
            "processId": "${command:PickProcess}",
            "request": "attach",
            "skipFiles": [
                "<node_internals>/**"
            ],
            "type": "pwa-node",
            "outFiles": ["${workspaceFolder}/lib/**/*.js"]
        },
        {
            "type": "pwa-node",
            "request": "launch",
            "name": "Debug",
            "program": "${workspaceRoot}/node_modules/serverless/bin/serverless",
            "args": [
                "offline",
                "start",
                "-s",
                "dev"
            ],
            "internalConsoleOptions": "openOnSessionStart",
            "outFiles": ["${workspaceFolder}/.webpack/**/*.js"],
            "sourceMaps": true,
            "env":{
                "SLS_DEBUG":"*",
                "ARCHIVE_CONFIG":"AuditEvent,60|Patient,120",
                "AWS_PROFILE":"$YOUR_AWS_PROFILE_HERE",
                "OFFLINE_BINARY_BUCKET":"$YOUR_AWS_BINARY_BUCKET_HERE",
                "OFFLINE_ELASTICSEARCH_DOMAIN_ENDPOINT":"$YOUR_AWS_ES_DOMAIN_HERE"
            },
            "runtimeArgs": [
                "--preserve-symlinks-main",
                "--preserve-symlinks"
            ],
            "autoAttachChildProcesses": true,
            "stopOnEntry": true
        },
        {
            "type": "pwa-node",
            "request": "launch",
            "name": "Debug Tests",
            "program": "${workspaceRoot}/node_modules/jest/bin/jest.js",
            "args": [
                "-i",
                "--testPathPattern=src/*|ddbToFirehoseLambda"
            ],
            "internalConsoleOptions": "openOnSessionStart",
            "env": {
                "ARCHIVE_DELIVERY_STREAM_NAME": "test-stream-name"
            }
        }
    ]
}
```

**Comment by robertlario** [comment]
Thanks Mike.

I created a directory called FHIRWORKS.  I placed the fhir-works-on-asw-* packages from githib into this directory.  I followed the readme.md and install.md directions and successfully deployed to AWS.  I configure postman accordingly and was able to put, get, etc.

I followed Development.MD and was able to use postman to connect to http://localhost:3000 successfully.

To setup for debugging:
1) I created a directory .vscode and placed the file launch.json in it.
2) I took the json definition provided and placed it in this file. I updated the env variables accordingly.
3) I open fhir-works-on-aws-deployment\src\index.ts and place a break point on line 18 ("return serverlessHandler(event,contect):").
4) selected "Run > Start Debugging"

visual studio provides a drop down to select an environment.  None of them related to Serverless.

Thoughts?





________________________________

**Comment by Zambonilli** [comment]
Your Run and Debug dropdown in vscode should have a `Debug` option. Select that and run, it should start and break on serverless.js becaues of the stopOnEntry being set to true.

**Comment by robertlario** [comment]
I do not have a "Run and Debug" menu item at the top level.  I do have "Run > Start Debugging".  It as if the IDE does not see "AWS FHIR Works 210622\fhir-works-on-aws-deployment\.vscode\launch.json"
[cid:a69b115c-674d-4943-b1b4-425acbe411b9]

[cid:e7633e5f-9fe2-40e7-bb4b-9ac0f6edef49]
________________________________

**Comment by robertlario** [comment]
So I moved the launch.json up "AWS FHIR Works 210622\.vscode\launch.json" and "Run > Start Debugging".  The debugger starts and appears to continue to run.  Using postman I attempted "Get Patient Search".  

I got : 

GET http://localhost:3000/Patient
Error: connect ECONNREFUSED 127.0.0.1:3000

Do I continue to use the same value I have been using for "x-api-key"?

**Comment by Zambonilli** [comment]
serverless command outputs the x-api-key to standard out and it should come through the debug window in vs code. Looks like your server isn't running though judging by the error above.

**Comment by robertlario** [comment]
Just to be clear, the .viscose/launch.json goes under the fhir-works-on-aws-development directory. Yes?

r/ Robert

On Jun 24, 2021, at 5:45 PM, Mike Lohmeier ***@***.***> wrote:

﻿

serverless command outputs the x-api-key to standard out and it should come through the debug window in vs code. Looks like your server isn't running though judging by the error above.

**Comment by Zambonilli** [comment]
yep, .vscode/launch.json in fhir-works-on-aws-development

**Comment by robertlario** [comment]
I’ve followed the readme, install and development docs.  I have gotten to the point where I can use postman with the FHIR Local environment to call the local instance of serverless to update and search DynamoDB and ElasticSearch running on AWS.

I would like to step through the lambda  code locally in visual studio code using the debugger.

I created the “launch.json” file as you suggested in “C:\AWS FHIR Works 210622\fhir-works-on-aws-deployment\.vscode”

The debugger will not start.  It appears that the IDE does not “see” the launch.json file.

Is there perhaps some other environmental variable, property, or setting that I am missing?  Something that tells the IDE to look in in “C:\AWS FHIR Works 210622\fhir-works-on-aws-deployment” for the launch file?  Presently, it appears the IDE is looking in “C:\AWS FHIR Works 210622”

I started visual studio code in “C:\AWS FHIR Works 210622”

All of the fhir-works-on-aws-* folders from github are all in this directory (“C:\AWS FHIR Works 210622”)

Thanks for your help

**Comment by Zambonilli** [comment]
Are you creating a ".vscode" directory under fhir-works-on-aws-deployment? Your absolute path to the launch.json should be "C:\AWS FHIR Works 210622\fhir-works-on-aws-deployment\.vscode\launch.json"

**Comment by robertlario** [comment]
yes with a slight clarification on your last message.  My absolute path is "C:\AWS FHIR Works 210622\fhir-works-on-aws-deployment\.vscode\launch.json"

Note the "\" added between "deployment\.vscode".

**Comment by robertlario** [comment]
interesting.  This systems removed the back slash I added between deployment and .vscode

I am assuming it did the same to your reply. :-)

**Comment by Zambonilli** [comment]
oh weird, yeah. Can you try just clicking the play button on the left hand menu options in vscode. From there you should be able to create or update the launch.json.

**Comment by robertlario** [comment]
I've tried this.  When I select the play button I am presented with three options "Run and Debug", "JavaScript Debug Terminal", and "Debug URL".  I've tried all three.  When I select "Run and Debug", I am presented with option to select an environment. 

The options presented are : "AWS SAM: Debug Lambda Function Locally", "Chrome", "Chrome (legacy)", "Docker: Debug in Container", "Edge: Launch", "Java", Node.js", "Node.js (legcy)", "install extension....".

None of these appear to be appropriate for debugging serverless.

Are you open to communicating directly?  Perhaps a webinar?

**Comment by Zambonilli** [comment]
What you are describing is the default "Run and Debug" pane. If you click the "create a launch.json file" under "Run and Debug" and select nodejs you can copy & paste the launch.json file into the resulting launch.json file that vs code created for you. vs code is not finding your .vscode/launch.json otherwise this screen wouldn't have the default pane contents.

**Comment by robertlario** [comment]
Yes, I believe I understand this.  If I create a new launch.json file in this manner, it places the file at C:\AWS FHIR Works 210622\.vscode" not under fhir-works.on-aws-development.  

So I should create a launch.json file under "C:\AWS FHIR Works 210622\.vscode" and place the configuration previously provided into this instance?

**Comment by Zambonilli** [comment]
Are you opening vs code in the fhir-works-on-aws-deployment directory or your root directory?

**Comment by robertlario** [comment]
At the root (C:\AWS FHIR Works 210622.vscode).  Should I be opening VSCODE at fhir-works-on-aws-deployment (the subdirectory of the project (C:\AWS FHIR Works 210622.vscode)

**Comment by Zambonilli** [comment]
yes

**Comment by robertlario** [comment]
1) Should this launch.json initiate the spin up of serverless?
or
2) Should I start serverless and attach to the process?

Because when I start the debugger VSCODE does see the configuration launch.json, but it does not appear to start serverless. After starting the debugger, VSCODE asks me to attached to existing processes, none of which is serverless.

**Comment by Zambonilli** [comment]
If you used the launch.json from above then there should be a `Debug` option in the drop down list. This will run serverless offline command and attach your debugger on start.

**Comment by robertlario** [comment]
I'm sure I am missing something, but please know I was very diligent to follow your directions.  

I started the debugger.

"Attach by Process ID" is one of the configurations, which i select.

VSCODE spins for a few seconds, then presents me with a list of processes to attached to.

serverless is not one of them.  

It does not appear that serverless is being spun up.

Besides configuring the launch file, is there something else I should have done?

Other than updating the key's, I copied and pasted the configuration directly from this thread.

IMO, this configuration does not appear (from myside) to initiate the spinning up serverless.

Might you take a peek at the configuration  provided?

**Comment by robertlario** [comment]
I was selecting the wrong configuration.

On to the next challenge.  

Thanks for your time!
