### ISSUE TITLE
[Misc] Kibana log-in issue

### ISSUE THREAD

**Issue by MacL3an** [awslabs/fhir-works-on-aws-deployment#362]
**What's on your mind?**
I set up FHIR Works yesterday using CloudFormation and was curious to peek into the ElasticSearch to see what data was there.
I created a new User in the Kibana pool in Cognito and then tried hitting the ElasticSearchDomainKibanaEndpoint endpoint. It asks to log in after which it asks me to change my password for the user, so it seems to find the user, but then I’m hit with the following not very informative message. Any advice on how to resolve this? 
![image](https://user-images.githubusercontent.com/2429736/123100923-d2345e00-d433-11eb-82f1-263b49bb62ab.png)

**Versions (please complete the following information):**
Version 2.1.3
Release date: 05/2021

**Comment by SanketD92** [comment]
Hi @MacL3an, thanks for opening this issue.

Did you confirm the email address for this user prior to logging in?

Could you check if there is an error message on your browser's network/console tabs (under developer tools)?
This could help us getting started with initial troubleshooting. 

Thanks!

**Comment by Zambonilli** [comment]
I was able to reproduce when not setting an email address when creating the kibana cognito pool user. There were no error messages in the console or returned by cognito in the network requests. Setting an `@example.com` email address in the cognito create user screen is a work around here.

Steps to Reproduce:
1. Navigate to fhir-service-$stage-Kibana user pool in Cognito's console
2. Navigate to Create User under Users and Groups
3. Create a new user
4. Uncheck "Mark email as Verified" and do not enter an email
5. Click create user
6. Navigate to Kibana login screen
7. login with username and password for new user
8. enter new password, confirm password and email
9. click sign in
10. assert error screen with no feedback

**Comment by MacL3an** [comment]
I can also confirm that it worked once I created a new user with an email address. Thanks for the help!

**Comment by rsmayda** [comment]
Added some comments in the INSTALL.md file calling this out

**Comment by MacL3an** [comment]
I used the PDF guide I found [here](https://docs.aws.amazon.com/solutions/latest/fhir-works-on-aws/fhir-works-on-aws.pdf) and dit not even know about this repo. The readme in this repo seems more up to date. Perhaps you should remove the pdf and only point to here?
