### ISSUE TITLE
Publish a Capability Statement, per version

### ISSUE THREAD

**Issue by rsmayda** [awslabs/fhir-works-on-aws-deployment#368]
I foresee many of these "Does AWS FHIR Works support <x>?" questions. In anticipation, would you consider?

- good: Publishing a static CapabilityStatement with your release note [^1]
- better: Running a live reference implementation, so folks can hit the `metadata` and `.well-known/smart-configuration` endpoints themselves
  * Optional: Add yourself to the HL7 Confluence of test/reference servers, [Public Test Servers](https://confluence.hl7.org/display/FHIR/Public+Test+Servers) and/or [Test Servers](https://confluence.hl7.org/display/FHIR/Test+Servers) 
  * Optional: Publishing your reference server conformance with AEGIS Touchstone

[^1] It's awesome you added the Postman collection, but this requires running the application locally.
> To know what all this FHIR API supports please use the GET Metadata postman to generate a Capability Statement.
> https://github.com/awslabs/fhir-works-on-aws-deployment/blob/72f4fa23feb68456a924a013dd064beaf75f1b41/README.md#using-postman-to-make-api-requests

_Originally posted by @rmharrison in https://github.com/awslabs/fhir-works-on-aws-deployment/issues/212#issuecomment-780961278_

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
