### ISSUE TITLE
fhir-works-on-aws-deployment 3.0 & older version fhir-works-on-aws-routing 5.4.1 

### ISSUE THREAD

**Issue by robertlario** [awslabs/fhir-works-on-aws-deployment#371]
Should fhir-works-on-aws-deployment 3.0 be referencing fhir-works-on-aws-routing 5.4.1 or 5.4.2?

It appears fhir-works-on-aws-deployment 3.0 is a version behind on fhir-works-on-aws-routing.  This is by design?

**Comment by rsmayda** [comment]
This occasionally happens, particularly when the sub-packages changes are not "urgent/critical".

We generally advise customers to take the latest version of each package. I will open a PR now remedying this Router version

**Comment by robertlario** [comment]
ok. Thanks.  It was just creating confusion for me when I was debugging the code.  I pulled down source for fhir-works-on-aws-routing 5.4.2, which of course does not line up with what the debugger was showing.
