### ISSUE TITLE
Resources will not validate if json schema has "ID" defined.

### ISSUE THREAD

**Issue by robertlario** [awslabs/fhir-works-on-aws-deployment#377]
Resources will not validate if the json schema has an "id" defined.

Taken from fhir.schema.json https://hl7.org/FHIR/fhir.schema.json.zip
{
  "$schema": "http://json-schema.org/draft-06/schema#",
  "id": "http://hl7.org/fhir/json-schema/4.0",
  "description": "see http://hl7.org/fhir/json.html#schema for information about the FHIR Json Schemas",
  "discriminator": { ......

The issues : 
if the id is present in the json schema file,   the line "JsonSchemaValidator: ajv.addSchema(ppmn_schema_v1_0_json_1.default);" uses the id as the "key" for looking up the schema when future validation occurs.  If no id is present in the schema, ajv uses "" as the key for future looks ups.

the line "JsonSchemaValidator:const referenceName = `#/definitions/${definitionName}`;" results  in the key being "" for looking up the schema during validation, but since the ID was previously available at initialization, the key to the correct schema is "http://hl7.org/fhir/json-schema/4.0".  So at validation no schema is found.

potential solutions:

In the JsonSchemaValidator prepend the schema id value ("http://hl7.org/fhir/json-schema/4.0") to

line :
const referenceName = `#/definitions/${definitionName}`;

becomes something like (note that a bit more work is required ie. not hard coding the id)  Also, not sure if '#' between the id and the url is still needed:

const schemID= "http://hl7.org/fhir/json-schema/4.0";
const referenceName = `${schemID}/definitions/${definitionName}`;

or strip the ID before
ajv.addSchema(ppmn_schema_v1_0_json_1.default);

or provide guidance to remove the id filed from the json field altogether (seems like least best solution).

**Comment by Bingjiling** [comment]
Hi @robertlario, thanks for reaching out! Could you please share the request data that you used that caused this error? We can try to reproduce it from our side with it.

**Comment by robertlario** [comment]
Morning,

I did provide the URL to the schema used.  It is https://hl7.org/FHIR/fhir.schema.json.zip.

Robert

**Comment by Bingjiling** [comment]
Hi Robert, 

Could you please share the exact request data that you used to recreate this error? Something like 

POST patient with: 

```
{
  "resourceType": "Patient",
  "text": {
    "status": "generated",
    "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><p></p></div>"
  },
  "active": true,
  "name": [
    {
      "family": "Smith",
      "given": ["John"]
    }
  ],
  "gender": "male",
  "birthDate": "1996-09-24",
  "managingOrganization": {
    "reference": "Organization/2.16.840.1.113883.19.5",
    "display": "Good Health Clinic"
  }
}
```

Then get patient with the id returned will result in error message: `Some random error message`. With this information we can reproduce the error on our side and find the root cause. 

Thanks,
Yanyu

**Comment by jn1119** [comment]
Pushed the fix in [PR 102](https://github.com/awslabs/fhir-works-on-aws-routing/pull/102)
