### ISSUE TITLE
[Misc] Does FHIR Works write the entire FHIR resource into ElasticSearch?

### ISSUE THREAD

**Issue by sb-wnyffenegger** [awslabs/fhir-works-on-aws-deployment#383]
**What's on your mind?**

I am reading the documentation concerning DynamoDB Streams and am a little confused with what is being streamed from DynamoDB to the intermediate Lambda and then to ElasticSearch.

When a FHIR resource is modified in DynamoDB does the resultant event in the DynamoDB stream (and hence sent to ElasticSearch) contain the entire FHIR resource?

**Comment by rsmayda** [comment]
Yes the entire FHIR resource is sent to Elastic Search
