### ISSUE TITLE
Install.sh Info_Output.yml is not a valid YAML

### ISSUE THREAD

**Issue by organom** [awslabs/fhir-works-on-aws-deployment#386]
The install.sh directs the output to a file called Info_Output.yml in 
https://github.com/awslabs/fhir-works-on-aws-deployment/blob/7cf96cbca41efce6b9f93ddf05673390966d09ce/scripts/install.sh#L305

Late it also executes `parse_yaml` in
https://github.com/awslabs/fhir-works-on-aws-deployment/blob/7cf96cbca41efce6b9f93ddf05673390966d09ce/scripts/install.sh#L310

By seeing the official documentation at https://www.serverless.com/framework/docs/providers/aws/cli-reference/info/ , its obvious that it doesn't output valid YAML format, since it has the headers `Service Information` and `Stack Outputs`. 

Please don't have a .yml extension in a file that is not valid YAML OR make sure to write a proper YAML file (by removing the non-yaml components of the output).

**Comment by ilyash-b** [comment]
> eval $( parse_yaml Info_Output.yml )

`parse_yaml` is then misnamed because it parses invalid yaml

**Comment by SanketD92** [comment]
A fix has been merged for this bug.
