### ISSUE TITLE
[Feature Request] Support [system] | [code] Search

### ISSUE THREAD

**Issue by sdhakal-xealth** [awslabs/fhir-works-on-aws-deployment#388]
**Is your feature request related to a problem? Please describe.**

Example: I want to search for any condition with a code "ha125" in the code system "http://acme.org/conditions/codes" using ` GET [base]/Condition?code=http://acme.org/conditions/codes|ha125`. 

**Describe the solution you'd like**
Support [system] | [code] search. 

**Describe alternatives you've considered**
Iterate all the condition resources and filter.

**Additional context**
As per the spec, https://www.hl7.org/fhir/search.html#token, [system] | [code] is a valid search param. 
Related to  https://github.com/awslabs/fhir-works-on-aws-deployment/issues/380

**Comment by carvantes** [comment]
Hi,

The support for token type search parameters was added on v2.3.0(https://github.com/awslabs/fhir-works-on-aws-search-es/blob/mainline/CHANGELOG.md#230-2021-04-09)

`GET [base]/Condition?code=http://acme.org/conditions/codes|ha125` is a valid search query. The only caveat is that the `|` MUST be url encoded. e.g. `GET [base]/Condition?code=http://acme.org/conditions/codes%7Cha125` (most http libraries will URL encode by default)

**Comment by carvantes** [comment]
I just verified that a query like the following orks fine using the latest version of this package:
```
{{API_URL}}/Condition?code=http://snomed.info/sct%7C386661006
```

Please upgrade to the latest version and do URL encoding for search queries.

I'm closing this issue now, but feel free to re-open if the above does not work for you.
