### ISSUE TITLE
[Bug] Getting error while running docker install command for fhir-works-on-aws-deployment with latest awscli in local laptop

### ISSUE THREAD

**Issue by masterelaya** [awslabs/fhir-works-on-aws-deployment#401]
Issue : 

I am getting below error after running this command by installing latest aws cli in my local laptop -> docker build -t fhir-server-install -f docker/Dockerfile . Please help to resolve with updated command line.

#6 35.41   Could not find a version that satisfies the requirement boto3 (from versions: )
#6 35.42 No matching distribution found for boto3
------
executor failed running [/bin/sh -c apt-get update && apt-get install -yq python3-pip less && pip3 install boto3 && curl -fsSL --compressed  "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o /tmp/awscliv2.zip && unzip -q /tmp/awscliv2.zip -d /tmp && /tmp/aws/install && npm install serverless -g]: exit code: 1

**Comment by Bingjiling** [comment]
Hi @masterelaya thanks for reaching out! Could you please share the print out of `aws --version` in your local laptop? Also, just so I understand it correctly, you've successfully installed FWoA through Docker before, and after a recent aws cli upgrade, the `docker build -t fhir-server-install -f docker/Dockerfile .` command is throwing error?
