### ISSUE TITLE
[Misc] Different implementations/versions between two deployment methods?

### ISSUE THREAD

**Issue by shengc5** [awslabs/fhir-works-on-aws-deployment#408]
The actual FHIR implementations seem to be different if someone deploys FWoA through the Cloudformation script and through cloning the repo from `mainline` and then deploying it through serverless.

For instance:

> 1. different capability statements(even though both state FHIR version 4.0.1)
> 2. the serverless version does not appear to support `Patient.name.given` or `Patient.name.family`, while the Cloudformation version supports them

Is this expected? If so would be nice to note that somewhere (apologies if already done & I just missed it)

**Comment by Bingjiling** [comment]
Hi Lucas, 

Thanks for reaching out! 

Yes, the CloudFormation install(AWS Solutions) is an older version compared to the GitHub install. It's been on our radar to bring the CloudFormation install up to date, however, we weren't able to get to it yet. I'll update the README file to reflect this difference so it does not bring more confusion. 

Thanks,
Yanyu

**Comment by shengc5** [comment]
Thanks for the response. Could you elaborate on what the actual implementation differences are? I see both indicate FHIR version 4.0.1. Also, according to the cloudformation file, the standard version is based off of `fhir-works-on-aws/v2.1.3`, but I'm not seeing v2.1.3 in the changelog.

**Comment by Bingjiling** [comment]
The Solutions deployment versions have diverged from the GitHub versions since the initial launch of Solutions actually. It was originally based out of GitHub v2.1.1 at initial launch, and we added some patches to the Solutions version afterwards which resulted in v2.1.2 and v2.1.3. And these two versions do not exist for the GitHub repository. 

We're keeping a copy of the codes deployed in Solutions in [this branch](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/aws-solution/CHANGELOG.md). I'll update the doc to have a link to this branch as well.

**Comment by shengc5** [comment]
Got it. Thanks for the clarification.

To a question I had earlier, are search interfaces implemented correctly in both, given they both show FHIR 4.0.1? 
According to the [FHIR docs](http://www.hl7.org/fhir/patient.html), Patient.name.given and Patient.name.family should be supported, but the serverless version is giving me a `Invalid search parameter 'name.given' for resource type Patient` error.

**Comment by Bingjiling** [comment]
Yes, the AWS Solutions version do not support standard FHIR search parameters. The AWS Solutions version v2.1.3 is a functional equivalent of GitHub v2.1.1, and standard FHIR search parameters and a few other search functionalities were released in GitHub [v2.6.0](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/CHANGELOG.md#260---2021-04-09) and up. 

For a complete list of features in GitHub but not in Solutions, you can reference the [CHANGELOG](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/CHANGELOG.md) for all features added in v2.2.0 and up.
