### ISSUE TITLE
[Feature Request] Make config.ts async to allow for things like kms decrypt calls for ENV variables

### ISSUE THREAD

**Issue by medhost-jshaver** [awslabs/fhir-works-on-aws-deployment#432]
**Is your feature request related to a problem? Please describe.**
Currently cannot make async calls from config.ts. I would like to pass kms encrypted ENV variables for the client_id/secret attributes of introspectionOptions and be able to call kms.decrypt() within config.ts/authZConfig.ts (for smart).

**Describe the solution you'd like**
I would be nice to have config.ts and authZConfig.ts (for smart) handle async methods.

**Describe alternatives you've considered**
We could make the kms decrypt call from the authz-smart package right before using the client_id/secret values for basic credentials, but this would be called for every request and seems like unnecessary overhead.

**Comment by rsmayda** [comment]
Hey Josh,

Lets set up some time to discuss more!

**Comment by carvantes** [comment]
This was added on https://github.com/awslabs/fhir-works-on-aws-deployment/pull/464
