### ISSUE TITLE
[Bug] group export performance

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-deployment#439]
**Describe the bug**
The performance of the group export has degraded as our dataset has grown.  We currently have ~8.7 million items with a size of ~ 10 gigabytes.  The glue job of a group export for a single patient ran for 17+ hours before being manually stopped (it did not complete normally).

As discussed I created a new patient without any referenced resources and did not see an improvement.

**To Reproduce**
1. Load a 'large' dataset into ddb
2. Create a group with a Patient member 
3. Initiate a group export

**Expected behavior**
The export to complete in a 'reasonable' time frame

**Screenshots**

**Versions (please complete the following information):**
2.2.0-SMART

**Additional context**
The same export request previously completed in about 1 minute with a small dataset

**Comment by rsmayda** [comment]
@medhost-bfindeisen -- What is your DynamoDB `Capacity mode`? You can find this in the console and clicking on the DynamoDB Table -- it should be `On-demand` or `Provisioned`

**Comment by ghost** [comment]
> @medhost-bfindeisen -- What is your DynamoDB `Capacity mode`? You can find this in the console and clicking on the DynamoDB Table -- it should be `On-demand` or `Provisioned`

@rsmayda -- our Capacity mode is set to `On-demand`

**Comment by SanketD92** [comment]
A note for those visiting this issue - the team is currently co-ordinating with Medhost and working towards a fix.

**Comment by Bingjiling** [comment]
Update: This issue was resolved and right now the export time is approximately 30mins. And we'll have a team discussion on if we can prioritize the request to make bulk export more time and resource efficient.
