### ISSUE TITLE
[Bug] Content-Type is not 'application/fhir+ndjson' when retrieving bulk export files

### ISSUE THREAD

**Issue by ghost** [awslabs/fhir-works-on-aws-deployment#442]
**Describe the bug**
The response Content-Type is 'binary/octet-stream' but Inferno tests require 'application/fhir+ndjson'

**To Reproduce**
1. Perform a group export
2. retrieve the ndjson files
3. Observe the response headers

**Expected behavior**
content-type is application/fhir+ndjson

**Screenshots**
![image](https://user-images.githubusercontent.com/69013924/133509305-bd0c5209-92ad-4e82-a489-6ba0e0fbe796.png)

**Versions (please complete the following information):**
2.2.0-SMART

**Additional context**
https://hl7.org/fhir/uv/bulkdata/export/index.html

![image](https://user-images.githubusercontent.com/69013924/133510045-60dae4e0-eebe-4363-8372-00c5be1b0bd0.png)

**Comment by rsmayda** [comment]
Working on this now!

**Comment by rsmayda** [comment]
Persistence update is in v3.8.1 - please update when you get the chance 👍 

https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/tree/v3.8.1
