### ISSUE TITLE
[Feature Request] Chained parameters search

### ISSUE THREAD

**Issue by lindenquan** [awslabs/fhir-works-on-aws-deployment#444]
**Is your feature request related to a problem? Please describe.**
I need to find Resources based on a value of referenced parameter. 
For example:   GET [base]/DiagnosticReport?subject:Patient.name=peter

**Describe the solution you'd like**
FHIR has a search spec about [Chained Parameters](https://www.hl7.org/fhir/search.html#chaining)

**Describe alternatives you've considered**
I have to search for Patient resource first, and then search for DiagnosticReport recourses.

**Comment by SanketD92** [comment]
Thank you for creating this feature request, we've added this to our team's backlog.

Related to another [issue](https://github.com/awslabs/fhir-works-on-aws-search-es/issues/104).

**Comment by lquanx** [comment]
Thanks

**Comment by Bingjiling** [comment]
Thanks for reaching out! Chained parameter search has been implemented in the search package(PR: https://github.com/awslabs/fhir-works-on-aws-search-es/pull/129), the feature is now available in mainline.
