### ISSUE TITLE
[Misc] How to POST custom Resources ?

### ISSUE THREAD

**Issue by lquanx** [awslabs/fhir-works-on-aws-deployment#445]
**What's on your mind?**
I would like to post a custom Resource.  But I got below error:
```
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>
<body>
	<pre>Cannot POST /CustomResource</pre>
</body>
</html>
```

**Versions (please complete the following information):**
 - v2.2.0-smart

**Comment by Zambonilli** [comment]
Have you implemented a custom [DomainResource](http://www.hl7.org/fhir/domainresource.html) in your own [ImplementationGuide](http://hl7.org/fhir/r4/implementationguide.html) and followed the steps for [Using Implementation Guides](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/USING_IMPLEMENTATION_GUIDES.md)?

I'd be curious if this works in fwoa because I've only ever done Profiles with constraints and extensions.

**Comment by lquanx** [comment]
Thanks very much. I will try that out

**Comment by lquanx** [comment]
I have implemented a custom DomainResource in your own ImplementationGuide and followed the steps for Using Implementation Guides.

But, I still get the same error. And There is no information about my custom resource in the "CapabilityStatement" Resource

**Comment by Zambonilli** [comment]
hmm, that is unfortunate. I haven't dived into the Implementation Guide code yet so I can't help much more until I do. I was hoping it would just work but with the breadth of change an Implementation Guides can bring, it's not surprising.

**Comment by rsmayda** [comment]
@Lin-002 could you share your DomainResource? We could take a look and try to replicate/figure out what the issue is

**Comment by carvantes** [comment]
Hi @Lin-002 , 

At this moment we don't support adding custom resources via Implementation Guides. Sorry for the confusion, perhaps we can make this clearer on our documentation. @ssvegaraju , please see if you can update the docs.

We support IGs that do profiling(constraints/extensions) on the base FHIR resource types.

Adding a custom resource may need some code changes. Adding it to the array of `baseResources` would be a start: https://github.com/awslabs/fhir-works-on-aws-deployment/blob/e43a6a7eea15ae63e8ab321f33b45c64a4aaf7cf/src/config.ts#L33
But we haven't tried adding custom resources before so I'm not sure about all the code modifications needed to make it work

**Comment by lquanx** [comment]
Thanks everyone.
