### ISSUE TITLE
[Feature Request] SNS Topic Actions for Cloudwatch Alarms

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#446]
**Is your feature request related to a problem? Please describe.**
When trying to attach custom subscriptions to cloudwatch Alarms in fwoa, you have to add the SNS topic ARN to the OkActions and AlarmActions properties of the cloudwatch alarm. Unfortunately, the PutMetricAlarm method requires that you echo the Alarm fields besides OkActions and AlarmActions. In our case, we used bash to attach an SNS topic with our PagerDuty subscriber to all of the cloudwatch alarms. The bash script got a bit gnarly and it'd be cleaner if out of the box fwoa provided an SNS topic that all Cloudwatch Alarms already have OkActions and AlarmActions set.

Here's the snippet of our bash script in our codebuild buildspec for attaching the SNS topic.
```
     # make sure our cloudwatch alerts have our sns pager duty Action
      - |
        if [ "${PAGER_DUTY_ENABLED}" == "true" ]; then
          echo "starting to add SNS topic actions to cloudwatch alarms"
          # aws cloudwatch put-metric-alarm requires you to echo everything...
          # probably should have just added the SNS topic, policies and actions in cloudformation upstream
          # then just create a pagerduty subscriber...
          aws cloudwatch describe-alarms --output json | jq -c '.MetricAlarms[]' |
          while read -r ALARM; do    
              # prune nonskeleton fields
              ALARM=$(echo $ALARM | jq -c 'del(.AlarmArn)')
              ALARM=$(echo $ALARM | jq -c 'del(.AlarmConfigurationUpdatedTimestamp)')
              ALARM=$(echo $ALARM | jq -c 'del(.StateValue)')
              ALARM=$(echo $ALARM | jq -c 'del(.StateReason)')
              ALARM=$(echo $ALARM | jq -c 'del(.StateReasonData)')
              ALARM=$(echo $ALARM | jq -c 'del(.StateUpdatedTimestamp)')
              DIMENSIONS_LENGTH=$(echo $ALARM | jq '.Dimensions | length')
              METRICS_LENGTH=$(echo $ALARM | jq '.Metrics | length')
              if [ $DIMENSIONS_LENGTH -eq 0 ] && [ $METRICS_LENGTH -gt 0 ];
              then
                ALARM=$(echo $ALARM | jq 'del(.Dimensions)')
              fi
              
              echo $ALARM | jq -c '.AlarmName'
              aws cloudwatch put-metric-alarm \
                  --actions-enabled \
                  --ok-actions "arn:aws:sns:${REGION}:${ACCOUNT_ID}:${CLOUDWATCH_SNS_TOPIC_NAME}" \
                  --alarm-actions "arn:aws:sns:${REGION}:${ACCOUNT_ID}:${CLOUDWATCH_SNS_TOPIC_NAME}" \
                  --cli-input-json "$ALARM"
          done
          echo "finished adding SNS topic actions to cloudwatch alarms"
        fi
```

**Describe the solution you'd like**
fwoa provided an SNS topic that all Cloudwatch Alarms already have OkActions and AlarmActions set.

**Describe alternatives you've considered**
The alternative here is API calls to PutMetricAlarm after `serverless deploy` is ran.

**Additional context**
I can do the Cloudformation updates to provide the SNS Topic, SNS Topic Policy for cloudwatch service to be able to publish to the SNS Topic and the updates to the Cloudwatch Alarms.

**Comment by SanketD92** [comment]
Thank you for creating this feature request, we've added this to our team's backlog.

**Comment by Zambonilli** [comment]
Thanks @SanketD92. I've got a PR ready and waiting with the cloudformation changes whenever this gets prioritized in your backlog.

**Comment by Zambonilli** [comment]
Closing because https://github.com/awslabs/fhir-works-on-aws-deployment/pull/447 merged.
