### ISSUE TITLE
[Feature Request] Ability to set id values on POST

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#461]
**Is your feature request related to a problem? Please describe.**
When POSTing a resource if you set the id field to a valid GUID the passed in id value is ignored and a new id is generated. This is problematic when trying to migrate existing data that already has it's own GUID id value and it's hard to change due to emails and bookmarks in the field with the existing id values used.

Looks like we can add logic before this line in the persistence-ddb to check if the incoming resource object already has an id and use that vs creating.
https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/mainline/src/dataServices/dynamoDbDataService.ts#L113

**Describe the solution you'd like**
A valid GUID used in a POST body's id field is used as opposed to a new GUID being generated.

**Describe alternatives you've considered**
Looked at if we can migrate data directly to Dynamodb but would prefer to go through the API to pickup all the metadata and validation.

**Additional context**
I can prepare a PR here if this makes sense as a feature.

**Comment by AllanHodkinson** [comment]
Hi Mike,
You can create new resources with a known id by using a PUT request as per https://www.hl7.org/fhir/http.html#upsert

This is disabled by default. but you can enable it by setting `updateCreateSupported` = true when the persistence component is created.  It's this line of code you need to change: 
https://github.com/awslabs/fhir-works-on-aws-deployment/blob/4e0b5ed2df673c636293264ebbafff5df6ce9ee6/src/config.ts#L35

**Comment by Zambonilli** [comment]
Fantastic, thank you. I'll close this issue out.

**Comment by Zambonilli** [comment]
To help anyone that stumbles upon this later. If you're doing a migration of records to fwoa and your dataset's unique IDs are not already GUIDs you can use a named UUID to deterministically has your id to a useable ID value. This helps keep your migration tooling a bit more lightweight than having to manage xref tables.

https://uuid.ramsey.dev/en/stable/rfc4122/version5.html
