### ISSUE TITLE
[Bug] Resource type not respected when doing a GET call with :id 

### ISSUE THREAD

**Issue by umair719** [awslabs/fhir-works-on-aws-deployment#468]
**Describe the bug**
When doing a `GET` call with` :id `using the Patient endpoint, but of a Practitioner resource, a valid Practitioner record is returned.

**To Reproduce**
1. Use Postman to do a GET call on a Patient Resrouce
2. In the path variables section, pass in a valid Practitioner ID
3. Response will return the Practitioner resource

**Expected behavior**
API response should return something like the following: 
`"diagnostics": "Resource with ID 3 exists but it is not of type Patient, found resource of type Practitioner"`

**Screenshots**
<img width="944" alt="postman_2021-09-29_15-50-28" src="https://user-images.githubusercontent.com/2522678/135529450-0fbaf9ec-c547-47f5-a82e-451ed571bee6.png">

**Versions (please complete the following information):**
```
"name": "fhir-works-on-aws-deployment"
"version": "2.1.1"
```

**Additional context**

**Comment by rsmayda** [comment]
Thanks for opening this up, I will be working on this now

**Comment by rsmayda** [comment]
This is no longer reproducible. The persistence version you are using is [V2.0.1](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/v2.1.1/package.json#L36) (based on the given deployment version), which does not have this [commit](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/commit/4f433d2eacdd81c25bdc6e5a2d5e9ea755a33204#diff-f639334981c2ebd30e571f0856dbb1b7c294497ff3467dbd981b8bf700e5544f) with the fix. Please update to the latest deployment   package [v4.0.0](https://github.com/awslabs/fhir-works-on-aws-deployment/tree/v4.0.0) or at the very least update your persistence package to [v3.2.1](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/releases/tag/v3.2.1)
