### ISSUE TITLE
[Misc] SMART on FHIR Authorization Server Setup

### ISSUE THREAD

**Issue by Sami-M** [awslabs/fhir-works-on-aws-deployment#469]
I've launched the FHIR Works on AWS but I'm having trouble with failing Inferno tests regarding Oauth (specifically tests SLS-97 and SLS-08). I think this means I launched my stack with the wrong issuerEndpoint, oAuth2ApiEndpoint, and or patientPickerEndpoint. I generated these endpoints by following the [Okta SMART on FHIR Setup Guide](https://github.com/oktadev/okta-smartfhir-docs/blob/main/SETUP.md), but I'm still not sure I'm using the correct values when launching my FHIR Works stack via the scripts/install.sh script. I tried comparing my values to the ones in this repo's Actions, but it looks like the url's are masked so I can't compare to see if I'm using the correct values.

My values look like the following:
- issuerEndpoint: https://dev-########.okta.com/oauth2/########
- oAuth2ApiEndpoint: https://dev-########.okta.com/oauth2/########/v1
- patientPickerEndpoint:  https://########.execute-api.us-east-1.amazonaws.com/sandbox

Please let me know if the above seem incorrect. Thanks.

 - Release Version installed: v2.2.0-smart

**Comment by rsmayda** [comment]
Hey @Sami-M Which inferno tests are you using? ONC PROGRAM EDITION or COMMUNITY EDITION? https://inferno.healthit.gov/

Looking at your values those do look to be correct syntax.

**Comment by Sami-M** [comment]
Thanks for verifying for me. I used the community edition tests here: https://inferno.healthit.gov/community/ and selected US Core v3.1.1. I'll run through the Okta setup guide again and try to troubleshoot.

**Comment by rsmayda** [comment]
A good milestone to aim for is to see if you can login. A easy way that I test is use Postman. To use our Postman setup check out our [README](https://github.com/awslabs/fhir-works-on-aws-deployment/tree/smart-mainline#using-postman-to-make-api-requests)

![image](https://user-images.githubusercontent.com/5750407/136203056-eb0227b4-7c06-4795-983b-c208db842e78.png)
