### ISSUE TITLE
Error: spawn yarn ENOENT

### ISSUE THREAD

**Issue by idm0404u** [awslabs/fhir-works-on-aws-deployment#472]
while Running this command : serverless deploy --aws-profile <AWS PROFILE> --stage <STAGE> --region <AWS_REGION>

I am getting this error.

Error: spawn yarn ENOENT
      at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
      at onErrorNT (internal/child_process.js:467:16)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

**Comment by nguyen102** [comment]
The command that you used is missing a parameter. It should be 
`serverless deploy --aws-profile <PROFILE_NAME> --stage <STAGE> --region <AWS_REGION>`

For example
`serverless deploy --aws-profile default --stage dev --region us-east-1`

**Comment by idm0404u** [comment]
@nguyen102 I have used parameter in that command:

serverless deploy --aws-profile sohel-serverless-cv-two --stage dev --region ap-south-1

then only I got the error.

**Comment by rsmayda** [comment]
@idm0404u Did you run `yarn install` prior to using `serverless`? 

It looks like the plugins may not have been installed: https://github.com/serverless/serverless/issues/3247

**Comment by idm0404u** [comment]
@rsmayda yes I have run yarn install prior to serverless, 
and the yarn is also installed, still getting the error.

**Comment by rsmayda** [comment]
@idm0404u When you run `serverless info` what are your environment information?

This is what mine looks like:
```
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.17.6
     Framework Version:         2.29.0 (local)
     Plugin Version:            4.5.0
     SDK Version:               n/a
     Components Version:        3.7.2
```

**Comment by rsmayda** [comment]
@idm0404u Could you also try to delete your `node_modules` directory and reinstalling the packages, then run `serverless` again

**Comment by idm0404u** [comment]
@rsmayda  
These are the environment information when I run the serverless info

 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.4.0
     Framework Version:         2.29.0 (standalone)
     Plugin Version:            4.5.0
     SDK Version:               n/a
     Components Version:        3.7.2

**Comment by idm0404u** [comment]
@rsmayda  I have deleted node_modules and reinstalled again, still facing the same issue.

**Comment by Bingjiling** [comment]
Hi @idm0404u, 

Thanks for your interest in FWoA!

I'm wondering if you've successfully deployed FWoA before and ran into this issue when updating the stack? Or this is the first time you deploy FWoA in this environment? If it's the first time you deploy it, I would recommend following the instruction [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/INSTALL.md#linux-or-macos-installation) for Mac and Linux install and use the install script instead of running serverless directly. If you're updating an existing stack, do you mind sharing what's changed between the last successful deployment and now? 

If you still get errors during the install, I would recommend using the [docker install](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/INSTALL.md#docker-installation) approach. This way we can eliminate differences in the environment and reproduce the issues you face if any. 

Thanks,
Yanyu

**Comment by idm0404u** [comment]
Hi @Bingjiling,

I have followed the instruction for Linux (ubantu), I have used the install script before running serverless.
 while deploying  :
 serverless deploy --aws-profile sohel-serverless-cv-two --stage dev --region ap-south-1

I am getting this error

Error: spawn yarn ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
at onErrorNT (internal/child_process.js:467:16)
at processTicksAndRejections (internal/process/task_queues.js:82:21)

I have tested the API in POSTMAN, APIs are working fine. but only when I deploy I am facing this above mentioned issue.

I have tried the docker install approach but I am still facing the same issue.

Thanks

**Comment by Bingjiling** [comment]
Hi @idm0404u,

Thanks for the additional details. Could you please share the detailed commands and logs for the Docker install? We can try reproducing the issue on our side with these information.

Thanks

**Comment by idm0404u** [comment]
Hi @Bingjiling , 
I have used the following commands
1. aws configure
2. docker build -t fhir-server-install -f docker/Dockerfile .
3.docker run -v ~/.aws/credentials:/home/node/.aws/credentials:ro -it -l install-container fhir-server-install
4. docker run -it -l install-container fhir-server-install --region ap-south-1 --stage dev

These are the environment variable :
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.4.0
     Framework Version:         2.62.0 (standalone)
     Plugin Version:            5.4.6
     SDK Version:               4.3.0
     Components Version:        3.17.1

**Comment by jn1119** [comment]
Hi @idm0404u, I tried the docker approach using Ubuntu and wasn't able to reproduce the issue. I used `Ubuntu Server 20.04 LTS (HVM)` when bringing up my EC2 instance and used the following commands from tutorial when downloading [Docker](https://docs.docker.com/engine/install/ubuntu/) on ubuntu. I ended up using the latest version `5:20.10.10~3-0~ubuntu-focal`. Once I was done setting up Docker, I set up my aws credentials and followed the above commands you listed. Did you verify if your aws credentials are setup correctly using awscli? I did have to install awscli separately on my EC2 instance.

I think it would be helpful if you list the steps in details or probably follow the above approach by bringing up an EC2 instance from AWS console.

Also, can you provide some surrounding logs that help us in understanding where the install is failing. For instance, did it get to the stack creation phase or failed way before that?

**Comment by carvantes** [comment]
Hi,

`Error: spawn yarn ENOENT` can only mean that `yarn` is not installed or that it somehow cannot be found by the nodejs process(i.e. cannot be found in `$PATH`).

Unfortunately we haven't been abbe to reproduce the issue on our side.

We recommend that you double check that yarn is installed correctly. You can uninstall and then reinstall yarn to be safe:
```
npm uninstall --global yarn
npm install --global yarn
```
Also, if you installed `yarn` via other means(homebrew, .msi installer, etc.) we recommend that you unisntall that `yarn` version and reinstall using `npm`.

https://classic.yarnpkg.com/en/docs/install
