### ISSUE TITLE
[Feature Request] lambda graviton2 support

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#476]
**Is your feature request related to a problem? Please describe.**
Lambda team released new support for running lambdas with an ARM architecture. The big win here is an estimated cost savings of ~34%. With fwoa lambdas being nodejs, this should be a relatively easy win.

**Describe the solution you'd like**
Update the lambda functions to by default run with `arm64` architecture.

**Describe alternatives you've considered**
run with `x86_64` and pay 34% more.

**Additional context**
https://aws.amazon.com/about-aws/whats-new/2021/09/better-price-performance-aws-lambda-functions-aws-graviton2-processor/
https://www.serverless.com/framework/docs/providers/aws/guide/functions#instruction-set-architecture

**Comment by rsmayda** [comment]
Great callout -- we will need to do some regression testing to ensure performance is comparable to existing solution. We will add this to our backlog for now

**Comment by Zambonilli** [comment]
I will add that we did switch our internal CodeBuild job that runs scripts/install.sh over to the new graviton2 small instance a couple of weeks ago when graviton2 small was added to CodeBuild. There has been no difference in the results of `yarn run release`'s `tsc`, `eslint` or `jest` runs.

**Comment by Zambonilli** [comment]
good call on doing some performance tests. Some generic workload performance tests on non-provisioned lambdas are  showing mixed results.

https://dev.to/aws-builders/aws-lambda-graviton2-cheap-and-slow-51ld

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
