### ISSUE TITLE
[Feature Request] API Gateway Content Encoding Enabled

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#477]
**Is your feature request related to a problem? Please describe.**
API Gateway supports various compression types for response payloads as part of the request pipeline. Currently, the fwoa $stage-fhir-service API Gateway has not configured the Content Encoding to be enabled. The problem enabling Content Encoding solves is API responsiveness and throughput because it trades CPU time for network time via sending less bytes over the wire.

**Describe the solution you'd like**
Update our serverless.yaml file to support API Gateway content-encoding.

**Describe alternatives you've considered**
I considered doing the content encoding in nodejs itself via an expressjs module. However, compression is CPU intensive so it smells like it'd be better off done outside of nodejs since CPU bound work without workers in nodejs has overhead with the event loop.

**Additional context**
Found 2 serverless plugins that support setting the API Gateway Content Encoding feature. I believe the 1st one is better supported but at one point had a "Too Many Requests" error when deploying that caused the second.
https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-gzip-compression-decompression.html
https://www.serverless.com/plugins/serverless-content-encoding/
https://www.npmjs.com/package/serverless-api-compression

**Comment by Bingjiling** [comment]
Hi @Zambonilli , thanks for reaching out! A ticket has been created in our backlog for this feature.

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
