### ISSUE TITLE
Machine to Machine Authentification 

### ISSUE THREAD

**Issue by aakashkag** [awslabs/fhir-works-on-aws-deployment#495]
**What's on your mind?**
How to enable machine to machine authentication. Basically Another api will call to fhir server. My another api only accept client id and client secrate Which we can use to get token from  Cognito. 
 How we can enable by default to generate client secret during deployment of fhir on aws.  also I don't want to enable api key. 
 

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3]

**Comment by maghirardelli** [comment]
Hello @aakashkag,

Thanks for your inquiry! We are looking into it and will get back to you with more information.

Thanks, Marianna

**Comment by jn1119** [comment]
Hi @aakashkag, Can you add more details on what you are trying to achieve here? If your intention is to call FHIR APIs from your own API - you should be able to use a Cognito token belonging to the configured user pool which was used to bring up FHIR server. It is completely up to you if you want to use the same user pool for your own APIs too. 

If you don't want to enable api keys, you would need to remove `private` parameter for all the paths:
1. [path '/'](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/serverless.yaml#L95)
2. [path 'proxy'](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/serverless.yaml#L101)

Let me know if you have any follow up questions. Thanks

**Comment by aakashkag** [comment]
@jn1119 
I am exposing FHIR to Commonwell. Commonwell only take fhir server url, client id, client secret and Oauth url. 
In my case , Commonwell only can only generate token using Client Credential Oauth flow right?

In Project read me it is mentioned that "To access the API, you must use the ID token. This ID token must include scopes of either openid, profile or aws.cognito.signin.user.admin."
We need to provide Scope from those three option. But in case of Client Credential oauth flow we need to generate custome scope. 
I am bit confused how to make it work using Client id and client screat given that commonwell only support that option.

**Comment by rsmayda** [comment]
So in general you would want to use our [`smart` branch](https://github.com/awslabs/fhir-works-on-aws-deployment/tree/smart-mainline) which is where we have SMART on FHIR support.

For Client Credential OAuth flow you would AuthN with your idP and should have get an access_token with the required FHIR claims. Then with that access_token you can all us (the FHIR endpoint)

**Comment by carvantes** [comment]
Hi, Hopefully the smart branch was useful for your use case. I'm closing this issue now, but feel free to reopen if you have further questions
