### ISSUE TITLE
Suggestion for elasticsearch elimination 

### ISSUE THREAD

**Issue by aakashkag** [awslabs/fhir-works-on-aws-deployment#499]
We are planning to completly shutdown elasticsearch from AWS FHIR stack. Is there any perfornmance issue or any major issue we are going to face if we do so. Our goal to use FHIR for documenr query and patient query. Can we eliminate elasticsearch from solution?

Thank you

**Comment by jn1119** [comment]
Hi @aakashkag Just out of curiosity- can you elaborate more on your use case, and why you want to remove elastic search component?

If you remove Elastic Search(ES), you won’t be able to perform any [search](https://www.hl7.org/fhir/http.html) operations. You would be able to perform other simple lookups though. To remove ES, you will need to remove the DynamoDB stream that writes back to ES. And ensure that [typeSearch](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/src/config.ts#L107) is `stubs.search` instead of `esSearch`. Further, you can add your own search capability by implementing the search interface [here](https://github.com/awslabs/fhir-works-on-aws-interface/blob/mainline/src/search.ts).

Let me know if you have any follow up questions I can help with. Thanks.

**Comment by aakashkag** [comment]
Hi @jn1119 Thanks for reply. 
We don't need full text search. becuase we  are exposing FHIR to xyz service which is only going to  consume document reference api by providing patient id. 

In such use cases i don't see point to having ElasticSearch becuase it cost alot as compare to other resource and ES is not much usefull in our case. 

Could you plese point out how to remove the DynamoDB stream that writes back to ES ? 

Also I am bit curious to know if there is any limitation on fields which we can use to get resource. 

Example:
When i use /DocumentReference?identifier=valuehere, I get document reference 
But when i use  /DocumentReference?patient.identifier= Valuehere, I get empty document reference. 

 I am not sure if "patient.identifier" is supported as parameters or not. Is there any list or swagger documentation to check possible parameters. 
 
Thank you

**Comment by carvantes** [comment]
Hi,

Removing elasticsearch may not be a suitable solution for you. Without it, the entire [Search API](https://www.hl7.org/fhir/search.html) won't work.
` /DocumentReference?identifier=valuehere` and ` /DocumentReference?patient.identifier= Valuehere` are both search queries that run on elasticsearch.

Without elasticsearch you can only use the [read, create, update, create, transaction, and capabilities APIs](https://www.hl7.org/fhir/http.html) e.g. you can only read records like `/DocumentReference/doc-ref-id-111`

---

> I am not sure if "patient.identifier" is supported as parameters or not. Is there any list or swagger documentation to check possible parameters.

`patient.identifier` is a "chained parameter" and it is not supported right now, but we are working on it. See: https://github.com/awslabs/fhir-works-on-aws-deployment/issues/505 for the latest updates.

You can find the possible parameters on the FHIR documentation e.g. https://www.hl7.org/fhir/patient.html#search. 
The supported search features are documented on https://github.com/awslabs/fhir-works-on-aws-search-es#fhir-search-features-supported

**Comment by carvantes** [comment]
If you still want to remove Elasticsearch after the above considerations, these are the changes that you need to make:

Remove the following:
- The `ddbToEs` lambda: https://github.com/awslabs/fhir-works-on-aws-deployment/blob/2bf9edc69a40e81b1716764d83c221881c0d48a0/serverless.yaml#L116
- All the search resources. You can simply delete the `elasticsearch.yaml` import: https://github.com/awslabs/fhir-works-on-aws-deployment/blob/2bf9edc69a40e81b1716764d83c221881c0d48a0/serverless.yaml#L841
- https://github.com/awslabs/fhir-works-on-aws-deployment/blob/2bf9edc69a40e81b1716764d83c221881c0d48a0/serverless.yaml#L181
- All the references to `elasticsearch.yaml`. e.g (there are more): https://github.com/awslabs/fhir-works-on-aws-deployment/blob/2bf9edc69a40e81b1716764d83c221881c0d48a0/serverless.yaml#L863-L877


Then on `config.ts`, remove `'search-type'` from `operations` and set `typeSearch` to `stubs.search`
https://github.com/awslabs/fhir-works-on-aws-deployment/blob/2bf9edc69a40e81b1716764d83c221881c0d48a0/src/config.ts#L110-L114


Removing Elasticsearch is not a setup that we officially support, so the manual changes are a bit involved. The above changes are expected to work, but they haven't been officially tested and a few additional changes may be required.
