### ISSUE TITLE
Chained parameter search patient.identifier not working

### ISSUE THREAD

**Issue by aakashkag** [awslabs/fhir-works-on-aws-deployment#505]
In document reference patient.identifier search not working. 
For example: {{API_URL}}/DocumentReference?patient.identifier=1.3.6.1.4.1.19376.1.2.3%7C123456789
returning empty result

 ```
{
    "resourceType": "Bundle",
    "id": "37e3ffe6-8d98-4c07-85c8-1732df8cb8c4",
    "meta": {
        "lastUpdated": "2021-11-01T15:42:29.413Z"
    },
    "type": "searchset",
    "total": 0,
    "link": [
        {
            "relation": "self",
            "url": "{{API_URL}}/DocumentReference?patient.identifier=1.3.6.1.4.1.19376.1.2.3%7C123456789"
        }
    ],
    "entry": []
}

```
This is valid search : https://www.hl7.org/fhir/search.html#token

I deployed FHIR Using cloudformation: https://docs.aws.amazon.com/solutions/latest/fhir-works-on-aws/automated-deployment.html

**Comment by carvantes** [comment]
Hi, 
`{{API_URL}}/DocumentReference?patient.identifier=111` is known as "chained parameters" (https://www.hl7.org/fhir/search.html#chaining)

At this moment we do not support chained parameters. However, we are currently working on it and it will be released soon. 

The PR with the implementation is https://github.com/awslabs/fhir-works-on-aws-search-es/pull/129. We'll update here once we release the feature, stay tuned!

**Comment by carvantes** [comment]
Also, for future reference, the supported search features can be found here: https://github.com/awslabs/fhir-works-on-aws-search-es#fhir-search-features-supported

**Comment by carvantes** [comment]
Hi, 

We released the chained search parameters feature as part of `fhir-works-on-aws-search-es@3.8.0`

You can upgrade the search package version or pull the latest changes for ` fhir-works-on-aws-deployment`(we already bumped the search package version in there)

Please try it out and let us know if you have any feedback
