### ISSUE TITLE
An error occurred: GlueJobSecurityConfig - export-security-config already exists in stack

### ISSUE THREAD

**Issue by sohel-khan** [awslabs/fhir-works-on-aws-deployment#512]
I have successfully installed the solution first time on the **qa** stage and it is working fine, But when I'm trying to install on another stage like on **dev** stage that time I am facing the below issue. It seems that it is using the previous deployment's stage name i.e  **fhir-service-qa** rather it should be **fhir-service-dev**

```
 Serverless Error ----------------------------------------
 
  An error occurred: GlueJobSecurityConfig - export-security-config already exists in stack arn:aws:cloudformation:ap-south-1:xxxxx:stack/fhir-service-qa/4703dda0-4144-11ec-979d-0257c5b15a04.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          linux
     Node Version:              14.18.1
     Framework Version:         2.64.1 (local)
     Plugin Version:            5.5.0
     SDK Version:               4.3.0
     Components Version:        3.17.1

```

Please have a look into that and give me an appropriate solution... Thanks

**Comment by ssvegaraju** [comment]
Hi, thanks for bringing up this issue! Could I ask what version of the deployment package you are running, and what steps you took to reproduce this error?

**Comment by sohel-khan** [comment]
Hi @ssvegaraju I'm using the latest version and I got this error when I'm trying to deploy on another stage.

**sudo -E ./scripts/install.sh -r ap-south-1 -s qa** 
- Deployed successfully

AND then tried
**sudo -E ./scripts/install.sh -r ap-south-1 -s dev**
 - Deployment Failed

**Comment by ssvegaraju** [comment]
Hi @sohel-khan, just wanted to reach out to let you know that a fix for this issue has just been merged into `mainline`. I'm going to close this issue for now but feel free to reopen if there's anything else!

**Comment by sohel-khan** [comment]
Hi  @ssvegaraju, How I can re-deploy new changes? 
 I have searched the solution for this in the document But I didn't find anything related to it...

**Comment by ssvegaraju** [comment]
after pulling the changes from GitHub, you can employ the same process outlined above to re-deploy with the new changes. (i.e. running `sudo -E ./scripts/install.sh -r <YOUR REGION HERE> -s <YOUR STAGE HERE>`).

**Comment by sohel-khan** [comment]
@ssvegaraju  Okay thanks, will do the same
