### ISSUE TITLE
[Bug][Search] Unable to search for boolean FHIR parameters

### ISSUE THREAD

**Issue by padraignolan** [awslabs/fhir-works-on-aws-deployment#516]
**Describe the bug**
Patient documents that have an active field of type boolean are not searchable.

**To Reproduce**
1. Create a Patient Resource with active set to `true`
https://www.hl7.org/fhir/patient-example.json.html
2. Invoke Search endpoint /Patient?active=true
3. No results are returned 

**Expected behavior**
Active Patients should be returned

**Versions (please complete the following information):**
 4.0.0

**Additional context**
This is the elastic search query generated by the fhirServer. 
`{
    "from": 0,
    "size": 20,
    "track_total_hits": true,
    "body": {
        "query": {
            "bool": {
                "filter": [
                    {
                        "match": {
                            "documentStatus": "AVAILABLE"
                        }
                    },
                    {
                        "match": {
                            "_tenantId": "MA110"
                        }
                    }
                ],
                "must": [
                    {
                        "multi_match": {
                            "fields": [
                                "active.code.keyword",
                                "active.coding.code.keyword",
                                "active.value.keyword",
                                "active.keyword"
                            ],
                            "query": "true",
                            "lenient": true
                        }
                    }
                ]
            }
        }
    },
    "index": "patient-alias-tenant-MA110",
    "preference": "0c89d85e24446b7765cfaa4255dba22d18c35bbf1a5090d937f7c70128ee833f"
}`

**Comment by rsmayda** [comment]
Could you check to see what you patient index is indexing `active` property as? I suspect it is being indexed as a `boolean` and our search isn't taking that into account

To do this log into your AWS Account and go to Opensearch domain, click on your domain then click on indices tab and search for `active`

**Comment by padraignolan** [comment]
Yes it's been indexed as a boolean
![Screenshot 2021-11-18 at 09 15 58](https://user-images.githubusercontent.com/7793238/142386460-4202c9ed-33d5-4f1f-848c-71be59ab40de.png)

**Comment by rsmayda** [comment]
Thanks, for confirming. I will be looking into resolving this

**Comment by Bingjiling** [comment]
Hi @PNolan92 , 

This issue has been fixed in mainline. Thanks for helping us identifying the issue!

Thanks,
Yanyu
