### ISSUE TITLE
GET method for ObservationDefinition with provided custom search parameter fails

### ISSUE THREAD

**Issue by ramunasjurgilas** [awslabs/fhir-works-on-aws-deployment#545]
- A: I have created (example: # 1) search parameter for ObservationDefinition resource.
- B: Then created (example: # 2) ObservationDefinition with extension which contains patient ID.
- C: When searching (example: # 3) for ObservationDefinition with patient ID it fails, that search parameter 'heart-rate-anomaly-range-patient-id' invalid (full error: # 4).

Do I need to do additional steps, that custom search parameter will start working?

I did investigation on how search parameters configuration with other FHIR providers like Google and Firely. Form they side needs to do additional custom steps which AWS FHIR service do not have. 

Version/Tag used: v4.0.0 

### 1. Creating search parameter
```
curl --location --request POST 'https://my.execute-api.eu-central-1.amazonaws.com/dev/tenant/tenant1/SearchParameter' \
--header 'Content-Type: application/json' \
--header 'x-api-key: U5fMfQbb2H7Ju7zmDXiWHak1CmbGobVF6185ach2' \
--header 'Authorization: Bearer XXX' \
--data-raw '{
  "resourceType": "SearchParameter",
  "id": "heart-rate-anomaly-range-patient-id",
  "url": "http://hl7.org/fhir/SearchParameter/heart-rate-anomaly-range-patient-id",
  "base": ["ObservationDefinition"],
  "code": "heart-rate-anomaly-range-patient-id",
  "name": "Search for heart rate anomaly range in ObservationDefinition resource with patient-id",
  "type": "string",
  "expression": "ObservationDefinition.extension('\''http://hl7.org/fhir/StructureDefinition/heart-rate-anomaly-range-patient-id'\'').value.as(String)",
  "status": "active",
  "description": "Search by Patient ID"
}'
```

### 2. Creating ObservationDefinition
```
curl --location --request POST 'https://my.execute-api.eu-central-1.amazonaws.com/dev/tenant/tenant1/ObservationDefinition' \
--header 'Content-Type: application/json' \
--header 'x-api-key: U5fMfQbb2H7Ju7zmDXiWHak1CmbGobVF6185ach2' \
--header 'Authorization: Bearer XXX' \
--data-raw '{
   "quantitativeDetails":{
      "decimalPrecision":0,
      "unit":{
         "coding":[
            {
               "display":"BPM",
               "system":"http://unitsofmeasure.org",
               "code":"BPM"
            }
         ]
      }
   },
   "preferredReportName":"Heart rate anomaly range",
   "multipleResultsAllowed":false,
   "code":{
      "coding":[
         {
            "system":"http://terminology.hl7.org/CodeSystem/observation-category",
            "code":"vital-signs"
         }
      ]
   },
   "identifier":[
      {
         "value":"heart-rate-anomaly",
         "id":"aa"
      }
   ],
   "permittedDataType":[
      "Quantity"
   ],
   "qualifiedInterval":[
      {
         "range":{
            "low":{
               "code":"{beats}/min",
               "system":"http://unitsofmeasure.org",
               "value":45,
               "unit":"heart beats per minute"
            },
            "high":{
               "code":"{beats}/min",
               "system":"http://unitsofmeasure.org",
               "value":126,
               "unit":"heart beats per minute"
            }
         },
         "category":"reference"
      }
   ],
   "extension":[
      {
         "url":"http://hl7.org/fhir/StructureDefinition/heart-rate-anomaly-range-patient-id",
         "valueString":"Patient/d2235f00-4e9c-4b32-9fa7-71480421e31d"
      }
   ],
   "resourceType":"ObservationDefinition"
}'
```

### 3.  Getting ObservationDefinition by providing patient ID
```
curl --location --request GET 'https://my.execute-api.eu-central-1.amazonaws.com/dev/tenant/tenant1/ObservationDefinition?heart-rate-anomaly-range-patient-id=Patient/d2235f00-4e9c-4b32-9fa7-71480421e31d' \
--header 'Content-Type: application/json' \
--header 'x-api-key: U5fMfQbb2H7Ju7zmDXiWHak1CmbGobVF6185ach2' \
--header 'Authorization: Bearer XXX'
```

### 4. Error when getting ObservationDefinition by providing patient ID
```
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">error</td><td>[]</td><td><pre>Invalid search parameter 'heart-rate-anomaly-range-patient-id' for resource type ObservationDefinition</pre></td></tr></table></div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "invalid",
            "diagnostics": "Invalid search parameter 'heart-rate-anomaly-range-patient-id' for resource type ObservationDefinition"
        }
    ]
}
```

**Comment by lwarren01** [comment]
Looking at your SearchParameter specification you have a code value set to `heart-rate-anomaly-range`. That should be the name of the query parameter you provide. You are instead providing `heart-rate-anomaly-range-patient-id`.

**Comment by ramunasjurgilas** [comment]
Thanks for the guidance. Unfortunately after changing code value I still getting same error. Is here still something wrong?

PS: I have updated POST SearchParameter with your suggestion.

As example custom search parameter in the [Google FHIR](https://cloud.google.com/healthcare-api/docs/how-tos/fhir-custom-search) setup must be enabled explicit by executing <API_URL>:configureSearch (on AWS it is not working). I saw similar approaches with other FHIR providers. Maybe in AWS infrastructure needs to be done something similar.

**Comment by Bingjiling** [comment]
Hi @ramunasjurgilas, 

Thanks for reaching out! 

FWoA can not integrate new search parameters that's added through a POST request. To introduce new search parameters, you need to create an IG that includes that parameter, and deploy FWoA with that IG. 

Here's documentation on how to use IG: https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/USING_IMPLEMENTATION_GUIDES.md 

Here's an example of adding a search parameter: https://github.com/awslabs/fhir-works-on-aws-search-es/issues/132#issue-1041215032

Hope this helps. 

Thanks,
Yanyu
