### ISSUE TITLE
[Feature Request] role for performing startRestoreJob backup restores

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#546]
**Is your feature request related to a problem? Please describe.**
Currently, there is no out of the box role for specifying as the role to use in AWS Backup restore process when calling startRestoreJob in fwoa. The existing backup infrastructure sets up only enough for performing the backup jobs themselves and not restoring from the backups.

**Describe the solution you'd like**
An out of the box role for performing restores of the backups when calling startRestoreJob API.

**Describe alternatives you've considered**
Add the `AWSBackupServiceRolePolicyForRestores` AWS managed policy to the `BackupRole` that currently exists that would allow someone to specify this role in startRestoreJob. 

Alternatively, create a dedicated role for restoring backups that has the `AWSBackupServiceRolePolicyForRestores` AWS managed policy attached.

**Additional context**
We're running through our DR plan for when there's DDB corruption and it's a bit painful restoring from AWS Backup. Not sure if these are more a symptom of AWS Backup missing functionality or we can build better tooling in fwoa.

The AWS Backup of DynamoDB tables leaves a lot to be desired. For one, the AWS Backup console does not set the stream to Enabled. This then requires manual reconfiguration of the restored table to add back the ddb stream and trigger for dynamoDDBtoES lambda function. In addition, the KMS encryption key used for the DDB encryption is being specified as the kmsMasterKeyArn when calling startRestoreJob but the restored table is not using the fwoa DDB key for encryption but instead native ddb encryption until you manually set the encryption type. 

We have manual steps in our DR plan to get through but it smells like these steps will get out of date fast and break the infrastructure as code model fwoa uses. We will trying using cloudformation's detect drift and update stack to see if it's better and safer to let cloudformation put the pieces together after a restore of our ddb tables.

**Comment by Bingjiling** [comment]
Hi @Zambonilli, 

Thanks for reaching out! I'll check with my team on this request and get back to you.

Thanks,
Yanyu

**Comment by Bingjiling** [comment]
Hi @Zambonilli - This request has been added to our backlog. Thanks for your input!

**Comment by Zambonilli** [comment]
Much appreciated, thank you

**Comment by carvantes** [comment]
Hi, thanks for submitting the PR https://github.com/awslabs/fhir-works-on-aws-deployment/pull/556. Looks like that PR already solves this issue in full. 
I'm closing this now. Feel free to reopen if needed
