### ISSUE TITLE
[Bug] Unauthorized Error after deploying the solution

### ISSUE THREAD

**Issue by damianesteban** [awslabs/fhir-works-on-aws-deployment#547]
**Describe the bug**

After following instructions and deploying the solution, I am receiving an Unauthorized error when making a request in postman

**To Reproduce**
1. Enter in the env variables in postman
2. Click on the Patient POST Request in the Postman Collection, hit Send
3. The reponse I get is:```{
    "message": "Unauthorized"
} ```

**Expected behavior**

A 200 response.

**Additional context**

The API Gateway Execution Logs:

```
{
    "authorizer.claims.sub": "-",
    "error.message": "Unauthorized",
    "extendedRequestId": "MVULgEY2PHcFlcA=",
    "httpMethod": "POST",
    "identity.sourceIp": "72.229.18.XX",
    "integration.error": "-",
    "integration.integrationStatus": "-",
    "integration.latency": "-",
    "integration.requestId": "-",
    "integration.status": "-",
    "path": "/dev/Patient",
    "requestId": "a4d1086d-937d-4f0e-8ff0-b2ee3b4e8b78",
    "responseLatency": "1",
    "responseLength": "26",
    "stage": "dev",
    "status": "401"
}
```

**Comment by Bingjiling** [comment]
Hi @damianesteban, 

Thanks for reaching out! 

Have you set the `API_KEY` and `COGNITO_TOKEN` value in Postman? If not, you can follow the instructions [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/README.md#using-postman-to-make-api-requests) to set these values. 

If you're still getting errors afterwards, could you please try the `/metadata` endpoint and see what it returns? The metadata endpoint is public, and can help us check if the FHIR server is up and running. 

Thanks,
Yanyu

**Comment by damianesteban** [comment]
I was able to get it working by entering the cognito token in the config for the individual requests. Thank you!
