### ISSUE TITLE
[Bug] Can't Search by Subject for DocumentReference and Media

### ISSUE THREAD

**Issue by Sami-M** [awslabs/fhir-works-on-aws-deployment#560]
I’m having trouble searching for Media and DocumentReference types by subject reference (type Patient) using the API. However, I do see some entries when I search for all DocumentReference and Media types and sort by last updated. For context, I’m using the  v4.0.0 release as of now. Some example queries that always return 0 search results are as follows:

```
curl --location --request GET 'https://<FHIR_URL>/tenant/<TENANT>/DocumentReference?patient=Patient/<PATIENT_ID>’ \
--header 'x-api-key:<KEY>’ \
--header 'Authorization: Bearer <‘AuthToken>’
```
```
curl --location --request GET 'https://<FHIR_URL>/tenant/<TENANT>/DocumentReference?subject=Patient/<PATIENT_ID>' \
--header 'x-api-key: <KEY>' \
--header 'Authorization: Bearer <‘AuthToken>’
```
```
curl --location --request GET '<FHIR_URL>/tenant/<TENANT>/Media?subject=Patient/<PATIENT_ID>' \
--header 'x-api-key: <KEY>' \
--header 'Authorization: Bearer <‘AuthToken>’
```
```
curl --location --request GET '<FHIR_URL>/tenant/<TENANT>/Media?patient=Patient/<PATIENT_ID>' \
--header 'x-api-key: <KEY>' \
--header 'Authorization: Bearer <‘AuthToken>’
```
```
curl --location --request GET '<FHIR_URL>/tenant/<TENANT>/Media?patient=<PATIENT_ID>' \
--header 'x-api-key: <KEY>' \
--header 'Authorization: Bearer <‘AuthToken>’
```

Can anyone confirm that their search for Media and DocumentReference types are working using a `subject` search?

**Comment by Bingjiling** [comment]
Hi @Sami-M ,

Thanks for reaching out! We'll look into this issue.

Thanks,
Yanyu

**Comment by Bingjiling** [comment]
Hi @Sami-M,

I tested the queries in my environment(v4.2.0) and was able to get expected results. Could you please try upgrading to v4.2.0 and see if the issue still persists? 

Thanks,
Yanyu

**Comment by Sami-M** [comment]
Thanks Yanyu. I can close for now and reopen if I'm still having this issue after upgrading.
