### ISSUE TITLE
[Misc][Question] Can FHIR Works be deployed with localstack?

### ISSUE THREAD

**Issue by jmrah** [awslabs/fhir-works-on-aws-deployment#584]
Has anyone on the FWOA team tried deploying the FHIR Works solution with [localstack](https://localstack.cloud/)?  If so, have you been successful in getting it up and running?

**Comment by Bingjiling** [comment]
Hi @jmrah , 

Thanks for reaching out! 

We have not tried localstack before. I did a quick comparison between AWS Services supported by localstack and AWS Services used by FHIR, and the following are not covered by localstack: 

* SNS
* KMS
* DynamoDB
* Step functions

You might be able to use localstack and leveraging actual AWS resources for the services not supported. But you won't be able to rely completely on local resources to deploy FHIR. 

Also, are you looking for a way to deploy and test locally? Have you tried serverless offline mentioned in [this doc](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/e29bcccf1b3a0d528510a76b2ce8fb6a1637f1b6/DEVELOPMENT.md)?

Thanks,
Yanyu

**Comment by jmrah** [comment]
Thanks Bingjiling.

Was your source of unsupported AWS services in localstack from their [feature coverage](https://docs.localstack.cloud/aws/feature-coverage/) page?  Just a FYI for other readers, it does look like those services are supported by localstack's "pro" version.

> Also, are you looking for a way to deploy and test locally? Have you tried serverless offline mentioned in [this doc](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/e29bcccf1b3a0d528510a76b2ce8fb6a1637f1b6/DEVELOPMENT.md)?

Yes, that's right.  I'm glad you brought up the [DEVELOPMENT.md](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/e29bcccf1b3a0d528510a76b2ce8fb6a1637f1b6/DEVELOPMENT.md) guide that you linked to.  I have looked at it, and maybe you can answer I question I had about it.  In the document, it says I can run the following command to spin up my local environment:

`AWS_ACCESS_KEY_ID=<Access-Key> AWS_SECRET_ACCESS_KEY=<Secret-Key> OFFLINE_BINARY_BUCKET=< <FHIRBinaryBucket> OFFLINE_ELASTICSEARCH_DOMAIN_ENDPOINT=<ElasticSearchDomainEndpoint> serverless offline start`

It isn't clear from the documentation what the values for `OFFLINE_*` variables should be.  What should I put in for these values?

**Comment by Bingjiling** [comment]
Thanks @jmrah for the prompt response. 

>Was your source of unsupported AWS services in localstack from their [feature coverage](https://docs.localstack.cloud/aws/feature-coverage/) page?

Yes, I used the feature coverage page as source. 

>It isn't clear from the documentation what the values for OFFLINE_* variables should be. What should I put in for these values? 

Good question! These are values from an existing stack deployed to AWS account, they can be found from the stack output. Example of how they would look like: 

```
OFFLINE_BINARY_BUCKET=fhir-service-dev-fhirbinarybucket-someUniqueString OFFLINE_S3_KMS_KEY=12345678-9123-3456-6789-90123456 OFFLINE_ELASTICSEARCH_DOMAIN_ENDPOINT=https://search-fhir-se-elasti-some-unique-string.us-east-1.es.amazonaws.com
```

**Comment by jmrah** [comment]
>  These are values from an existing stack deployed to AWS account, they can be found from the stack output. Example of how they would look like:

So, the values are _real_ endpoints for an existing deployment of FHIR Works on AWS?  What does the `OFFLINE_` prefix signify then (I just assumed these values were meant to point at a fake/mock/local version of a service because of the `OFFLINE` prefix in the name)?  Does a `serverless offline start` command actually connect to the internet?

**Comment by Bingjiling** [comment]
Yes, you're correct. The values are real endpoints for an existing deployment of FWoA and `serverless offline start` connect to AWS resources through the internet. The command is used for local development after FWoA is successfully deployed to an AWS account, and won't work without an existing deployment.
