### ISSUE TITLE
[Misc] Bundle 25 Entry Limit Workaround

### ISSUE THREAD

**Issue by christopher-watanabe-snkeos** [awslabs/fhir-works-on-aws-deployment#587]
**What's on your mind?**
In our usage of FhirWorks, we need to upload potentially more than 25 Entries in a Bundle. I found this [issue](https://github.com/awslabs/fhir-works-on-aws-deployment/issues/188) from a little over a year ago, but haven't found anything indicating any changes to this limit. 

Is there any plan to increase this limit? And/or any existing workaround that anyone knows of in order to optimally partition a Bundle of >25 Entries into multiple Bundles of an acceptable upload size? 

One could simply partition into as many Bundles of 25 or less entries as possible. That depends however on how the server responds to an incomplete Bundle -- A Bundle with an entry that references Patient A and Organization B, but Organization B is not an entry in the Bundle, for example. If incomplete Bundles throw errors, then one must ensure completeness before uploading, which would complicate the matter further.

Many thanks in advance for any input!

**Versions (please complete the following information):**
 -  fhir-works-on-aws-persistence-ddb v3.9.0

**Comment by Bingjiling** [comment]
Hi @ChristopherWatanabe , 

Thanks for reaching out! 

We have it on our priority list to implement bundle operation in type batch, which would have a higher limit than 25 at the expense of NOT treating it as a transaction. I'm wondering if that would suit your use case? And if yes, what would be an acceptable upload size in your use case?

Thanks,
Yanyu

**Comment by christopher-watanabe-snkeos** [comment]
Hi @Bingjiling, 

Thanks for the reply! Unfortunately our use case is such that we need the all-or-none behavior of the transaction to ensure that if the upload fails for a single resource, then the entire upload fails. We've found a workaround for the references in the meantime! 

Thank you!!

Chris
