### ISSUE TITLE
How to migrate single tenant data to multi-tenant deployment?

### ISSUE THREAD

**Issue by nirojshrestha019** [awslabs/fhir-works-on-aws-deployment#588]
**What's on your mind?**
Currently, we have single-tenant FWOA deployed. But we are going to enable multi-tenancy in our new FWOA deployment. We are following this documentation https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/USING_MULTI_TENANCY.md which mentions that 

> Updating an existing (single-tenant) stack to enable multi-tenancy is a breaking change. Multi-tenant deployments use a different data partitioning strategy that renders the old, single-tenant, data inaccessible. If you wish to switch from a single-tenant to a multi-tenant model, it is recommended to create a new multi-tenant stack and then migrate the data from the old stack.

Could you please let me know about the steps or documentation to migrate data from single tenant old stack to new multi-tenant stack?

Hoping to hear from you soon. Thanks

**Versions (please complete the following information):**
 - v4.1.0 (smart-mainline)

**Comment by Bingjiling** [comment]
Hi @nirojshrestha019 ,

Thanks for reaching out! I'll create a ticket to add documentation for multi-tenancy data migration. 

Here's an explanation on how a record from a single-tenant DDB map to new record in a multi-tenant DDB:  

```
Tenant isolation is achieved by adding the tenantId to the hash key. 

In single-tenant mode the id field in the DDB table is simply the id of the FHIR resource. 
For multi-tenancy a composite key will be used as hash key:

id = <tenantId>|<resourceId>
// Note: "|" is just a separator, it is not an OR

Also, 2 new metadata fields will be added:

* _id, this field simply stores the original FHIR resource id. It’s convenient to have it now that id is a composite key
* _tenantId

For example, a record in DDB for a Patient with id=id1 for the tenant with tenantId=tenant1 will be:

{
    "id": "tenant1|id1",
    "vid": 1,
    "_id": "id1",
    "_tenantId": "tenant1",
    "resourceType": "Patient",
    "birthDate": "1990-01-01"
    ...
}

```

Currently we don't have a script facilitating the above data migration, and if you happen to create one as part of your task, we would love for you to contribute the script back to the repository so other customers can share your wisdom. 

Hope this helps. 

Thanks,
Yanyu

**Comment by nirojshrestha019** [comment]
Thank you so much for the information @Bingjiling . Additionally, are there any changes necessary in **elastic search** and **S3 bucket** artifact to do the migration from single-tenant to multi-tenant deployment?

Yeah, sure I will let you know what approach we took to do this migration and provide the scripts for it too.

**Comment by SanketD92** [comment]
Hi @nirojshrestha019, 

Once you upgrade from single tenant to multi-tenant, all new resources added will function normally. However, existing data in S3 and search can't be retrieved since they do not have a `tenantId` in their path.

For S3, you'd need to insert `tenantId` into the object path, as shown below:
`s3://fhir-binary-bucket/<tenantId>/<Binary file name>`

Similarly for bulk export:
`s3://bulkexportresultsbucket/<tenantId>/<jobId>/<ResourceType>-<chunk #>.ndjson`

For search, you'd need to add the new attribute `tenantId` to each existing item. A search call would then look like:
```
{
    bool: {
        must: [
            // search query clauses
        ],
        filter: [
            {
                match:{
                    _tenantId: '<tenantId>'
                }
            }
            //... more filter clauses
        ]
    }
}
```

Hope this helps!

**Comment by nirojshrestha019** [comment]
@SanketD92 Thank you so much for the information. We are in the process of data migration from our single-tenant deployment to multi-tenant. Will update you on the progress and our learnings in this thread soon.

**Comment by lwarren01** [comment]
Hi @SanketD92 . I am working with @nirojshrestha019 on a migration plan from single to multi-tenant support. We have a single API client that is exclusively writing FHIR resources. We are hoping there is an opportunity here that would allow for us not to take an outage as we re-deploy the solution to enable multi-tenancy. We were hoping you might be able to provide some feedback on our plan prior to testing it out.

Here is what we were thinking:

1. Generate a tenantId (UUID) for the existing tenant.
2. Update Cognito to issue new tokens with the tenantId claim.
3. Wait 1 hour to drain pool of existing signed tokens.
4. Re-deploy the solution enabling multi-tenancy, but setting `useTenantSpecificUrl` to false.
5. Execute a CodePipeline to run a bulk update of all dynamoDB records to set the tenantId field as documented above.
6. Delete any content in either the bulk export, or binary S3 buckets. These buckets shouldn’t have any content in them.

**Comment by SanketD92** [comment]
Hi @lwarren01. The steps that you have laid out are correct, however we recommend deploying a separate environment with multi-tenancy enabled and then use a load balancer to slowly shift customer traffic to this new environment.

This is because if you directly upgrade and the process errors out for any reason, it would be very difficult to roll back.

**Comment by lwarren01** [comment]
Thanks @SanketD92 . Unfortunately we don't have a load balancer in front to redirect client traffic to the new installation seamlessly. Our clients are connecting to a custom private ApiGateway, so there is a chance we could modify this ApiGateway instance to proxy traffic to the new fhir-works installation. We will look into this. Thanks for the feedback!
