### ISSUE TITLE
[Misc] Order of Transaction-Response same as Transaction? 

### ISSUE THREAD

**Issue by christopher-watanabe-snkeos** [awslabs/fhir-works-on-aws-deployment#594]
Hi all,

I'd like to map resource Entries in a transaction Bundle to response Entries in the respective transaction-response Bundle after uploading to a Server. My question is: Can I safely assume that the order of responses is 1 to 1 with the resources? 

According to the R4 Standard, this seems to be the [case](http://hl7.org/fhir/R4/http.html#transaction-response)

> For a batch, or a successful transaction, the response the server SHALL return a [Bundle](http://hl7.org/fhir/R4/bundle.html) with [type](http://hl7.org/fhir/R4/bundle-definitions.html#Bundle.type) set to batch-response or transaction-response that contains one entry for each entry in the request, in the same order, with the outcome of processing the entry. For a failed transaction, the server returns a single [OperationOutcome](http://hl7.org/fhir/R4/operationoutcome.html) instead of a Bundle.

I can imagine this is maintained by the FHIR Server in question, so I'd like to ask: Does FhirWorks on AWS respect this specification? 

Thank you all very much! 

**Versions (please complete the following information):**
 - fhir-works-on-aws-persistence-ddb v3.9.0

**Comment by Bingjiling** [comment]
Hi @ChristopherWatanabe ,

Thanks for reaching out! We'll look into it and get back to you.

Thanks,
Yanyu

**Comment by nguyen102** [comment]
Yes, it appears that the order is preserved. 

Taking a look at the [code](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/5a5e18f8280300cde74c3a157c9fad2b47288c75/src/dataServices/dynamoDbBundleServiceHelper.ts#L40), I see that `newBundleEntryResponses` is returned. This array is built in sequential order based on the `request` coming in.

Please let us know if you find a bug in which the order is not preserved.
