### ISSUE TITLE
400kb item size limit in DynamoDB for Drug Formulary ingestion

### ISSUE THREAD

**Issue by WendyUmbriac** [awslabs/fhir-works-on-aws-deployment#595]
**Is your feature request related to a problem? Please describe.**
Early on, we identified FHIR Works as FHIR repository that was scalable, performant, and was already on MiHIN's roadmap to adopt. Recently, as we have implemented the drug formulary ingestion we have started to deal with large FHIR resource. Specifically the List resource which can have over 5k entries inside it. This has put us past a 400kb item size limit in DynamoDB. 

**Describe the solution you'd like**
Ability to link to an alternate DB that is not DynamoDB

**Describe alternatives you've considered**
HAPI FHIR

**Additional context**

**Comment by Bingjiling** [comment]
Hi @WendyUmbriac ,

Thanks for reaching out!

Right now we don't have it on our roadmap to create an alternate persistence layer other than DynamoDB. However, if you do have another DB in mind, you can implement it as a separate NPM package. As long as it supports the persistence interface defined in the interface package, you can plug it in through the deployment package without affecting any other functionalities in FWoA. 

Hope this helps. 

Thanks,
Yanyu

**Comment by nguyen102** [comment]
Closing this ticket as the ability for FHIR Works to use an alternate persistence layer is already available. Users can connect FHIR Works to another DB by implementing the [persistence interface](https://github.com/awslabs/fhir-works-on-aws-interface/blob/mainline/src/persistence.ts#L55)
