### ISSUE TITLE
[Misc] [Question] About update interaction behavior of FHIR Works on AWS.

### ISSUE THREAD

**Issue by Ken-Nakane-swg** [awslabs/fhir-works-on-aws-deployment#596]
**What's on your mind?**
Question about update interaction behavior of FHIR Works on AWS.

I try to update FHIR R4 Resource by client generated Resource.id.
The resource don't exist on FHIR Works Server at the time.

I execute update interaction (Http PUT) for this process but the server response is the following error OperationOutcome. Create interaction is OK.
```
{"resourceType":"OperationOutcome","text":{"status":"generated","div":"<div xmlns=\"http://www.w3.org/1999/xhtml\"><h1>Operation Outcome</h1><table border=\"0\"><tr><td style=\"font-weight: bold;\">error</td><td>[]</td><td><pre>Can not update resource with ID[1234567890-adt-a08], while the given request payload has an ID[undefined]</pre></td></tr></table></div>"},"issue":[{"severity":"error","code":"invalid","diagnostics":"Can not update resource with ID[1234567890-adt-a08], while the given request payload has an ID[undefined]"}]}
```

Please tell me how to resolve, if there is the configration and so on.

Other FHIR Server accept update interaction by client generated Resource.id. For example hapi google healthcare...

**Versions (please complete the following information):**
 - Release Version installed 4.0.0
 - I created stack... Amazon S3 URL: https://s3.amazonaws.com/solutions-reference/fhir-works-on-aws/latest/fhir-works-on-aws.template

**Comment by nguyen102** [comment]
Hi Ken,

To enable updating a resource with a custom id, you can pass the boolean value `true` for `supportUpdateCreate`.
The setting is [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/3e5fe2c0f9f83e1340a6d9f1b61243fb814f0086/src/config.ts#L38)

The change will look like this
`const dynamoDbDataService = new DynamoDbDataService(DynamoDb, false, { enableMultiTenancy });`

This will enable creating a resource with an id ([link](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/37e34732817d5053e9a3f57d69ed16e63147c979/src/dataServices/dynamoDbDataService.ts#L194)).

**Comment by Ken-Nakane-swg** [comment]
Hi Tim,
Thanks, I try to update the setting of my environment.
