### ISSUE TITLE
unauthorised error while invoking FHIR Apis 

### ISSUE THREAD

**Issue by vcareit** [awslabs/fhir-works-on-aws-deployment#598]
Hi , 

I have followed all the steps of deployment of FHIR works on AWS. I can get the metadata using postman. When I try to create patient I get unauthorised 401 error. I have been trying to debug the scenario with no success. 

In the lambda logs I can see the below mentioned error: (Lambda - fhir-service-dev-fhirServer)

UnauthorizedError: Unauthorized    at RBACHandler.isAllowed (/var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/fhir-works-on-aws-authz-rbac/lib/RBACHandler.js:79:1)    at RBACHandler.verifyAccessToken (/var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/fhir-works-on-aws-authz-rbac/lib/RBACHandler.js:32:1)    at /var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/fhir-works-on-aws-routing/lib/app.js:87:1    at Layer.handle [as handle_request] (/var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/express/lib/router/layer.js:95:1)    at trim_prefix (/var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/express/lib/router/index.js:317:1)    at /var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/express/lib/router/index.js:284:1    at Function.process_params (/var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/express/lib/router/index.js:335:1)    at next (/var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/express/lib/router/index.js:275:1)    at /var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/fhir-works-on-aws-routing/lib/router/middlewares/setServerUrl.js:26:1    at /var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/fhir-works-on-aws-routing/lib/router/routes/routeHelper.js:16:1 {  isUnauthorizedError: true} | 2022-03-21T21:07:17.521Z 85bc0833-8f9b-4a91-b311-8f571f0e9525 ERROR UnauthorizedError: Unauthorized at RBACHandler.isAllowed (/var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/fhir-works-on-aws-authz-rbac/lib/RBACHandler.js:79:1) at RBACHandler.verifyAccessToken (/var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/fhir-works-on-aws-authz-rbac/lib/RBACHandler.js:32:1) at /var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/fhir-works-on-aws-routing/lib/app.js:87:1 at Layer.handle [as handle_request] (/var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/express/lib/router/layer.js:95:1) at trim_prefix (/var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/express/lib/router/index.js:317:1) at /var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/express/lib/router/index.js:284:1 at Function.process_params (/var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/express/lib/router/index.js:335:1) at next (/var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/express/lib/router/index.js:275:1) at /var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/fhir-works-on-aws-routing/lib/router/middlewares/setServerUrl.js:26:1 at /var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/fhir-works-on-aws-routing/lib/router/routes/routeHelper.js:16:1 { isUnauthorizedError: true }
-- | --

I have tested the authoriser and it works fine. I am using the right idtoken. I have deployed FHIR works on AWS using cloud formation template in AWS:

**Comment by Zambonilli** [comment]
The stack trace points to your role to resource mapping rules not having an entry for the calling user's role having access to write to Patient. Check the cognito user you are calling with is in a role that allows creating Patient. Out of the box fwoa rbac rules has only the `Practitioner` role with the ability to `Create`.

https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/src/RBACRules.ts

**Comment by vcareit** [comment]
Thanks a lot for your reply. I figured this out while debugging I switched the user from patient to practitioner. The errors generated for incorrect user group was very generic. I have used the cloud formation template to create the stack. Is it possible to update the RBAC post stack creation ?

**Comment by rsmayda** [comment]
Yeah, you would need to make the changes via pulling down the code from GitHub and then redeploy the stack! If you didn't deploy that way initially then I would recommend you to start from scratch.

**Comment by vcareit** [comment]
Thanks a lot for the advise and it makes sense.
