### ISSUE TITLE
[Misc]  OAuth2 SMART compliant authorization server

### ISSUE THREAD

**Issue by liquid36** [awslabs/fhir-works-on-aws-deployment#603]
**What's on your mind?**

Which OAuth2 SMART compliant authorization server do you recommend? Are you using Cognito?  I cannot set up custom scopes without server identifier (example **fhirUser** **offline_access**) in Cognito so i'm thinking is not suitable for this approach. 

**Versions (please complete the following information):**
 - mainline-smart

**Comment by ssvegaraju** [comment]
Hi @liquid36. We have typically used Okta on our end and found it to work with our requirements. However, there are many other IdPs that would work as well. Okta has detailed instructions for setup with SMART that can be found [here](https://github.com/oktadev/okta-smartfhir-docs/blob/main/SETUP.md).

**Comment by liquid36** [comment]
Great! I'm evaluating Cognito as well an other OAuth Server. I make some improvement with Keycloak and [this extension](https://github.com/Alvearie/keycloak-extensions-for-fhir).

Have you try to be compliance with ONC and test the application against  [inferno testing suites](https://inferno.healthit.gov/suites)?

**Comment by ssvegaraju** [comment]
We do run a suite of inferno tests during our own testing, but we don't have a publicly available scorecard from the Inferno testing suite as of yet.
