### ISSUE TITLE
[Feature Request] patient $match operation support

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#615]
**Is your feature request related to a problem? Please describe.**
Currently fwoa does not support the patient $match operation. Customers of our fwoa implementation would like to match their internal database of patients to our patients in our fwoa implementation. The FHIR spec supports the matching of patients through the patient $match operation. In addition, our implementation of patient matching will need to be a custom matching algorithm through our eMPI and not self contained in fwoa. 

https://www.hl7.org/fhir/patient-operation-match.html

**Describe the solution you'd like**
Implementation of the patient $match operation that allows for custom implementations but the default implementation could leverage an out of the box fwoa implementation like Open Search's fuzzy search.

**Describe alternatives you've considered**
Leveraging the existing FHIR patient search functionality that is has already been implemented in fwoa. However, this leaves the responsibility of the algorithm to evaluate best match to each client that needs to do client patient matching.

**Additional context**
We are able to completely implement the patient $match operator in our private fork but are concerned about at some point when fwoa implements this separately our implementation will collide with the upstream fwoa implementation. Best case it would be purely symbol name differences but it could be implemented completely differently. We're open to creating a PR to help get the scaffolding in place for patient $match operation with a not implemented exception thrown or alternatively a rudimentary out of the box implementation of patient match that leverages Open Search's fuzzy search. Let us know what works best for the fwoa team and we can help.

**Comment by SanketD92** [comment]
Thank you for reporting this issue. We've created a ticket in our backlog.

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
