### ISSUE TITLE
facing issue createError (/var/task/node_modules/axios/lib/core/createError.js 

### ISSUE THREAD

**Issue by pawaramruta025** [awslabs/fhir-works-on-aws-deployment#617]
I tried to call an FHIR api but it gives createError (/var/task/node_modules/axios/lib/core/createError.js .Suddenly it stops working.Please help

![MicrosoftTeams-image (16)](https://user-images.githubusercontent.com/104631479/166114542-473d52bc-46fd-4f47-a14a-4277aad4ab0f.png)
.

**Comment by rsmayda** [comment]
Thanks for reaching out! To better help and understand where you are at, could you please share your FHIR works set-up? Specifically what your [package.json](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/package.json) and your [config.ts](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/src/config.ts) looks like?
