### ISSUE TITLE
[Bug] v2.5.1-smart deployment package.json uses rbac and not smart

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#622]
**Describe the bug**
The v2.5.1-smart tag in the fhir-works-on-aws-deployment's package.json has a dependency to fhir-works-on-aws-authz-rbac module and not fhir-works-on-aws-authz-smart module.

**To Reproduce**
1. Go to https://github.com/awslabs/fhir-works-on-aws-deployment/blob/v2.5.1-smart/package.json#L40
2. See fhir-works-on-aws-authz-rbac and not fhir-works-on-aws-authz-smart

**Expected behavior**
Smart line to use authz smart version 3.1.1 and not authz rbac.

**Screenshots**
n/a

**Versions (please complete the following information):**
 - fhir-works-on-aws-deployment repo's release tag for v2.5.1-smart

**Additional context**
n/a

**Comment by rsmayda** [comment]
Great eye -- looks like we tagged incorrect will get resolved quickly for the time being please use the `smart-mainline` branch

https://github.com/awslabs/fhir-works-on-aws-deployment/tree/smart-mainline

**Comment by Zambonilli** [comment]
no worries, I figured as much and it didn't block us at all.

**Comment by Bingjiling** [comment]
The tag has been updated. Thanks for catching it!

**Comment by Zambonilli** [comment]
no problem, thanks for the quick fix!
