### ISSUE TITLE
[Feature Request] Improve Lambda Log Structure for Log Reporting 

### ISSUE THREAD

**Issue by preethipanneer** [awslabs/fhir-works-on-aws-deployment#623]
Is your feature request related to a problem? Please describe. 
We want to build a report that is the distinct errors over a period of time that is grouped and sorted on the count of distinct errors. The report would be used for prioritizing distinct bugs happening in production with the context of the logs and the frequency the errors are occurring. 

Currently the log messages are logged as strings. And they have timestamps so, can’t be grouped. As the log level and message are part of the message string, log insights cannot extract out these fields. We also found that Log insights can only extract out the fields from the first json object in the input message. This makes it harder to group the error messages based on the type of errors/log level. We explored the options provided by log insights to parse the log messages to extract our error type and log level. Parsing the message makes the queries hard to maintain. And with large number of logs, the queries can get slower. 

Describe the solution you would like:
Adding more flexibility to log analysis by adding custom formatting in such way that the log messages can be queried easily – One option is to make the message json (Winston format can be used) instead of a string.

**Comment by maghirardelli** [comment]
Hi @preethipanneer ! Thanks for your message. We are going to look into this and get back to you!

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
