### ISSUE TITLE
[Feature Request] Log when express server is started and stopped

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#624]
**Is your feature request related to a problem? Please describe.**
Trying to debug when new instances of our fhirServer lambda are started and stopped is currently only possible by doing fuzzy back of the napkin math on the lambda's concurrent executions graph. This is problematic when trying to figure out definitively when shared state in the process has been created or released. For example, we have connections in a shared HTTP connection pools to services that require authenticated connections. However, we lack visibility into when our lambdas are being restarted and it's hard to definitively answer the question, "are we thrashing service xyz's authentication process right now?"

**Describe the solution you'd like**
Application log message when the express.js server is started and stopped so we can create log insight reports of starts and stops.

**Describe alternatives you've considered**
Using the Concurrent Executions metric and reporting to get a general idea.

**Additional context**
Happy to do the PR here.

**Comment by ssvegaraju** [comment]
This is a good point and a useful metric; I've added this to our team's backlog. Would also be happy to review a PR if you already have one in the works or plan to work on it. Thanks for bringing this up!

**Comment by Zambonilli** [comment]
PR created, https://github.com/awslabs/fhir-works-on-aws-deployment/pull/627

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
