### ISSUE TITLE
[Feature Request] Update lambdas to nodejs 16 LTS

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#626]
**Is your feature request related to a problem? Please describe.**
Lambda team announced support for nodejs 16.x LTS major version. Biggest win looks to be performance improvements over 14.x and some syntactical sugar around timeouts and regexes.

**Describe the solution you'd like**
Update all lambdas to nodejs 16.x LTS major version.

**Describe alternatives you've considered**
Stay with 14.x a bit longer but 14.x LTS maintenance is scheduled to end in 2023-04-30

**Additional context**
https://aws.amazon.com/about-aws/whats-new/2022/05/aws-lambda-adds-support-node-js-16/

**Comment by Bingjiling** [comment]
Hi @Zambonilli,

Thanks for reaching out! I'll add this issue to our backlog. 

Thanks,
Yanyu

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
