### ISSUE TITLE
Using the sub id generated in Cognito user pool as ID to create FHIR resource

### ISSUE THREAD

**Issue by vcareit** [awslabs/fhir-works-on-aws-deployment#628]
**What's on your mind?**
I would like to use the sub id created in Cognito as part of user registration to create patient id. Currently When I create a patient the ids are different - What I have in Cognito and what is auto generated in FHIR.

How can I control the id generation and link it to the ids in Cognito. 

Example Workflow - Patient Group members would self register themselves as patient with observations and conditions. Currently There is no link I can establish to link the generated user pool id and patient record id that I get after the creation. Which means I will have to either create a separate map or can I edit the code to use Cognito user pool id ?

**Comment by Bingjiling** [comment]
Hi @vcareit,

Thanks for reaching out! There're two ways this could work: 

1. Add custom field in Cognito to save the patient record id generated from FWoA 
2. Add custom field in FWoA to save the Cognito id generated (through extending the resource with Implementation Guide)

Based on which ID is generated first in the workflow, you can pick the approach. 

From a design perspective, I think the primary identifier of FWoA patient and Cognito patient should be kept different. Using the same id as primary identifier would deeply couple the two and could add complexity and challenge to future update. 

Thanks,
Yanyu

**Comment by vcareit** [comment]
Thanks a lot for clarification. I was able to solve this.

**Comment by vcareit** [comment]
You can close this issue

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
