### ISSUE TITLE
[Bug] Cannot enable updateCreate on resources

### ISSUE THREAD

**Issue by spookybando** [awslabs/fhir-works-on-aws-deployment#629]
**Describe the bug**
Trying to enable `updateCreate` on resources does not appear to work, updateCreate is set to false in the capability statement. I have hardcoded the the `supportUpdateCreate` parameter as true in the [following](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/4b0fdf66f94274facf7d7bc14508575b319a58a8/src/config.ts#L39) code in `src/config.ts`:

```
const dynamoDbBundleService = new DynamoDbBundleService(DynamoDb, true, undefined, {
    enableMultiTenancy,
})
```

I have tried updating the config then deploying on an already existing instance, as well as deploying a second instance without any luck getting updateCreate enabled. 

**To Reproduce**
1) Update `src/config.ts` as shown above
2) Serverless deploy

**Expected behavior**
`updateCreate` should be true for resources in the capability statement

**Versions (please complete the following information):**
 - Commit hash 6bfd49b1cbf15bd6591e8d37eec970d6a7c18fb4
 - Version 4.3.1

**Comment by Bingjiling** [comment]
Hi @spookybando,

Thanks for reaching out! We'll look into this issue. 

At the meantime, could you please provide an example of test you ran to confirm the updateCreate functionality? We'll use it to reproduce the issue on our side. 

Thanks,
Yanyu

**Comment by ssvegaraju** [comment]
Hi @spookybando, just checking something really quick: I see you've updated the `DynamoDbBundleService` constructor in `config.ts`. I just wanted to ask whether you wanted to support update create for Bundles or for individual resources? If it's for individual resources, I believe the change to the `DynamoDbDataService` constructor (same change, just updating the `false` to `true` for the `supportUpdateCreate` flag) is more what you are looking for rather than the bundle service. Let me know if this helps!

Thanks for your time,
Sukeerth

**Comment by bgfreitas** [comment]
Hi @ssvegaraju,

Same problem here. 
When changing:

`dynamoDbDataService = new DynamoDbDataService(DynamoDb, true, { enableMultiTenancy });". `
Then deploy.

I didn't get the expect behavior:

<img width="998" alt="image" src="https://user-images.githubusercontent.com/3239481/221946723-4e78a8fe-c56e-4c54-9370-b34032188d27.png">


What is still missing?
Thanks.

Best regards,
Bruno

**Comment by ssvegaraju** [comment]
Hey @bgfreitas, it looks like you're using POST instead of PUT in those screenshots, could you try making a put request and seeing if that works? The update Create functionality allows put requests to create resources while post requests remain unaffected.

Thanks,
Sukeerth

**Comment by bgfreitas** [comment]
Perfect @ssvegaraju! Now it works!
<img width="663" alt="image" src="https://user-images.githubusercontent.com/3239481/221986066-58c87dba-1f3f-44ae-9d34-189eea584c1d.png">
Many Thanks!
