### ISSUE TITLE
[Feature Request] search parameters on ObservationDefinition

### ISSUE THREAD

**Issue by KevinMayfield** [awslabs/fhir-works-on-aws-deployment#631]
FHIR ObservationDefinition is a new resource on FHIR R4 and lacks any defined search parameters. 

This makes this endpoint not as useful as it could be. The search we (Virtually Healthcare) would be interested in is defined here  

https://github.com/NHSDigital/NHSDigital-FHIR-ImplementationGuide/blob/master/SearchParameter/SearchParameter-ObservationDefinition-code.json

Is it possible to add this to AWS FHIR Works, is this something we could configure?

**Comment by KevinMayfield** [comment]
This is a SearchParameter defined in FHIR R5.

**Comment by nguyen102** [comment]
Hi @KevinMayfield ,

We currently do not have search configured for this new resource. I'll add this feature request to our backlog though.

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
