### ISSUE TITLE
FUNCTION_ERROR_INIT_FAILURE on deploy using install.md

### ISSUE THREAD

**Issue by viperx77** [awslabs/fhir-works-on-aws-deployment#634]
**Describe the bug**
Following the documentation INSTALL.md fails to install with:

`serverless deploy --stage dev --region us-west-2 --enableMultiTenancy true`

Fails with:
Logical ID: FhirServerProvConcLambdaAlias 
Status: CREATE_FAILED
Status Reason: Provisioned Concurrency configuration failed to be applied. Reason: FUNCTION_ERROR_INIT_FAILURE

**To Reproduce**
1. `serverless deploy --stage dev --region us-west-2 --enableMultiTenancy true`

**Expected behavior**
The deployment will succeed.

**Versions (please complete the following information):**
 - Release v4.3.1

**Comment by ssvegaraju** [comment]
Hey @viperx77, this error is usually one that comes up whenever there is an issue with the Lambda code, or if there is an issue with recognizing the handler for the lambda function. A few questions: 
- Have you run `yarn install` and `yarn build`? 
- Are you following the Manual installation portion of the INSTALL.md?
One additional option to troubleshoot is to remove the provisioned concurrency for the lambda function that is failing to create from the `serverless.yaml` template [(line here)](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/serverless.yaml#L112) and deploying to get more information on the stack trace about what exactly is going wrong.
