### ISSUE TITLE
[Bug] Abnormally high KMS usage

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#639]
**Describe the bug**
In our production environments our last monthly bill had ~3k USD usage for KMS. This environment is currently only receiving ~5 requests/second, so the amount of KMS usage is abnormally high for such little load.

Looking into the issue we discovered that the aws-sdk does not create and use https connection pools by default. Instead, the aws-sdk will create a new https connection on every service request. Looking into DynamoDB's documentation on how it interacts with KMS, dynamoDB will create table keys that are seeded from the KMS CMK and use the table key to derive data keys for encrypting/decrypting data in the table for a sliding expiration of 5 minutes per connection to DynamoDB. With the aws-sdk by default not reusing https connections, each request to fhir server is causing dynamoDB to thrash KMS decrypt operations to recreate the table key and data keys for a single use. Similarly, all other lambdas are exhibiting the same behavior.

**To Reproduce**
1. Send through a slew of FHIR requests that use dynamoDB like POST patient
2. Navigate to AWS Cloudtrail
3. Select Event History
4. Update the filter to "Event Source" with a value of "kms.amazonaws.com"
5. Export to csv
6. Group the rows by Username and Source IP
7. Assert that the fhirServer lambda user has called decrypt for dynamodb for each request

**Expected behavior**
KMS decrypt to not be called on every single request to FHIR Server lambda and other lambdas.

**Screenshots**
[aws-sdk reusing connections](https://docs.aws.amazon.com/sdk-for-javascript/v2/developer-guide/node-reusing-connections.html)
[dynamodb KMS](https://docs.aws.amazon.com/kms/latest/developerguide/services-dynamodb.html)

**Versions (please complete the following information):**
v2.5.1-smart but we believe this affects all versions

**Additional context**
We've successfully deploy our private fork of v2.5.1-smart fwoa to our alpha environments with all lambdas having the  `AWS_NODEJS_CONNECTION_REUSE_ENABLED` environment variable set to `1` and have confirmed that by reusing https sockets the KMS usage goes from every request down to only calling decrypt on the initial https socket creations. This should lower the KMS usage and bill by orders of magnitude as well as result in lower response times, higher throughput and higher reliability. I will send a PR through by the end of the day.

**Comment by kpark277** [comment]
Hi @Zambonilli, thank you for reporting this issue and providing the PR to fix it. [The PR](https://github.com/awslabs/fhir-works-on-aws-deployment/pull/640) has now been merged. I am closing this issue; please re-open if there are any other questions or concerns.
