### ISSUE TITLE
[Bug] IGs since IG Publisher 1.1.119 fail to parse

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#642]
**Describe the bug**
We're seeing our Implementation Guide fail to be parsed by scripts/compile-igs.ts with `Exception:  Missing dependency hl7.terminology.r4@3.1.0 Error: Missing dependency hl7.terminology.r4@3.1.0`. We have not created a custom terminology server and are not using any other IGs. We've been able to identify that as of IG publisher version 1.1.119 a new dependency is added to the IG tgz's package.json for `hl7.terminology.r4` : `3.1.0`. Rolling back to 1.1.118 IG publisher fixes the fwoa compiler error and the script completes successfully. We haven't had enough time to root out exactly what the issue is yet and there's nothing that jumps out in the IG publisher 1.1.119 release notes to indicate the root cause. We do however believe that since our IG is so basic that other people creating IGs will have the same issue in fwoa compiler.

IG Publisher 1.1.118 dependencies:
```
"dependencies": {
    "hl7.fhir.r4.core": "4.0.1"
  },
```

IG Publisher 1.1.119+ dependencies
```
"dependencies": {
    "hl7.fhir.r4.core": "4.0.1",
    "hl7.terminology.r4": "3.1.0"
  },
```

**To Reproduce**
1. Use IG Publisher 1.1.119 or greater to generate a tgz of your IG
2. Navigate to the deployment repo 
3. yarn install
4. yarn run compile-igs
5. assert that the compiler returned the error `Exception:  Missing dependency hl7.terminology.r4@3.1.0 Error: Missing dependency hl7.terminology.r4@3.1.0`

**Expected behavior**
Successfully compiled IG. Although, I'm not sure if the IG Publisher is now producing different output since it looks like there are pushes for r4b in the more recent releases. This could be an error with the IG publisher no longer being backwards compatible with r4.0.1.

**Versions (please complete the following information):**
v2.5.1-smart

**Additional context**
https://github.com/HL7/fhir-ig-publisher/releases/tag/1.1.119

**Comment by SanketD92** [comment]
Thank you for creating this bug report. I'll create a ticket in our team's backlog.

**Comment by ssvegaraju** [comment]
Hi,
just wanted to update that we've introduced a fix that may be a workaround for this issue: https://github.com/awslabs/fhir-works-on-aws-deployment/pull/789. This should allow you to include the dependencies that the ig compiler complains about, and not run into the issue of the Lambda being too large to deploy. Unfortunately we're unable to merge this code to mainline at this time due to conflicts on our end, but the code has been tested and reviewed. We're continuing to look into the changes to the IG Publisher as well to see what else we can do to address the compiler.

Thanks,
Sukeerth

**Comment by Zambonilli** [comment]
Woah, super cool! We were actually looking to update our private fork to load IGs from s3 as well for a lot of the same reasons. We'll keep an eye out for changes to that PR.

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
