### ISSUE TITLE
[Bug] Same Structure Defintion can be registered

### ISSUE THREAD

**Issue by kuma1416** [awslabs/fhir-works-on-aws-deployment#643]
**Describe the bug**

After a structure definition was registered, I tried to register same one. FHIR Works allowed it.
I don't think FHIR specification allows to register duplicated structure definition because structure definition is uniquely identified by the URL.

**To Reproduce**
1. Making a structure definition
2. Registering the structure definition
3. One more

the sample of a structure definition.
https://github.com/HealthDataWorks/fhir-ig-jp-eCheckup/blob/main/input-json/resources/StructureDefinition-jp-eCheckup-Observation.json

**Expected behavior**
When I register the structure definition again, FHIR has to say 'an error' because FHIR has already the same structure definition.

**Screenshots**

**Versions (please complete the following information):**
 - commit 432d4a88e74c4bfec5b0374ee21f592aaebaef02

**Comment by SanketD92** [comment]
Thank you for creating this bug report. I'll create a ticket in our team's backlog.

**Comment by kuma1416** [comment]
Thank you for creating a ticket!

**Comment by ElliotSilver** [comment]
@kuma1416 When you "register the structure definition again" are you saying the id is the same or the canonical url (url element) is the same? I believe canonical urls may be duplicate--actually, duplicate canonicals have to be permitted in order to have multiple versions of the same struct def.
