### ISSUE TITLE
Mismatch node engine versions (package.json and install.sh)

### ISSUE THREAD

**Issue by zeubs** [awslabs/fhir-works-on-aws-deployment#645]
Package.json on line 132 states:
"node": ">=14.0.0"

but /scripts/install.sh which helps install dependencies
from line 56 to to 67
installs version 12

This leads to dependencies being unmet and the script failing.

Of course seasoned devs will easily bypass the issue but when statrting with a vanilla environment and relying on the automated script this is less than ideal.
I replaced 12 with 14 and the script was a lot happier :)

**Comment by Bingjiling** [comment]
Hi @zeubs,

Thanks for spotting this issue! I'm wondering if you would be open to create a PR to fix this issue give you've already resolved it? 

Thanks in advance for your contributions!

Thanks,
Yanyu
