### ISSUE TITLE
[Misc] unable to request MedicationRequest and Observation resourceType

### ISSUE THREAD

**Issue by fkmkana** [awslabs/fhir-works-on-aws-deployment#665]
**What's on your mind?**
Please let us know what you think about the following error.
And please let me know the part of the source code that check.

**1. About resourceType MedicationRequest**

I sent the request of resourceType MedicationRequest on FHIR works on AWS.
The following error was returned.
```
ERROR　InvalidResourceError: Bundle.entry[0].resource.ofType(MedicationRequest).dosageInstruction[0].extension[0].url - 
Value is 'http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_MedicationRequest_DosageInstruction_PeriodOfUse' 
but must be 'http://jpfhir.jp/fhir/core/Extension/JP_MedicationRequest_DosageInstruction_PeriodOfUse'
```

When I check the JPCORE site （https://jpfhir.jp/jpcoreV1/MedicationRequest.html） ,
I think the URL containing "StructureDefinition" is correct.

**2. About reqourceType Observation**

I sent the request of resourceType Observation on FHIR works on AWS.
The following error was returned.

<error 1>
```
Observation.basedOn[0] - The type 'ServiceReqest' is not a valid Target for this element
 (must be one of [CanonicalType[http://hl7.org/fhir/StructureDefinition/CarePlan],
  CanonicalType[http://hl7.org/fhir/StructureDefinition/DeviceRequest],
  CanonicalType[http://hl7.org/fhir/StructureDefinition/ImmunizationRecommendation], 
  CanonicalType[http://hl7.org/fhir/StructureDefinition/MedicationRequest], 
  CanonicalType[http://hl7.org/fhir/StructureDefinition/NutritionOrder], 
  CanonicalType[http://hl7.org/fhir/StructureDefinition/ServiceRequest]])
```

<error 2>
```
Observation.category[0].coding[0] - The Coding references a value set, not a code system ('http://hl7.org/fhir/ValueSet/observation-category')
Observation.category[0].coding[0] - Unknown Code System 'http://hl7.org/fhir/ValueSet/observation-category'
Observation.interpretation[0].coding[0] - The Coding references a value set, not a code system ('http://hl7.org/fhir/ValueSet/observation-interpretation')
Observation.interpretation[0].coding[0] - Unknown Code System 'http://hl7.org/fhir/ValueSet/observation-interpretation'
Observation.referenceRange[0].type.coding[0] - The Coding references a value set, not a code system ('http://hl7.org/fhir/ValueSet/referencerange-meaning')
Observation.referenceRange[0].type.coding[0] - Unknown Code System 'http://hl7.org/fhir/ValueSet/referencerange-meaning'
Observation.referenceRange[1].type.coding[0] - The Coding references a value set, not a code system ('http://hl7.org/fhir/ValueSet/referencerange-meaning')
Observation.referenceRange[1].type.coding[0] - Unknown Code System 'http://hl7.org/fhir/ValueSet/referencerange-meaning'
```

<basedOn.type>
My Request(Error) : ServiceRequest
Success request   : http://hl7.org/fhir/StructureDefinition/ServiceRequest

<category.coding.system.value and referenceRange.type.coding.system.value>
My Request(Error) : http://hl7.org/fhir/ValueSet/xxxx
Success request   : http://terminology.hl7.org/CodeSystem/xxxx

<interpretation.coding.system.value>
My Request(Error) : http://hl7.org/fhir/ValueSet/observation-interpretation
Success request   : http://terminology.hl7.org/CodeSystem/referencerange-meaning

I don't know which request is correct as a JPCORE specification.

**Comment by Bingjiling** [comment]
Hi @fkmkana , 

Thanks for reaching out! Have you installed the JPCORE implementation guide in your FWoA deployment? If so, could you please share the steps you go through to install the implementation guide?

Thanks,
Yanyu

**Comment by fkmkana** [comment]
Thanks.
I installed the JPCORE implementation guide with the following steps.

**Get the JPCORE implementation guide**
1. Install Firely Terminal
2. Run the following command
`# fhir install JP-CORE.Draft 1.0.5`

Reference site : https://registry.fhir.org/package/JP-CORE.Draft%7C1.0.5

**Install and deploy**
1. Put the JPCORE implementation guide in local environment
    PHRPoC > hir-works-on-aws-deployment-4.0 > implementationGuides > package
2. Set up the AWS credentials file in my FWoA deployment
3. Run the following command in my FWoA deployment
```
#fhir-works-on-aws-deployment
yarn run compile-igs

#fhir-works-on-aws-deployment/javaHapiValidatorLambda
cd javaHapiValidatorLambda
mvn clean install

#fhir-works-on-aws-deployment
cd ..
serverless deploy --region ap-northeast-1
serverless deploy --useHapiValidator true --region ap-northeast-1
```
Reference site : https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/USING_IMPLEMENTATION_GUIDES.md

**version of fhir-works-on-aws-deployment**
v4.0.0

**OS**
Windows 10 Pro 64bit

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
