### ISSUE TITLE
[Bug] Unable to compile US Core Implementation Guides 

### ISSUE THREAD

**Issue by yonghaochen-nt** [awslabs/fhir-works-on-aws-deployment#671]
**Describe the bug**
I followed the [Using FHIR Implementation Guides](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/USING_IMPLEMENTATION_GUIDES.md#using-fhir-implementation-guides), created `implementationGuides` directory and downloaded us-core IG packages and dependencies.  When I use `yarn run compile-igs` in the parent directory, it throw the error below:

Exception:  The following input is not a search parameter: {
  "code": "end",
  "description": "Optional Extensions Element",
  "experimental": true,
  "id": "valueset-extensions-ValueSet-end",
  "name": "end",
  "resourceType": "SearchParameter",
  "status": "draft",
  "type": "date",
  "url": "[http://hl7.org/fhir/SearchParameter/valueset-extensions-ValueSet-end"](http://hl7.org/fhir/SearchParameter/valueset-extensions-ValueSet-end%22),
  "version": "4.0.1",
  "xpath": "f:ValueSet/f:extension[@url='[http://hl7.org/fhir/StructureDefinition/valueset-expirationDate']](http://hl7.org/fhir/StructureDefinition/valueset-expirationDate%27]) | /f:#expirationDate",
  "xpathUsage": "normal"
}

**Expected behavior**
the us core IG and its dependencies could be compiled without errors.

**Comment by ssvegaraju** [comment]
Hi @yonghaochen-nt, could you provide a link to the us-core IG and dependencies you are trying to compile? Also, if you could list the steps you took when adding them to the `implementationGuides` directory, that would be very helpful for us to try and reproduce this bug on our end!

Thanks,
Sukeerth

**Comment by yonghaochen-nt** [comment]
> Hi @yonghaochen-nt, could you provide a link to the us-core IG and dependencies you are trying to compile? Also, if you could list the steps you took when adding them to the `implementationGuides` directory, that would be very helpful for us to try and reproduce this bug on our end!
> 
> Thanks, Sukeerth

Hi @ssvegaraju , us-core IG is from [https://build.fhir.org/ig/HL7/US-Core/package.tgz](url). Dependencies are 
[hl7.fhir.r4.examples](https://simplifier.net/packages/hl7.fhir.r4.examples/4.0.1)
[hl7.fhir.uv.bulkdata](https://simplifier.net/packages/hl7.fhir.uv.bulkdata)
[hl7.fhir.uv.sdc](https://simplifier.net/packages/hl7.fhir.uv.sdc)
[hl7.fhir.uv.smart-app-launch](https://simplifier.net/packages/hl7.fhir.uv.smart-app-launch)
[hl7.terminology.r4](https://simplifier.net/packages/hl7.terminology.r4)
[us.nlm.vsac](https://simplifier.net/packages/us.nlm.vsac)

I downloaded these packages and put them into `implementationGuides` under `fhir-works-on-aws-deployment`.  Except these I was I followed the [Using FHIR Implementation Guides](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/USING_IMPLEMENTATION_GUIDES.md#using-fhir-implementation-guides). Hope that is good for you to reproduce it.

**Comment by ssvegaraju** [comment]
Hi, I was able to reproduce this bug successfully. I will add this bug to our team's backlog! Thanks for providing all of the information above.

**Comment by floofydoug** [comment]
Just checking in on this bug. the US-Core IG is a requirement for g(10) certs which will be required by December 2022

**Comment by FernandoAranda** [comment]
Hi, we are currently working on this item and we will keep you posted for any updates.

Thanks

**Comment by floofydoug** [comment]
for anyone else experiencing this and needs a way forward... i reverted to us-core 4.0.0, (the 2021 release), and `yarn run compile-igs` accepts this version.

**Comment by ssvegaraju** [comment]
Hi,
We've introduced a fix for this issue here: https://github.com/awslabs/fhir-works-on-aws-deployment/pull/789
Unfortunately we're unable to merge the code into mainline branch at this time due to conflicts on our end, but this code has been tested and will work to fix the issue of being unable to deploy implementation guides that are too large. This should allow dependencies for implementation guides to be included without running into errors with deployment.

Thanks,
Sukeerth

**Comment by kyle-mwnz** [comment]
Hi @ssvegaraju  - when will this be in the mainline branch?

**Comment by ssvegaraju** [comment]
Hey @kyle-mwnz,

We have this prioritized in our backlog, and tentatively plan to release this fix in April!

Thanks,
Sukeerth

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
