### ISSUE TITLE
[Bug] Subscription SNS topic name not unique per stage

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#672]
**Describe the bug**
The `SubscriptionsTopic` cloudformation resource in cloudformation/subscriptions.yaml is creating the SNS topic with the name `SubscriptionsTopic`. This causes a conflict on name when trying to deploy multiple stages to a single AWS account.

**To Reproduce**
1. Deploy FWoA to an AWS account
2. Open AWS console
3. Navigate to SNS
4. See `SubscriptionsTopic` SNS topic name

**Expected behavior**
A unique name for the SNS topic so multiple stages can be deployed to the same environment.

**Versions (please complete the following information):**
v4.3.1 and v2.5.1-smart. Sorry, we're still pinned a version behind and am unsure if the CDK update has fixed this. I'm assuming the issue still exists because cloudformation/subscriptions.yaml still exists with the explicit setting of the name to `SubscriptionsTopic`.

**Additional context**
https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/cloudformation/subscriptions.yaml#L88

**Comment by ssvegaraju** [comment]
I saw the Pull request before I saw this, but I've gone ahead an approved the PR! This was definitely a needed change and has already been reflected in the CDK stack, so no need to worry about that side.

Thanks for your time,
Sukeerth
