### ISSUE TITLE
[Feature Request] Support for greater than 25 bundle transaction entries

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#674]
**Is your feature request related to a problem? Please describe.**
Currently FHIR Works on AWS only supports up to 25 entries in a POST bundle with type transaction. This maps well to the dynamodb transaction functionality but causes use cases that require more than 25 entries to handle multiple calls on the client. The FHIR community generally believes that this is an implementation problem and the implementation should support more than 25 entries. We have a core use case that requires more than 25 see, https://chat.fhir.org/#narrow/stream/179166-implementers/topic/Max.20bundle.20size.3F

I've got a local version of FHIR Works that supports up to 100 transaction entries by replacing the dynamoDB transaction calls with logic to chunk out multiple transaction calls.

Here are all the touch points that I'm seeing and have running:
_routing_
* update max entries input validation to 100 - https://github.com/awslabs/fhir-works-on-aws-routing/blob/mainline/src/constants.ts#L6

_persistence_
* Bump max to 100 - https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/mainline/src/dataServices/dynamoDbBundleService.ts#L49
* update lockItems ddb transaction call - https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/mainline/src/dataServices/dynamoDbBundleService.ts#L381
* update rollBackItems ddb transaction call - https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/mainline/src/dataServices/dynamoDbBundleService.ts#L598
* update stageItems ddb write transaction call - https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/mainline/src/dataServices/dynamoDbBundleService.ts#L661
* update stageItems ddb get transaction call - https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/mainline/src/dataServices/dynamoDbBundleService.ts#L669

**Describe the solution you'd like**
Update of FHIR Works on AWS to support more entries than 25. Ideally, allowing up to 100 entries (4x dynamodb transaction calls).

**Describe alternatives you've considered**
We've evaluated 3 different ways to do writes:
* client performs saga pattern using multiple FHIR transactions
* client performs saga pattern on child observations and subsequently writes a parent "panel" observation
* client uses FHIR bundle batch type with subsequently writes a parent "panel" observation

**Additional context**
Are there any other reasons besides keeping the simplicity of FHIR transaction to DynamoDB transaction being 1:1 that I'm not accounting for here? Happy to see if others in the community have this same problem or if this is specific to our needs and keep in our private fork. Also, happy to do the leg work here and get PRs for your review.

**Comment by ssvegaraju** [comment]
Hi @Zambonilli, thanks for bringing this up! As far as I am aware (I could be wrong), the main reasoning for the 25 item limit was indeed the limit on the DDB Transaction calls. There are a few approaches we could take to circumvent this (as we did with Batch), but these may also run into the issue of the 6MB Lambda limit, or the 30 second API Gateway timeout, as preemptive considerations. I'm happy to review any PRs you may have, but can also add this to our backlog to tackle!

Thanks,
Sukeerth

**Comment by Zambonilli** [comment]
PRs for support up to 100 entries in a FHIR transaction. 

routing = https://github.com/awslabs/fhir-works-on-aws-routing/pull/170
persistence-ddb = https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/pull/153

**Comment by ssvegaraju** [comment]
Sorry for the delayed response, I will take a look at these PRs and test them, and let you know how it goes!

**Comment by ssvegaraju** [comment]
Just merged both PRs, everything passed our tests locally! Thanks for taking this up! I'll release the changes on npm as well. I'll go ahead and mark this issue as resolved for now, but feel free to reopen if there's anything else.
