### ISSUE TITLE
[Feature Request] Update github actions runner

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#680]
**Is your feature request related to a problem? Please describe.**
The github actions ubuntu 18.04 runner is being deprecated by github. They just ran a "brown out" where any action that tried to run with the ubuntu 18.04 runner was automatically cancelled. 

github thread on the issue
https://github.com/actions/runner-images/issues/6002

**Describe the solution you'd like**
Update to a github action runner that is not in the proces sof being deprecated

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Bingjiling** [comment]
Hi Mike,

Thanks for sharing the information! I'll bring this up to the team to get this update prioritized. 

Thanks,
Yanyu

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
