### ISSUE TITLE
Composite search doesn't work for local development (serverless-offline)

### ISSUE THREAD

**Issue by nirojshrestha019** [awslabs/fhir-works-on-aws-deployment#683]
**Describe the bug**
Composite search works for AWS deployed fireworks but doesn't seem to work for local development. Here is the sample composite search: 
`{{API_URL}}/Patient?family=Namajunas,Shrestha&given=Rose&birthdate=eq1990-10-25`

**To Reproduce**
1. create a patient with the following body: 
```
{
  "resourceType" : "Patient",
  "name" : [
    {
      "family" : "Musk",
      "given" : [
        "Elon"
      ]
    }
  ],
  "birthDate" : "1971-06-28",
  "managingOrganization" : {
    "reference" : "Organization/6f3e0616-e3d6-402c-b9a5-63a630babf32"
  }
}
```

2. Do the composite search on AWS deployed fhirworks. And here is the composite search to do:
`{{API_URL}}/Patient?family=Musk&given=Elon&birthdate=eq1971-06-28`
This gives the search result as expected.
3. Apply the same composite search query in serverless-offline deployed fhirworks (local development)
`{{API_URL}}/Patient?family=Musk&given=Elon&birthdate=eq1971-06-28`
It returns an empty search result but the simple search query gives search result: `{{API_URL}}/Patient?name=Musk

**Expected behavior**
I expect the composite search query to work in local development as it does in AWS deployed fhirworks.

**Versions (please complete the following information):**
 - v3.0.0-smart

**Additional context**

**Comment by FernandoAranda** [comment]
Hi @nirojshrestha019  thanks for bringing this to our attention, I added this bug to the team backlog

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
