### ISSUE TITLE
[Misc] Enable HAPI Validator V3

### ISSUE THREAD

**Issue by alex-harvey-z3q** [awslabs/fhir-works-on-aws-deployment#684]
**What's on your mind?**

How to we force V3 HAPI Validation to occur?

I need to force the FHIR Server Lambda function to route to the HAPI Validation stack and use V3 validation. It is not working, and
I am confused about what is really going on in the FHIR Server Lambda function. 

After deploying the stack, there is a Lambda function named 'fhir-service-dev-fhirServer'. The CloudFormation code is given in this screenshot (just so that you have a view of which version of the code we used):

<img width="679" alt="Screen+Shot+2022-09-01+at+7 37 18+pm" src="https://user-images.githubusercontent.com/2305330/188027018-10c684dc-eecd-4966-b3c9-b6878fadc7d3.png">

A variable `VALIDATOR_LAMBDA_ALIAS` is then exported, and the logic that I am expecting to respond to this variable begins on line 108,028 of src/index.js. Again, a screenshot of that logic:

<img width="1295" alt="Screen+Shot+2022-09-01+at+7 45 04+pm" src="https://user-images.githubusercontent.com/2305330/188027126-cf92d28d-4d60-4228-ad67-d2288811353e.png">

After reconfiguring and redeploying, I use curl to POST a request to the `dev/MedicationStatement` end point.

```
resource_type="MedicationStatement"

sample_payload='{"resourceType":"MedicationStatement","meta":{"profile":["http://hl7.org.au/fhir/ch/v1/StructureDefinition/ncdhc-medicationstatement-vitamink"],"versionId":"cbdd783e-cec4-4e33-b590-bc3df9a74083","lastUpdated":"2021-02-09T11:05:17.14+11:00"},"status":"completed","medicationCodeableConcept":{"coding":[{"system":"http://snomed.info/sct","code":"69775011000036100","display":"Phytomenadione"}],"text":"Vitamin K1"},"effectiveDateTime":"2021-02-09T11:00:00+11:00","dateAsserted":"2021-02-09T11:00:00+11:00","subject":{"reference":"Patient/0a56e30b-d55c-4073-840a-ade156a944d9"},"taken":"n"}'

test() {
  curl -k -X POST \
    -d"$sample_payload" \
    -H "Content-Type: application/json" \
    -H "Authorization:$id_token" \
    -H "x-api-key:$x_api_key" \
        https://"$api_id".execute-api.ap-southeast-2.amazonaws.com/dev/"$resource_type"
}
```

The response we get back in the logs shows that the JSON schema validation is still being used:

```
2022-09-01T19:09:52.437+10:00Copy2022-09-01T09:09:52.437Z	36ae2b93-5025-4858-83da-0c1bd629b14e	ERROR	InvalidResourceError: Failed to parse request body as JSON resource. Error was: data should NOT have additional properties    at JsonSchemaValidator.validate (/var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/fhir-works-on-aws-routing/lib/router/validation/jsonSchemaValidator.js:43:1)    at Object.validateResource (/var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/fhir-works-on-aws-routing/lib/router/validation/validationUtilities.js:11:1)    at ResourceHandler.create (/var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/fhir-works-on-aws-routing/lib/router/handlers/resourceHandler.js:22:1)    at /var/task/src/webpack:/codebuild/output/src548478748/src/source/node_modules/fhir-works-on-aws-routing/lib/router/routes/genericResourceRoute.js:146:1    at processTicksAndRejections (internal/process/task_queues.js:97:5) {  isInvalidResourceError: true}
```

**Versions (please complete the following information):**

We downloaded this one on May 26 2022:

```
▶ wget https://solutions-reference.s3.amazonaws.com/fhir-works-on-aws/latest/fhir-works-on-aws.template
```

We have made a few minor customisations to it for security but that's all.

**Comment by alex-harvey-z3q** [comment]
Further to this I tried a number of variations on trying to set up a dev environment using the instructions in this project, and now I get a broken FHIR server, that errors out with this:

```json
{
    "errorType": "TypeError",
    "errorMessage": "Cannot read property 'split' of undefined",
    "stack": [
        "TypeError: Cannot read property 'split' of undefined",
        "    at toIdentifier (/var/task/src/webpack:/Users/alexharvey/git/fhir-works-on-aws-deployment/node_modules/toidentifier/index.js:24:1)",
        "    at forEachCode (/var/task/src/webpack:/Users/alexharvey/git/fhir-works-on-aws-deployment/node_modules/http-errors/index.js:267:1)",
        "    at Array.forEach (<anonymous>)",
        "    at populateConstructorExports (/var/task/src/webpack:/Users/alexharvey/git/fhir-works-on-aws-deployment/node_modules/http-errors/index.js:265:1)",
        "    at Object.<anonymous> (/var/task/src/webpack:/Users/alexharvey/git/fhir-works-on-aws-deployment/node_modules/http-errors/index.js:31:1)",
        "    at __webpack_require__ (/var/task/src/webpack:/webpack/bootstrap:19:1)",
        "    at Object.<anonymous> (/var/task/src/webpack:/Users/alexharvey/git/fhir-works-on-aws-deployment/node_modules/send/index.js:15:19)",
        "    at __webpack_require__ (/var/task/src/webpack:/webpack/bootstrap:19:1)",
        "    at Object.<anonymous> (/var/task/src/webpack:/Users/alexharvey/git/fhir-works-on-aws-deployment/node_modules/express/lib/utils.js:20:12)",
        "    at __webpack_require__ (/var/task/src/webpack:/webpack/bootstrap:19:1)"
    ]
}
```

**Comment by alex-harvey-z3q** [comment]
I believe this (the comment above) was caused by 2 different versions of the http-error NPM module appearing in the source code.

**Comment by nguyen102** [comment]
Hi, you can follow the instructions [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/USING_IMPLEMENTATION_GUIDES.md) to use FHIR STU 3.

**Comment by alexharv074** [comment]
@nguyen102 I am not having much luck with those instructions. The [package.tgz](https://www.hl7.org/fhir/us/core/package.tgz) referred to in step 1 is for FHIR R4. Thus I need an appropriate one for STU3. I've tried this:

```
curl http://hl7.org/fhir/us/core/STU2/package.tgz | tar xz -C implementationGuides
yarn run compile-igs
```
This errors out with:
<img width="1465" alt="Screen Shot 2022-09-05 at 9 05 07 pm" src="https://user-images.githubusercontent.com/2305330/188434724-beb90619-229f-4a42-b7a2-3a9472d2585e.png">

To workaround that I've tried:

```
yarn config set registry https://packages.simplifier.net 
yarn add hl7.fhir.r3.core@3.0.2
yarn run compile-igs
```

And variations on this.

But the result is always the same.

**Comment by alex-harvey-z3q** [comment]
@nguyen102 I am not having much luck with those instructions. The [package.tgz](https://www.hl7.org/fhir/us/core/package.tgz) referred to in step 1 is for FHIR R4. Thus I need an appropriate one for STU3. I've tried this:

```
curl http://hl7.org/fhir/us/core/STU2/package.tgz | tar xz -C implementationGuides
yarn run compile-igs
```
This errors out with:

```
alexharvey@192-168-1-106 fhir-works-on-aws-deployment % yarn run compile-igs
yarn run v1.22.19
$ ts-node scripts/compile-igs.ts
looking at ig path: /Users/alexharvey/git/fhir-works-on-aws-deployment/implementationGuides/package
checking /Users/alexharvey/git/fhir-works-on-aws-deployment/implementationGuides/package/package.json
Exception:  Missing dependency hl7.fhir.r3.core@3.0.2 Error: Missing dependency hl7.fhir.r3.core@3.0.2
    at IGCompiler.depthFirst (/Users/alexharvey/git/fhir-works-on-aws-deployment/src/implementationGuides/IGCompiler.ts:183:19)
    at IGCompiler.depthFirst (/Users/alexharvey/git/fhir-works-on-aws-deployment/src/implementationGuides/IGCompiler.ts:191:22)
    at IGCompiler.validateDependencies (/Users/alexharvey/git/fhir-works-on-aws-deployment/src/implementationGuides/IGCompiler.ts:175:18)
    at IGCompiler.compileIGs (/Users/alexharvey/git/fhir-works-on-aws-deployment/src/implementationGuides/IGCompiler.ts:103:14)
    at async compileIGs (/Users/alexharvey/git/fhir-works-on-aws-deployment/scripts/compile-igs.ts:46:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

To workaround that I've tried:

```
yarn config set registry https://packages.simplifier.net 
yarn add hl7.fhir.r3.core@3.0.2
yarn run compile-igs
```

And variations on this.

But the result is always the same.

**Comment by ssvegaraju** [comment]
Hi, just wanted to update that this may be related to another bug we are aware of: https://github.com/awslabs/fhir-works-on-aws-deployment/issues/642
You could try downgrading the IG Compiler version to see if that resolves this issue?

**Comment by alex-harvey-z3q** [comment]
@ssvegaraju  Sorry, I am completely new to this and I don't even know what that means. Are there docs somewhere on how to downgrade the IG Compiler, or what that is?
