### ISSUE TITLE
[Feature Request] Clearer instruction for Lambda code package and more language support (python)

### ISSUE THREAD

**Issue by nathando** [awslabs/fhir-works-on-aws-deployment#686]
**Is your feature request related to a problem? Please describe.**
Currently, we can only access the lambda code package after deploying to CloudFormation and exporting from there.

**Describe the solution you'd like**
A clear instruction on where to get Lambda code package (git repo ?). And also support for other languages like Python. It currently only is in nodejs ?

**Comment by FernandoAranda** [comment]
Hi @nathando thanks for reaching out, I've added this feature request to our backlog.

-Fernando

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
