### ISSUE TITLE
[Feature Request] Support no-code configuration of operations

### ISSUE THREAD

**Issue by ElliotSilver** [awslabs/fhir-works-on-aws-deployment#687]
**Is your feature request related to a problem? Please describe.**
FHIR Works doesn't support appear to support operations (other than bulk export). We need to provide several of the FHIR core operations as well as some custom ones. Similarly, we'd like custom (or IG defined) search parameters.

**Describe the solution you'd like**
Provide a "no code" way to support additional operations and search parameters.

In my mind, I see a JSON config file similar to the following, that is read at "startup," and determines supported operations and search parameters:
```
[
   {
      "resource": "Patient",
      "searchParam": [
          {
              "name": "middleName",
              "definition": "http://example.org/fhir/SearchParameter/patient-middleName",
              "type": "reference",
              "documentation": "search by patient middle names",
              "handler": "SearchMiddleNameHandler"
          },
          ...
      ],
      "operation": [
          {
              "name": "match",
              "definition": "http://hl7.org/fhir/OperationDefinition/patient-match",
              "documentation": "FHIR standard Patient/$match operation",
              "handler": "OperationPatientMatch"
          },
          ...
      ],
   }
]
```

Right now, I've just put arbitrary "handler" values, and would be open to discussion about how best to connect the configuration to actual code (or a lambda).

(Our current need is adding/overriding operations and simple search parameters. However, I can envision being able to somehow define additional _include/_revInclude support, etc. An ultimate solution would essentially allow entry-by-entry control of the CapabilityStatement presented at /metadata along with a means to wire each claimed feature to the code that supports it.)

**Describe alternatives you've considered**
Manually code routes and CapabilityStatement content for each custom operation/search param.

**Additional context**
The ability to add search parameters and operations is required to support many implementation guides, and to build out the FHIR Works implementation of the FHIR core spec. If FHIR Works isn't going to provide the implementations of all core spec search parameters and operations, there should be a simple mechanism that allow FHIR Works customers to do it themselves.

**Comment by ElliotSilver** [comment]
Apparently, search parameters defined in the configured IG are supported automatically. However there may be instances where additional parameters are needed.

**Comment by FernandoAranda** [comment]
Hi @ElliotSilver  thank for bringing this to our attention, I added this feature request to the team's backlog.
We'll keep this ticket updated with any news related to the feature.

Thanks
Fernando

**Comment by ssvegaraju** [comment]
Hey @ElliotSilver, could you also provide a list of the features/operations you were hoping to be able to use with FWoA?

**Comment by ElliotSilver** [comment]
Our priority is Patient/$match, although I expect others like, $validate (base and type), Composition/$document, Observation/$lastn, Patient/$merge, ValueSet/$expand, and various $validate-code and $lookup may be desired later.

However, the complexity is that we want to provide our own operations (both custom implementations of standard operations, and new operations defined "in-house"). We need a way to wire these up simply (as well as enable/disable operations in particular environments).

Since submitting this ticket, we realized our initial approach to adding an operation was more invasive than it needed to be, and have taken a different approach that echoes how $docref is implemented/wired-up. However, it would still be helpful if we could move some of this effort into configuration.

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
