### ISSUE TITLE
An error occurred: SubscriptionsMatcherLambdaFunction - Resource handler returned message: "Specified ReservedConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of [10]

### ISSUE THREAD

**Issue by robertlario** [awslabs/fhir-works-on-aws-deployment#691]
**Describe the bug**
Running fhir-works-on-aws-deployment\scripts\win_install.ps1

In the new AWS account
In AWS Lambda Console : 
Full account concurrency is 10
and Unreserved account concurrency is 10

**To Reproduce**
1.  Create a new free AWS account
2.  run win_install.ps1
3. See error

ServerlessError: An error occurred: SubscriptionsMatcherLambdaFunction - Resource handler returned message: "Specified ReservedConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of [10]. (Service: Lambda, Status Code: 400, Request ID: f0182875-14ba-48a4-afb7-6e3ec9c90312)" (RequestToken: 4e849a11-4bb9-c6b0-d178-bd0723e7152c, HandlerErrorCode: InvalidRequest).

**Comment by FernandoAranda** [comment]
Hi @robertlario  thanks for reaching out.
This looks like an issue with your account limits, based on your account age, usage history, and other patterns, your accounts may start with limits that are lower than service defaults. As more information about the account is available overtime, AWS Lambda automatically restores service limits. 
To fix this issue you can request an increase on the concurrency limits of your account by:

1.    Open the [Service Quotas dashboard](https://console.aws.amazon.com/servicequotas/home).

2.    Choose the AWS Lambda card. The Lambda Service quotas page opens.

3.    Choose Concurrent executions.

4.    In the Recent quota increase requests pane, choose the Request quota increase button.

5.    Enter your requested concurrency limit. Then, choose Request.

for more information you can visit https://aws.amazon.com/premiumsupport/knowledge-center/lambda-concurrency-limit-increase/

I hope this helps you with the issue

Thanks
Fernando

**Comment by robertlario** [comment]
thanks. I have contacted AWS directly.
