### ISSUE TITLE
Some suggestions - Issues I ran across building the solution from the ground up

### ISSUE THREAD

**Issue by robertlario** [awslabs/fhir-works-on-aws-deployment#693]
I had some challenges with policy as provided in fhir-works-on-aws-deployment\scripts\iam_policy.json

I had to add :  
          "sqs:*",
          "glue:*"

in C:\My Workspaces\AWSFHIR220819\fhir-works-on-aws-deployment\scripts\win_install.ps1
line 212 is currently: $redep = (Get-CFNStack -StackName -Region $region fhir-service-$stage)
should it be $redep = (Get-CFNStack -StackName fhir-service-$stage -Region $region)?

Robert

**Comment by robertlario** [comment]
"sqs:*",
          "glue:*",

Seems the "star" symbol was stripped from my message

**Comment by FernandoAranda** [comment]
Hi @robertlario ,thank you for reaching out, I added this to the team's backlog

-Fernando

**Comment by joehep** [comment]
On my Mac the install process blindly did `brew update` which broke several unrelated to the projects things on my system that relied on specific versions. Granted relying on specific versions of stuff in general is not best practices, but forcing a system update when installing this seems a bit heavy handed.

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
