### ISSUE TITLE
What is the relationship between Deployment\lib and Deployment\cloudformation?

### ISSUE THREAD

**Issue by robertlario** [awslabs/fhir-works-on-aws-deployment#696]
Are the files in fhir-works-on-aws-deployment\lib generated?

Perhaps in some cases from the files in fhir-works-on-aws-deployment\cloudformation?

**Comment by ssvegaraju** [comment]
Hi,
We currently offer both CDK and Serverless as means of deployment for FWoA. The files in the cloud formation directory are part of the serverless stack, whereas the ones in lib are part of the CDK stack. The Serverless deployment pipeline is currently marked as legacy, however.
Thanks,
Sukeerth
