### ISSUE TITLE
[Misc] Project direction

### ISSUE THREAD

**Issue by joehep** [awslabs/fhir-works-on-aws-deployment#702]
What is the future of this project? I ask because it looks like the documentation page (https://docs.aws.amazon.com/solutions/latest/fhir-works-on-aws/welcome.html) has been taken down from the AWS docs site. My company is in the process of evaluating this solution for a FHIR service and want to make sure that it is ok to continue that process. 

I realize this probably isn't the best way to ask the question, but I just couldn't find any other way.

**Comment by liaden** [comment]
Also in an investigatory phase, and this is relevant for us as well. The relative lack of documentation compared to something like HAPI FHIR is disappointing as well.

**Comment by torresdrew** [comment]
Is there any specific documentation that is missing from the Github repo that is preventing you from testing out FHIR Works on AWS? 

On the status of the solutions page. We are working on streamlining the customer experience as it relates to what was published on the solutions library vs. Github. The pages will be back once a better unified experience is available. In the meanwhile feel free to use the Github repo as the source of truth.

Thanks,
Drew

**Comment by joehep** [comment]
My specific issue is that due to the REMOVAL of this project from the MAIN Amazon website I no longer know if pursuing this as a solution is a worthwhile endeavor. The removal from docs.aws.amazone.com sent a message that this project has been discontinued. And that is fine, things come and go all the time. I just need to know if that is true so I can move on to something else, if appropriate or continue down the path with FHIR Works solution.

**Comment by torresdrew** [comment]
Project has not been discontinued, just reducing confusion with SMART vs non-SMART branch. Didn't want folks having to go to 2 places. It will return to to the solutions library, but we don't have an ETA currently.

**Comment by joehep** [comment]
That's good to hear. I did think it was odd that there seemed to be 2 main development branches - SMART vs. non-SMART. I do hope that when the SMART feature set is merged into the mainline it SMART support will be optional. For me, the biggest blocker is that large data (i.e. a DocumentReference or Binary resources is >10M data) is not handled very well; if at all, we haven't had any luck so far. 

Again, thanks for the answer.
