### ISSUE TITLE
[Misc] Upgrading from v2.5.1 to v3.1.1

### ISSUE THREAD

**Issue by floofydoug** [awslabs/fhir-works-on-aws-deployment#703]
**What's on your mind?**
Hello! It looks like there is a major change since the summer. What would be the steps to go about upgrading from a serverless deployed stack like in version v2.5.1 to the newest stack? 

Would I have to manually scrap everything that was generated?

**Comment by kcadette** [comment]
Hello @floofydoug, you can simply redeploy with the serverless upgraded version and it should update your stack without you having to scrap everything.
