### ISSUE TITLE
Policies needed to use 'cdk bootstrap'

### ISSUE THREAD

**Issue by robertlario** [awslabs/fhir-works-on-aws-deployment#708]
I found that when I ran 'yarn deploy' the first time I had to run 'cdk bootstrap' first.

'cdk bootstrap' needs these policies:

"ecr:CreateRepository",
          "ecr:SetRepositoryPolicy",
          "ecr:DescribeRepositories",
          "ecr:DeleteRepository",
          "ssm:PutParameter",
          "ssm:GetParameter",
          "ssm:GetParameters",
          "ssm:DeleteParameter"

**Comment by kpark277** [comment]
Hi @robertlario, did you run into any issues or find that any of those policies were missing?

**Comment by robertlario** [comment]
Hi, 

You might consider adding them to "iam_policy.json".  

And maybe adding a note to INSTALL.md section "### AWS service deployment with CDK" that running Running 'cdk bootstrap' is required before you can run 'yarn deploy' the first time, and these policies will be required to do so.

Just some issues I ran into.

**Comment by kpark277** [comment]
Got it, thank you for the suggestion. We have added to our backlog to update the INSTALL.md documentation to call out what is necessary to run cdk bootstrap.

**Comment by ssvegaraju** [comment]
Thanks for the information! `cdk bootstrap` is a prerequisite to using CDK for deployment, and the permissions required for this action are controlled by CDK itself. I don't see this "iam_policy.json" file you mention in our repository, but as the bootstrap step isn't something that is part of FWoA specifically, and is something that is for anything deployed via CDK, we probably won't add them into our deployment so as to fall on the side of lesser permissions wherever possible. However, it is a good call-out to update our instructions to note that bootstrapping is part of the CDK setup process, and we will make that more clear! For now, we have the instructions for setting up CDK for the first time here: https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/INSTALL.md#cdk-cli, which links to CDK documentation.

**Comment by robertlario** [comment]
I am moving away from fhir-works-on-aws-deployment\INSTALL.md ### serverless CLI (LEGACY)
to
fhir-works-on-aws-deployment\INSTALL.md ### AWS service deployment with CDK

To do this for the first time I needed to 'cdk bootstrap'.  Additional policies are required that are not shown in
fhir-works-on-aws-deployment\scripts\iam_policy.json

Just some suggestions to make the INSTALL.md a bit better for someone doing this for the first time.

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
