### ISSUE TITLE
[Feature Request] Remediate an AWS Security Hub critical finding by supporting virtual private cloud (VPC) configuration for ElasticSearch domain

### ISSUE THREAD

**Issue by dgrainge4** [awslabs/fhir-works-on-aws-deployment#710]
**Is your feature request related to a problem? Please describe.**
AWS **Security Hub** is reporting a CRITICAL severity security finding on the ElasticSearch domain deployed by FHIRWorks (v4.3.1) in our solution.  

The title of the finding is _"ES.2 Elasticsearch domains should be in a VPC"_ and a relevant excerpt from the finding detail is
> .. You should ensure that Elasticsearch domains are not attached to public subnets. See Resource-based policies (https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-ac.html#es-ac-types-resource) in the Amazon OpenSearch Service (successor to Amazon Elasticsearch Service) Developer Guide. 

This finding is being regarded by our government client as a security compliance issue leading to concern about allowing our FHIRWorks-based solution into production operation.

I am aware, from a [line in the FHIRWorks elasticsearch cloudformation](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/cloudformation/elasticsearch.yaml#L103), that FHIRWorks ES access is controlled using IAM roles.  From this I surmise that there is not actually a critical security issue here if the ES endpoint is not publically usable, and it would be good to confirm this belief.

**Describe the solution you'd like**
1) I seek confirmation from FHIRWorks that the ElasticSearch domain it deploys, outside of any VPC, is protected from public access by IAM security.

2) I would like to have the option of deploying FHIRWorks' ElasticSearch domain in a VPC.  I believe this should be possible using Cloudformation [ElasticSearch's VPCOption](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticsearch-domain-vpcoptions.html). By exercising this choice we would be able to avoid the critical-labelled security finding.

**Describe alternatives you've considered**
1) We considered modifying the configuration of ElasticSearch in our FHIRWorks solution to deploy the ES domain in a VPC, however we lack a full appreciation of all the usages of ES in the FWoA codebase and so we are concerned that this change will bring about a large amount of test/fix effort and uncertainty.

2) In the meantime, our only recourse is to seek an exemption by our client for this Security Hub finding, in order that the the solution be permitted to proceed into production.
    
<img width="1569" alt="Screen Shot 2022-10-05 at 9 34 59 AM" src="https://user-images.githubusercontent.com/22805473/193921700-4704dbf9-c399-4d54-8ca9-47d519b453d2.png">

**Comment by ssvegaraju** [comment]
Hi, thanks for bringing up these questions!

1. Yes, IAM controls all access to the ElasticSearch domain endpoint. Users accessing the endpoint will not be able to perform any actions if they are not authorized.
2. This question is slightly more complicated. We have done some research into VPCs for the ElasticSearch domain for this exact compliance concern. While the IAM control works, we understand that VPC is a wanted configuration option for some use cases. From our research we determined the following:

In addition to moving the ElasticSearch cluster into a VPC, you will also need to move all of the FWoA Lambdas into the VPC. This includes the fhirServer Lambda, the ddbToEs Lambda, and the updateSearchMappings Lambda. These Lambdas will also all need access to the internet through a NAT Gateway or VPC endpoint, each of which has another cost per hour/data on the connection. If you are interested in the specifics of changing the default FWoA Implementation to support ElasticSearch inside a VPC, please let me know and we can provide you instructions for setting up the VPC. But to answer your question, it would definitely be quicker to move forward with the IAM configuration, as we have confirmed that this is not a compliance risk. Hope this helps!

Thanks,
Sukeerth

**Comment by dgrainge4** [comment]
Thanks for your prompt response Sukeerth.

We are going to proceed by exemption from the Security Hub finding, relying
on the assurance that IAM is controlling access to the cluster endpoints.

regards
David

**Comment by ssvegaraju** [comment]
Great! I'll go ahead and close this for now, but feel free to reopen if there's anything else.
