### ISSUE TITLE
How to generate a tenant on a Smart-Mainline deployment?

### ISSUE THREAD

**Issue by floofydoug** [awslabs/fhir-works-on-aws-deployment#715]
Reading the documentation for the multi-tenancy deployment, I've seen that I can request the tenant in the auth token. However, I need a step before that to create the first tenant! 

On the `mainline` branch i saw that there is a `user-provision.py` script that sets up a tenant for a user via cognito. Is there something similar I can run to create my first tenant?

**Comment by ssvegaraju** [comment]
Hi @floofydoug, thanks for bringing up this question! There isn't anything you need to do to register a tenant specifically: A tenant is just a prefix to the endpoints. You can include this tenantId as part of the claim for users in your IdP. By default, the tenant id claim path is set to `tenantId` here: https://github.com/awslabs/fhir-works-on-aws-deployment/blob/smart-mainline/src/config.ts#L173. We have our users setup on our IdP to have tenantId defined as a field, so when you login to authenticate a request, it knows which tenant the requesting user is under. Let me know if that clears things up!

Thanks,
Sukeerth

**Comment by floofydoug** [comment]
Ah. Okay that makes sense. I am dealing with an invalid access error message, and this helps narrow things down a bit. Appreciate the quite response, Sukeerth.
