### ISSUE TITLE
[Misc] FHIR Works solution is gone

### ISSUE THREAD

**Issue by jayallenmn** [awslabs/fhir-works-on-aws-deployment#717]
Hey guys,

A month or so ago we used the AWS solution at https://aws.amazon.com/solutions/implementations/fhir-works-on-aws/ to create a FHIR service on AWS.  It's worked well for us and we're about to go to production with it but without a solution we're not able to create another FHIR service.  Any ideas on how we can create a new FHIR service?

Jay

**Comment by joryhatton** [comment]
+1

**Comment by ssvegaraju** [comment]
Hi @jayallenmn, thanks for bringing this up! On the status of the solutions page, we are working on streamlining the customer experience as there were multiple different entry points and sources of truth between GitHub and the Solutions page, SMART and non-SMART. The Solutions page will be back once we have a better, more unified experience. In the meantime, please feel free to use GitHub as the source of truth. Hope this helps!

Thanks,
Sukeerth

**Comment by jayallenmn** [comment]
Thanks for getting back to us.  If we clone the repo down, how do you recommend we deploy it to AWS?  Do we use the yaml in the cloudformation directory?  Just looking for a deploy similar to the AWS solution.

**Comment by ssvegaraju** [comment]
So we currently support deploying with both CDK and Serverless, though Serverless is marked as Legacy. In either case, running `yarn deploy` (for CDK) or `serverless deploy` (for Serverless) in the root of the repo will deploy FHIR-Works similarly to Solutions. More information on pre-deployment steps and configuration options can be found [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/INSTALL.md).

**Comment by jayallenmn** [comment]
Thanks Sukeerth; we were able to deploy using yarn deploy.  We did hit an error when we turned backup on for the dynamodb so I'll open a separate issue for that.
