### ISSUE TITLE
[Feature Request] ES end to end latency metric

### ISSUE THREAD

**Issue by Zambonilli** [awslabs/fhir-works-on-aws-deployment#719]
**Is your feature request related to a problem? Please describe.**
We're getting reports of writes not being reflected in searches fast enough for clients to be able to create a UX that has a form submitted, resource instance written and then redirect the user to a page with a list of results. Unfortunately, we're unable to measure the latency of synchronization between Dynamodb and ElasticSearch. The only cloudwatch metric we're seeing is SuccessfulRequestLatency which tells the time in ddb for successfully processed requests to the stream. This does not give us client processing time nor time from write to first published in the stream.

**Describe the solution you'd like**
Similar to the rest hook subscription's `SubscriptionEndToEndLatency` metric, adding an end to end latency metric for synchronizing between dynamodb and ElasticSearch would help us triage these sync delays.

**Describe alternatives you've considered**
Out of the box cloudwatch metrics for dynamodb streams

**Additional context**
none

**Comment by maghirardelli** [comment]
Hi! Thanks for the request. We have added this to our backlog.

**Comment by Zambonilli** [comment]
PR for adding this metric to ddbToES lambda.
https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/pull/156

**Comment by nguyen102** [comment]
Thanks for reaching out about this topic. Please note that we may not take immediate action on this issue and it may be left open as we evaluate demand and support for this issue. Updates will be provide as they become available.

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
