### ISSUE TITLE
[Bug] enableBackup breaks deploy

### ISSUE THREAD

**Issue by jayallenmn** [awslabs/fhir-works-on-aws-deployment#721]
**Describe the bug**
When enableBackup is set to true in cdk.json the install throws the following error.  We had to turn enableBackup off
        
Error: Cannot supply both 'day' and 'weekDay', use at most one at Function.cron 

**To Reproduce**
1. Edit cdk.json in the project root and set enableBackup to false.
2. yarn run release
3. yarn deploy

**Expected behavior**
Expect that the stack will deploy with Dynamo DB backups enabled.

**Versions:**
 - Release Version 5.1.0

**Comment by ssvegaraju** [comment]
Hi @jayallenmn, thanks for reporting this bug! I've added this to our teams backlog.

**Comment by jayallenmn** [comment]
hey guys, any update on this?  should we (manually) set up backup on the dynamodb?

**Comment by FernandoAranda** [comment]
Hi @jayallenmn ,
Thanks for reaching out, we do not have updates yet regarding this issue but we will keep you posted on this conversation. In the meantime you can manually setup backups for the DDB resource table by navigating to the table in the AWS Console under DynamoDB, and schedule backups under the Backups tab.

**Comment by sevu1** [comment]
@jayallenmn , we have just pushed fix. Feel free to get latest version or apply fix as per PR. One thing to note thought, your resources must be tagged manually with "fhir": "service" and "backup": "daily" to be automatically backed up. We are evaluating options to avoid manual tagging and have added item to the backlog.
![image](https://user-images.githubusercontent.com/112517151/213567428-30ed5bed-f1d2-4261-9752-47bbf2d71189.png)

Let us know if you have any other questions regarding this bug though
