### ISSUE TITLE
Info_Output.log

### ISSUE THREAD

**Issue by sunitakodali** [awslabs/fhir-works-on-aws-deployment#723]
**Describe the bug**
Unable to locate the Info_Output.log file.

**To Reproduce**
1.   serverless info --verbose --region <REGION> --stage <STAGE>.
Should be able to retrieve all user-specific variables. It is not.

2. container_id=$(docker ps -f "label=install-container" --format "{{.ID}}")
docker cp ${container_id}:/home/node/fhir-works-on-aws-deployment/Info_Output.log .
Should be able to details about Info_Output.log file. It is not.

**Screenshots**
![Screenshot 2022-10-13 130258](https://user-images.githubusercontent.com/96587254/195674988-1b16163f-e863-41c8-b4ee-aca5d5da0e50.png)

**Versions (please complete the following information):**
 - Release Version installed or commit hash [e.g. v1.0.3, 1edf4]

**Comment by ssvegaraju** [comment]
Hi, just a quick question:
1. Have you already deployed FHIR-Works? If not, Please follow the steps here first: https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/INSTALL.md. This will generate the info_output.log file, and also deploy the stack to your environment

For some additional context, the Info_Output.log is a file that contains all of the stack deployment outputs of FHIR-Works.

Thanks,
Sukeerth

**Comment by sunitakodali** [comment]
Hey Sukeerth,

Thank you for reaching me out.
Yes. I did deployed FHIR-works. I am able to pass few steps today, but got stuck after “yarn run and release”.

Errors:
“fhir-service-dev failed: Error: fhir-service-dev: SSM parameter /cdk-bootstrap/hnb659fds/version not found. Has the environment been bootstrapped? Please run 'cdk bootstrap'”

I did cdk bootstrap.
Error:
“Environment aws://*******/us-west-2 failed bootstrapping: Error: The stack named CDKToolkit failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: cdk-hnb659fds-assets-*******-us-west-2 already exists”

Not able to pass this step/unable to create stack.
Any help with these issues will be greatly appreciated 😊

How did you get my work email-id?

Thank you,
Sunita


________________________________

**Comment by ssvegaraju** [comment]
Hi,

I just responded to the github issue (and did not email you), please post
updates there so the rest of the team can see it.

As for the cdk bootstrap issue, it looks like fhir works did not deploy
successfully as a result, hence the lack of the output log.

You will need to make sure that the bootstrapped region and the deployment
region are the same.

Thanks,
Sukeerth

**Comment by sunitakodali** [comment]
Issue got fixed. Thank you.
