### ISSUE TITLE
Adding a body to a Get

### ISSUE THREAD

**Issue by robertlario** [awslabs/fhir-works-on-aws-deployment#725]
Is it possible to add a body to a get call?

I would like to establish the setting of the resourceType to that which is found in the body of the call. Not as part of the URL.

However, I get the following error when I include a body to the get call:

HttpError BadRequestError: request size did not match content length.

Can you direct me to where in the AWS code the resourceType is being set? And where is this error originating? 

Thanks,

Robert

**Comment by Bingjiling** [comment]
Hi Robert, 

Thanks for reaching out! HTTP GET requests shouldn't have request body, and all parameters must appear in the URL or in a header.

Which endpoint are you trying to use for resourceType? Is it getting a specific resource or a search? 

Thanks,
Yanyu
