### ISSUE TITLE
[Bug] Cannot build Implementation Guides via after deploying via CDK route

### ISSUE THREAD

**Issue by floofydoug** [awslabs/fhir-works-on-aws-deployment#732]
**Describe the bug**
I am having difficulty deploying with the following parameters on the SMARTLINE branch: (line broken for easier readability)  

```yarn deploy 
--profile profile_name 
-c issuerEndpoint= https://auth.my_proxy_endpoint.com
-c oAuth2ApiEndpoint=https://auth.my_proxy_endpoint.com 
-c patientPickerEndpoint=https://auth.my_proxy_endpoint.com   
-c stage=dev 
-c region=us-east-1 
-c enableMultiTenancy=true 
-c useHapiValidator=true 
-c fhirVersion=4.0.1
```

The error that I see states that the deployment is looking for a .jar file. However, in the documentation it looks as though creating a .jar file is only necessary going through the serverless path. 

instructions from ImplementationGuide readme:  

```
 When deploying, simply append the useHapiValidator flag (and the optional fhirVersion flag, which defaults to 4.0.1):
  yarn deploy -c useHapiValidator=true -c fhirVersion=4.0.1
```

I have since tried to compile the IGs via Maven using Java 8, and Coretto 17. but I run into this error: 

```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  0.978 s
[INFO] Finished at: 2022-11-06T22:29:48-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project fwoa-hapi-validator: Fatal error compiling: java.lang.IllegalAccessError: class lombok.javac.apt.LombokProcessor (in unnamed module @0x7134b8a7) cannot access class com.sun.tools.javac.processing.JavacProcessingEnvironment (in module jdk.compiler) because module jdk.compiler does not export com.sun.tools.javac.processing to unnamed module @0x7134b8a7 ->
```

**To Reproduce**

- place US-CORE files in /implementationGuide
- yarn run compile-ig
- yarn deploy --profile profile_name 
                        -c issuerEndpoint= https://auth.my_proxy_endpoint.com
                        -c oAuth2ApiEndpoint=https://auth.my_proxy_endpoint.com 
                        -c patientPickerEndpoint=https://auth.my_proxy_endpoint.com   
                        -c stage=dev 
                        -c region=us-east-1 
                        -c enableMultiTenancy=true 
                        -c useHapiValidator=true 
                        -c fhirVersion=4.0.1
running this will produce: 

```
/Users/doug/fhir-works-on-aws-smart/fhir-works-on-aws-deployment/node_modules/aws-cdk-lib/core/lib/asset-staging.ts:165
      throw new Error(`Cannot find asset at ${this.sourcePath}`);
            ^
Error: Cannot find asset at /Users/doug/fhir-works-on-aws-smart/fhir-works-on-aws-deployment/javaHapiValidatorLambda/target/fwoa-hapi-validator-dev.jar
```

or when trying to compile make a jar file manually: 

cd'ed into javaHapiValidator and ran `mvn clean install` 

**Expected behavior**
Expected to be able to pass useHapiValidator as a flag to build the necessary .jar files for IG. 

**Screenshots**

**Versions (please complete the following information):**
This is my current machine configuration: 

```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/homebrew/Cellar/maven/3.8.6/libexec
Java version: 17.0.5, vendor: Amazon.com Inc., runtime: /Library/Java/JavaVirtualMachines/amazon-corretto-17.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.3.1", arch: "aarch64", family: "mac"

Running node v16.15.1
```

**Comment by floofydoug** [comment]
What is the recommended Java version and Maven version?

**Comment by nguyen102** [comment]
Hi @floofydoug,

You'll still need to compile the IG. The deploy step is different for using CDK, but IG compilation is still required. Please follow steps 1 to 3 [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/7ed40d94b6739e737fa8f240b19d41591278c2d1/USING_IMPLEMENTATION_GUIDES.md#installation-steps) before running step 4. 

If it helps [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/4bc82a6a3a3958a0163bf9f35636a8a166dac9d2/.github/workflows/deploy-smart.yaml) are the commands we run to deploy FWoA.  You can try running those commands yourself, except replacing the `secrets` with the correct values for your installation.

* [Deploying FWoA with CDK](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/4bc82a6a3a3958a0163bf9f35636a8a166dac9d2/.github/workflows/deploy-smart.yaml#L111-L117)
* [Download and Compile IG](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/4bc82a6a3a3958a0163bf9f35636a8a166dac9d2/.github/workflows/deploy-smart.yaml#L84-L92)
* [Prereq](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/7ed40d94b6739e737fa8f240b19d41591278c2d1/USING_IMPLEMENTATION_GUIDES.md#prerequisites)

**Comment by nguyen102** [comment]
I also noticed in your command there is an extra space in your command
```
--profile profile_name 
-c issuerEndpoint= https://auth.my_proxy_endpoint.com
```

There shouldn't be a space between `=` and `https`

**Comment by floofydoug** [comment]
hey @nguyen102, 

Thanksk for responding. I had done all the steps mentioned. The extra space in the issuerEndpoint was a typo. I was already building and deployed before trying to add the HapiValidator. 

The problem was using Coretto 17. I had tried Java 8 and Coretto 17, but I needed to download Coretto 11 for it to compile.
