### ISSUE TITLE
FHIR -Bundle Request

### ISSUE THREAD

**Issue by sunitakodali** [awslabs/fhir-works-on-aws-deployment#738]
Hello,

I am trying to Bundle resource type (Synthea generated) from Postman. I am receiving error as: "Endpoint request timed out".
Any idea why I am not able to send Bundle messages. I am able to all other resource types.

Thank you

**Comment by nguyen102** [comment]
Hi,
Can you include the request that you sent? It could be that the Bundle request that was generated is too large. Therefore FWoA could not finish processing it in 30 seconds. This is the API timeout limit.

To debug if you can send Bundle request, can you try sending this Bundle request?
```
{
  "resourceType": "Bundle",
  "type": "transaction",
  "entry": [
    {
      "fullUrl": "urn:uuid:8cafa46d-08b4-4ee4-b51b-803e20ae8126",
      "resource": {
        "resourceType": "Patient",
        "name": [
          {
            "family": "Jameson",
            "given": [
              "Matt"
            ]
          }
        ],
        "gender": "male"
      },
      "request": {
        "method": "POST",
        "url": "Patient"
      }
    },
    {
      "resource": {
        "resourceType": "Patient",
        "name": [
          {
            "family": "Smith",
            "given": [
              "John"
            ]
          }
        ],
        "gender": "male"
      },
      "request": {
        "method": "POST",
        "url": "Patient"
      }
    }
  ]
}
```

**Comment by sunitakodali** [comment]
[ex.txt](https://github.com/awslabs/fhir-works-on-aws-deployment/files/9973955/ex.txt)

Yes, it is too large. I was able to post the message you sent. 
Does dynamoDb transaction limit could be the reason why I am not able to send large file?

**Comment by nguyen102** [comment]
Yep, we have a max bundle size of 100 as seen [here](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/mainline/src/dataServices/dynamoDbBundleService.ts#L49).

Have you tried splitting the request into smaller bundles?

**Comment by sunitakodali** [comment]
No. Not sure how to do that. Could you please let me know how I can fix this issue?

**Comment by sunitakodali** [comment]
No. Will try.

**Comment by sunitakodali** [comment]
Thank you.

**Comment by nguyen102** [comment]
Inside the Bundle request there is an entry attribute with a list of entries. You can remove all of the entries except for 25 and then try making the Bundle request again. You can continue doing this with different subset of the original entries in the list until all entries are sent.

**Comment by sunitakodali** [comment]
Hello Nguyen,

Splitting the request into smaller bundles, did work for me. For few requests I'm getting an error as: "Maximum number of entries for a Bundle is 100. There are currently 113 entries in this Bundle". Is the entry for a Bundle fixed or can we increase?

Thank you.
