### ISSUE TITLE
FHIR works UI

### ISSUE THREAD

**Issue by sunitakodali** [awslabs/fhir-works-on-aws-deployment#744]
Hello,

I am able to install and login to FHIR works UI page. Creating new Patient message (I don't see any 200 response). I am not able to perform any other action like read, search, delete or update. Resource Type sections shows, no resource types found.

Thank you.

**Comment by aws-tyler** [comment]
Do you receive any error messages at all? Any information you could share with us to help us understand if there is an issue with the setup instructions would be appreciated. Thanks!

**Comment by sunitakodali** [comment]
I already had FHIR server deployed. Enabled CORS.
Followed the instructions given - https://github.com/awslabs/fhir-works-on-aws-ui
No, I am not getting any error messages. At the same time, nothing is being inserted in db. 
[ex.txt] (https://github.com/awslabs/fhir-works-on-aws-deployment/files/10007335/ex.txt)

**Comment by sunitakodali** [comment]
I already had FHIR server deployed. Enabled CORS.
Followed the instructions given - https://github.com/awslabs/fhir-works-on-aws-ui
No, I am not getting any error messages. At the same time, nothing is being inserted in db.
![er1](https://user-images.githubusercontent.com/96587254/201772599-8779a940-a58b-4bfa-b17e-12f4f2e3afa8.png)

**Comment by sunitakodali** [comment]
Nothing is being populated under Resource Type.

**Comment by aws-tyler** [comment]
There isn't much we can do to help without an error message. No errors show up in the networking tab of the inspector? What about in the cloudwatch logs?

**Comment by aws-tyler** [comment]
Could you double check that you have configured your environment variables correctly and that you have created the `workshopuser` cognito user correctly by running the `provision-user` script and try again? We think that might be the cause of the issue.

**Comment by sunitakodali** [comment]
Sure. Thank you.
