### ISSUE TITLE
Dynamodb generation and structure question

### ISSUE THREAD

**Issue by rpostulart** [awslabs/fhir-works-on-aws-deployment#745]
**What's on your mind?**
How are the dynamoDB tables generated based on the FHIR standard / schema?
I can't find any documentation about this. So will there for each FHIR resources a separate table and how to deal with updates to the FHIR schema, how can we settle those later in this AWS solution?

**Comment by ssvegaraju** [comment]
Hi, thanks for bringing up this question! FHIR-Works has a single table design - all resources will be in the same table. We construct and store resources according to the FHIR schema, and these can be queried by using the API URL generated after deployment to search on specific resources (e.g. a GET request to `{API_URL}/Patient`). Does this answer your question?

Thanks,
Sukeerth

**Comment by rpostulart** [comment]
Yes and No :)

I am looking into a solution where I can add a custom authorizer (lambda) via API gateway and routes in API gateway where each route is a FHIR resource like patient. For each FHIR resource I would like to create a kind of  lambda microservice  which is doing the custom logic and manage the data in dynamodb. If you hear this use case, would that be possible with this solution?

**Comment by kcadette** [comment]
Hu @rpostulart, this isn't possible and no on else has done it but the code is available for you to fork.

**Comment by rpostulart** [comment]
Ok will have a look into it. Where can I find how a lambda is structured to complete the CRUD operations?

**Comment by ssvegaraju** [comment]
The CDK code that generates that API Gateway routes can be found [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/lib/cdk-infra-stack.ts#L677). The Lambda that handles all CRUD operations is the fhirServer Lambda. In particular, we have the [routing package](https://github.com/awslabs/fhir-works-on-aws-routing/), wherein all the different paths taken in by the API Gateway are handled and sent to the appropriate modules.

**Comment by rpostulart** [comment]
ok thanks for the update.
Are my thoughts about having a 'microservice' per resource a strange thinking?

**Comment by nguyen102** [comment]
I've found a link [here](https://dev.to/aws-builders/the-what-why-and-when-of-mono-lambda-vs-single-function-apis-5cig) that provides the pros/cons of single function lambda vs mono lambda. FWoA uses the mono lambda approach. Single function lambda is preferred when you want more granular control for each resource type. For example, if you expect the Patient resource type to receive much more traffic than the Observation resource type, you can set a higher provisioned concurrent for the lambda function that manages the Patient resource. If this level of control and granularity is not needed, I would recommend using FWoA as is.
