### ISSUE TITLE
[Misc] Enabling CORS in the lambda 

### ISSUE THREAD

**Issue by vcareit** [awslabs/fhir-works-on-aws-deployment#751]
**What's on your mind?**
I am using FWoA and it works well with mobile app. Now I want to access the rest api via angular app. I am getting CORS error which needs to be fixed in the lambda - fhir-service-****-fhirServer:provisioned

Where can I check the response headers allowed in the lambda and what changes needs to be done to enable CORS on the FHIR rest API

**Comment by kcadette** [comment]
Hi @vcareit, 
There are instructions for CORS customization [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/smart-mainline/CUSTOMIZE.md#cors-customization)

**Comment by vcareit** [comment]
This issue was resolved by extending the API Gateway deployment.
