### ISSUE TITLE
[Bug] Deploying 4.3.1 in a multi-environment setting results in error: "SubscriptionsTopic already exists"

### ISSUE THREAD

**Issue by atrudeau-vitall** [awslabs/fhir-works-on-aws-deployment#754]
**Describe the bug**
Our team has 2 environments for FHIR works - staging and production. We were on 4.1.0 and I upgraded staging to 4.3.1 without trouble. Then when I went to upgrade production, I received the error `Resource handler returned message: "SubscriptionsTopic already exists" (RequestToken: xxxxxx, HandlerErrorCode: AlreadyExists)`

**To Reproduce**
_All of this is done in the same AWS account_
1. Create deployment of the fhir-works project v4.3.1 for a certain stage name (e.g. staging)
2. Wait for the deployment to finish
3. Create deployment of the fhir-works project v4.3.1 for a different stage name (e.g. production)
4. Observe the deployment events in CloudFormation
5. See error

**Expected behavior**
The deployment fails because the SNS resource "SubscriptionsTopic" was created in the first deployment. It should either detect that the resource exists and use the existing one, or it should create 2 SNS resources using the stage name of the deployment

**Screenshots**
<img width="1125" alt="Screen Shot 2022-11-24 at 11 40 16 AM" src="https://user-images.githubusercontent.com/71970571/203833476-7e6cae84-34e7-465a-b2c6-aa50629180e5.png">

**Versions (please complete the following information):**
 - 4.3.1

**Additional context**
I was able to get the second upgrade working by commenting out the resource definition for SubscriptionsTopic and replacing all instances of `!Ref SubscriptionsTopic` with `!Sub "arn:aws:sns:${AWS::Region}:${AWS::AccountId}:SubscriptionsTopic"`

**Comment by ssvegaraju** [comment]
Hey @atrudeau-vitall, this was fixed as of this PR: https://github.com/awslabs/fhir-works-on-aws-deployment/pull/673. But if you're unable to upgrade, the workaround you've implemented is one of the methods we'd suggest as a fix, the other being to append the stage of the deployment to the subscription topic name in the serverless stack. Hope this helps!

Thanks,
Sukeerth
