### ISSUE TITLE
[Feature Request] Deployment option using OpenSearch Serverless

### ISSUE THREAD

**Issue by katayohe** [awslabs/fhir-works-on-aws-deployment#755]
**Is your feature request related to a problem? Please describe.**
The cost of OpenSearch for FHIR Works on AWS solutions is high. 
I want to be able to choose about using OpenSearch Serverless when deploying.

**Describe the solution you'd like**
OpenSearch Serverless (Preview)
https://aws.amazon.com/jp/opensearch-service/features/serverless/

**Comment by maghirardelli** [comment]
Thanks for reaching out. FHIR Works on AWS does not have immediate plans to integrate OpenSearch Serverless, however we we will keep this request open as we evaluate demand for this feature.

**Comment by Zambonilli** [comment]
@katayohe it looks like OpenSearch Serverless so far is highly focused on 2 use cases right now, time series data and log search. However, the docs tend to leave the log search open ended as full text search which would be where FWoA falls in. We're looking into the feasibility of OpenSearch Serverless with FWoA as well right now and will update this ticket if we learn anything more. However, we have some pretty rough requirements with running in a lot of tough AWS regions so our analysis might not make it's way to a PR until after all of the regions we need to run in are supported by OpenSearch Serverless.

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
