### ISSUE TITLE
transaction Bundle Post doesn't work for local development (serverless-offline)

### ISSUE THREAD

**Issue by nirojshrestha019** [awslabs/fhir-works-on-aws-deployment#756]
**Describe the bug**
Transaction Bundle Post works for AWS-deployed fireworks but doesn't seem to work for local development. 

**To Reproduce**
1. POST `{{API_URL}}`
```
{
	"resourceType": "Bundle",
	"type": "transaction",
	"entry": [{
		"resource":
		{
			"resourceType": "Organization",
			"name": "NirojOrganization"
		},
		"request": {
			"method": "POST",
			"url": "Organization"
		}
	}]
}
```

2. I get a 404 response with the following response: 
```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>

<body>
	<pre>Cannot POST null</pre>
</body>

</html>
```

**Expected behavior**
 I expect the transaction Bundle Post to work in local development as it does in AWS deployed fhirworks.

**Versions (please complete the following information):**
 - v3.0.0-smart

**Additional context**

**Comment by maghirardelli** [comment]
Thanks for reaching out. We will provide updates as they become available.

**Comment by Zambonilli** [comment]
A workaround is to add a path when registering the root route here, https://github.com/awslabs/fhir-works-on-aws-routing/blob/mainline/src/app.ts#L212. You just have to remember to not push this change when you're done.

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
