### ISSUE TITLE
[Misc] Does this solution support extensions / custom profiles?

### ISSUE THREAD

**Issue by rpostulart** [awslabs/fhir-works-on-aws-deployment#776]
I can't find any information about adding extentions to this solution.
Is there a possibility to do so. For example: https://simplifier.net/packages/nictiz.fhir.nl.stu3.zib2017/1.3.4

docs: https://hl7.org/fhir/extensibility.html

**Comment by kcadette** [comment]
Hi @rpostulart, you are able to define extensions/custom profiles as an Implementation Guide and use that with your deployment. ref: https://github.com/awslabs/fhir-works-on-aws-deployment/blob/smart-mainline/USING_IMPLEMENTATION_GUIDES.md
