### ISSUE TITLE
Deploying with pre-existing KMS keys?

### ISSUE THREAD

**Issue by dmlee8215** [awslabs/fhir-works-on-aws-deployment#807]
Hi, I was wondering if it was possible to deploy this using existing KMS keys, rather than creating new ones? I work in an organization under a parent account which doesn't have access to a full admin role. In particular we can do pretty much everything required to deploy except create KMS keys at the same time. If this can't happen out of the box can I get a couple pointers on the simplest way to modify this so that it will work? Thanks!

**Comment by nguyen102** [comment]
Hi @dmlee8215,

You can [deploy](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/INSTALL.md) FWoA using CDK. The KMS keys are defined [here](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/lib/kms.ts). To import existing keys you can follow the instructions [here](https://www.npmjs.com/package/@aws-cdk/aws-kms). Please refer to the `Importing existing keys` section.


-Tim

**Comment by dmlee8215** [comment]
Perfect, thanks @nguyen102 !
