### ISSUE TITLE
XML format accept in API request

### ISSUE THREAD

**Issue by youbenuse** [awslabs/fhir-works-on-aws-deployment#808]
---
name: XML format API Request/Response Feature
about: As FHIR built-in option, to implement both json/xml data type option is good way to improve feature.
title: "FWoa Server enable to accept XML data type"
labels: enhancement
assignees: ''

---

**Is your feature request related to a problem? Please describe.**
As default, FHIR support `application/fhir+xml` data type, So I think it's important to have this option as many users are getting clinic data as xml type the most.

**Describe the solution you'd like**
So I think to enable xml data type request data on the api handler would be great method for enhancement.

**Describe alternatives you've considered**
I think the best way is to update api handler to consider api request header as `Accept` key param and can format request data according to the this value. 

**Additional context**

**Comment by nguyen102** [comment]
Thanks for your feedback. I have added this feature request to our backlog.

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
