### ISSUE TITLE
[Bug] Unable to compile JP-CORE v1.1.0 Implementation Guides

### ISSUE THREAD

**Issue by adcyusuke** [awslabs/fhir-works-on-aws-deployment#818]
**Describe the bug**
I'm trying to compile JP-CORE v1.1.0 And it fails.
I succeed when I compile JP-CORE v1.0.5, But, in the case of JP-CORE v1.1.0, it throw the following error.
Please let us know what you think about error. Do you have any solutions?

I followed the [Using FHIR Implementation Guides](https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/USING_IMPLEMENTATION_GUIDES.md), created implementationGuides directory and downloaded JP-CORE IG packages.
When I use "yarn run compile-igs" in the parent directory, it throw the error below:

```
Compiling C:\FWoA\fhir-works-on-aws-deployment-5.1.0_1.1.0\fhir-works-on-aws-deployment-5.1.0\implementationGuides\package\StructureDefinition-jp-procedure.json
Exception:  The expressions for the following search parameter could not be parsed:
{
  "name": "JP_Coverage_InsuredPersonNumber_SP",
  "url": "http://jpfhir.jp/fhir/core/SearchParameter/JP_Coverage_InsuredPersonNumber_SP",
  "expression": "Coverage.extension.where(url='http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Coverage_InsuredPersonNumber').value.as(string)",
  "xpath": "f:Coverage/f:extension[@url='http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Coverage_InsuredPersonNumber']/f:valueString"
}
Either it is an invalid FHIRPath expression or it is using FHIRPath features not supported by this compiler.
Original error message was: Syntax error at line 1 col 90:

1 Coverage.extension.where(url='http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Coverage_InsuredPersonNumber').value.as(string)

Unexpected "_". Instead, I was expecting to see one of the following:

A character matching /[a-zA-Z0-9-:/.]/ based on:
    STRING_VALUE$ebnf$1 → STRING_VALUE$ebnf$1 ● /[a-zA-Z0-9-:/.]/
    STRING_VALUE →  ● STRING_VALUE$ebnf$1
    simpleWhereExp → IDENTIFIER _ "=" _ "'" ● STRING_VALUE "'"
    simpleWhere → simpleWhere$string$1 ● simpleWhereExp ")"
    expression → path ● simpleWhere expression$ebnf$1
    unionExpression →  ● expression
    Main →  ● unionExpression
A "'" based on:
    simpleWhereExp → IDENTIFIER _ "=" _ "'" STRING_VALUE ● "'"
    simpleWhere → simpleWhere$string$1 ● simpleWhereExp ")"
    expression → path ● simpleWhere expression$ebnf$1
    unionExpression →  ● expression
    Main →  ● unionExpression
 Error: The expressions for the following search parameter could not be parsed:
{
  "name": "JP_Coverage_InsuredPersonNumber_SP",
  "url": "http://jpfhir.jp/fhir/core/SearchParameter/JP_Coverage_InsuredPersonNumber_SP",
  "expression": "Coverage.extension.where(url='http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Coverage_InsuredPersonNumber').value.as(string)",
  "xpath": "f:Coverage/f:extension[@url='http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Coverage_InsuredPersonNumber']/f:valueString"
}
Either it is an invalid FHIRPath expression or it is using FHIRPath features not supported by this compiler.
Original error message was: Syntax error at line 1 col 90:

1 Coverage.extension.where(url='http://jpfhir.jp/fhir/core/Extension/StructureDefinition/JP_Coverage_InsuredPersonNumber').value.as(string)

Unexpected "_". Instead, I was expecting to see one of the following:

A character matching /[a-zA-Z0-9-:/.]/ based on:
    STRING_VALUE$ebnf$1 → STRING_VALUE$ebnf$1 ● /[a-zA-Z0-9-:/.]/
    STRING_VALUE →  ● STRING_VALUE$ebnf$1
    simpleWhereExp → IDENTIFIER _ "=" _ "'" ● STRING_VALUE "'"
    simpleWhere → simpleWhere$string$1 ● simpleWhereExp ")"
    expression → path ● simpleWhere expression$ebnf$1
    unionExpression →  ● expression
    Main →  ● unionExpression
A "'" based on:
    simpleWhereExp → IDENTIFIER _ "=" _ "'" STRING_VALUE ● "'"
    simpleWhere → simpleWhere$string$1 ● simpleWhereExp ")"
    expression → path ● simpleWhere expression$ebnf$1
    unionExpression →  ● expression
    Main →  ● unionExpression

    at C:\FWoA\fhir-works-on-aws-deployment-5.1.0_1.1.0\fhir-works-on-aws-deployment-5.1.0\node_modules\fhir-works-on-aws-search-es\src\implementationGuides\index.ts:136:23
    at Array.map (<anonymous>)
    at Object.compile (C:\FWoA\fhir-works-on-aws-deployment-5.1.0_1.1.0\fhir-works-on-aws-deployment-5.1.0\node_modules\fhir-works-on-aws-search-es\src\implementationGuides\index.ts:129:10)
    at IGCompiler.compileIGs (C:\FWoA\fhir-works-on-aws-deployment-5.1.0_1.1.0\fhir-works-on-aws-deployment-5.1.0\src\implementationGuides\IGCompiler.ts:113:76)
    at async compileIGs (C:\FWoA\fhir-works-on-aws-deployment-5.1.0_1.1.0\fhir-works-on-aws-deployment-5.1.0\scripts\compile-igs.ts:46:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**

1. Install Firely Terminal.

2. Run the following command to get JP-CORE v1.1.0 implementation guides.
　# fhir install jp-core.r4 1.1.0
　Reference site : https://registry.fhir.org/package/jp-core.r4%7C1.1.0

3. Put the JP-CORE IG package in local environment.
　#fhir-works-on-aws-deployment-5.1.0\implementationGuides\packages

4. Run the following command in Windows Powershell.
　#yarn install
　#yarn run compile-igs

**Expected behavior**
The JP-CORE v1.1.0 IG could be compiled without errors.

**Versions:**
- fhir-works-on-aws-deployment v5.1.0
- jp-core.r4 v1.1.0

**Additional context**
Are the above steps correct?

**Comment by nisankep** [comment]
Hey @adcyusuke,
Thank you for reaching out to us. We appreciate your feedback and would be happy to assist you in resolving any issues you may be experiencing.

In order to better understand the problem you are facing, we can try to recreate it on our side. Our team will work diligently to identify the root cause of the issue and provide a solution as quickly as possible.

While we are working on the issue, it may be helpful for you to reach out to the JP core team and review their changes for the 1.1.0 version. This may provide you with some additional information that could help resolve the issue or provide a workaround until a solution is implemented.

Thank you again for bringing this to our attention, and please don't hesitate to reach out to us if you have any further questions or concerns.

**Comment by adcyusuke** [comment]
Hi @nisankep 
I appreciate your cooperation.

This syntax error seems to occur when compiling the json file for [Search Parameter: jp-coverage-insuredpersonnumber-sp](https://jpfhir.jp/fhir/core/1.1.0/SearchParameter-jp-coverage-insuredpersonnumber-sp.html).
This Search Parameter newly added in v1.1.0.


In v1.1.0, the following Search Parameters have been added in addition to the above.
・JP_Coverage_InsuredPersonSubNumber_SP
・JP_Coverage_InsuredPersonSymbol_SP
・JP_Organization_InsuranceOrganizationCategory_SP
・JP_Organization_InsuranceOrganizationNo_SP
・JP_Organization_PrefectureNo_SP

I'm not very familiar with FHIR, so I'm asking without knowing whether the cause is FWoA or JP-CORE.

We will continue to investigate and inquire about JP-CORE.
Thank you for your continued support.

**Comment by ssvegaraju** [comment]
Hi, thanks for bringing up this issue! I was able to verify this issue on our end as well: I suspect that this is due to the version difference in FHIRPath that the implementation guide was compiled with, versus the one used in FWoA today. I'll add an item to our backlog to investigate upgrading our FHIRpath support! If you would like to attempt this change yourself, we have the grammar we use for parsing FHIRPath located [here](https://github.com/awslabs/fhir-works-on-aws-search-es/blob/mainline/src/implementationGuides/reducedFHIRPath.ne), which is compiled using [nearley](https://nearley.js.org/docs/grammar). 

Thanks,
Sukeerth

**Comment by adcyusuke** [comment]
Hi @ssvegaraju ,
Thank you for your investigation.
Am I correct in understanding that the same syntax error would occur if I use another FWoA versions?

**Comment by ssvegaraju** [comment]
I believe so, the same error would occur in other versions of FWoA.

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
