### ISSUE TITLE
[Misc] Physical Deletion of Resources

### ISSUE THREAD

**Issue by inatam** [awslabs/fhir-works-on-aws-deployment#820]
**What we want to do**
To delete all data with "documentStatus.DELETED".

**question**
Is it possible to specify a index query instead of a unique key, in order to delete the data in "dynamodb" physically by using function "deleteItem"?

**Versions:**
- fhir-works-on-aws-deployment
v4.0.0
- JPCORE
JP-CORE.Draft 1.0.5

**Comment by kcadette** [comment]
DynamoDB also has a [BatchWriteItem](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchWriteItem.html) action for deleting multiple items at the same time:

**Comment by inatam** [comment]
Hi @kcadette
Thank you for the reply.

I recognize that a BatchWriteItem action can delete multiple items.
However,  it can delete at most 25 items at one request.
It is the only way to process 25 items for each request by creating a loop.

**current procedure(Lambda function)**
1. Create global secondly index whose hash key is documentStatus, and acquire a key and a range key of "documentStatus=DELETED" record by excuting the following query:
```Java:LambdaFunctionHandler.java
	AmazonDynamoDB client = AmazonDynamoDBClientBuilder.standard().withRegion(Regions.AP_NORTHEAST_1).build();
	DynamoDB dynamoDB = new DynamoDB(client);
	Table table = dynamoDB.getTable(TABLE_NAME);
	Index index = table.getIndex(INDEX_NAME);
	QuerySpec spec = new QuerySpec()
		    .withKeyConditionExpression("#d = :v_documentStatus")
		    .withNameMap(new NameMap()
		        .with("#d", "documentStatus"))
		    .withValueMap(new ValueMap()
		        .withString(":v_documentStatus", "DELETED"));
	ItemCollection<QueryOutcome> result = index.query(spec);
```

2. Delete 25 items for each request by a BatchWriteItem acition, specifying a hash key and a range key of the Table
(alternatingHashAndRangeKeyValues is a list that saves 25 pairs of a hash key and a range key.)
```Java:LambdaFunctionHandler.java
	for (List<Object> alternatingHashAndRangeKeyValues : allKeyValues) {
		TableWriteItems deleteItems = new TableWriteItems(TABLE_NAME)
				.withHashAndRangeKeysToDelete(
						HASH_KEY, RANGE_KEY,
						alternatingHashAndRangeKeyValues.toArray(new Object[alternatingHashAndRangeKeyValues.size()]));
		dynamoDB.batchWriteItem(deleteItems);
	}
```

**question**
Is there any way to delete all the documents in one request, specifying only "documentStatus=DELETED"?

**Comment by sevu1** [comment]
@inatam , unfortunately deleting all documents in a single request is not something FWoA supports, but as you mentioned you can use a loop as a workaround

**Comment by inatam** [comment]
Thank you.
