### ISSUE TITLE
[Misc] About Resource Updates

### ISSUE THREAD

**Issue by inatam** [awslabs/fhir-works-on-aws-deployment#821]
**What we want to do**
To get resources from multiple systems and gather them into Fhir works on aws.
To synchronize resources on a regular basis.

**premise**
It is not possible to extract a difference from resources acquired from each system.

**question**
To synchronize resources, we are considering the following method:

1.  Delete all FWoA resources and register all newly acquired resources.
2. Retrieve all FWoA resources, compare them with the new resources, and then choose to registrate, renew, or delete them.
3. Save key values for each resource in DB, compare them with keys in new resources, and then choose to registrate, renew, or delete them.

To synchronize resources, are there any best practices for updating Fhir works on aws resources?

**Comment by kcadette** [comment]
HI @inatam  
You can do this with a batch transaction upsert. Records would be updated if they exist and inserted if they do not. With upsert, even though a record is exactly the same, it will still be updated and IDs will need to be in sync between the twi systems.

**Comment by inatam** [comment]
Hi @kcadette 
Thank you for the reply.

Does IDs have to be managed if they are different between the systems?
Please tell me if there is another way.

Also, is upsert supported in FHIR API?

**Comment by kcadette** [comment]
Upsert is supported. 
You can configure your deployment to be support upsert in your config.ts, when dynamoDbDataService and dynamoDbBundleService are instantiated, by setting supportUpdateCreate flag to true

I will circle back on if there is another way to do this

**Comment by kcadette** [comment]
@inatam If IDs are different between the 2 systems you would need to so some mapping for the Upsert feature to work as explained.

**Comment by inatam** [comment]
@kcadette
I found supportUpdateCreate flag in the formula Lambda used in CRUD, so I turned it into true and reuploaded.

Then, I tried PUT request as follows:
```
curl --location --request PUT 'https://XXX.amazonaws.com/dev/AllergyIntolerance/YYY'
```

As a result, an error was returned and  insert was not succeeded.
```
    "issue": [
        {
            "severity": "error",
            "code": "not-found",
            "diagnostics": "Resource AllergyIntolerance/YYY is not known"
        }
    ]
```

Is re-deploy of FWoA needed?
Or, was there any mistake in the method I tried?

**Comment by sevu1** [comment]
Yes, you'd need to redeploy FWoA

**Comment by inatam** [comment]
Thank you.
