### ISSUE TITLE
[Misc] About Encounter Resource Search

### ISSUE THREAD

**Issue by inatam** [awslabs/fhir-works-on-aws-deployment#822]
**What we want to do**
To search data of particular period of time even if resource lacks "period.end".

**premise**
Resource without period.end exists.

**question**
When we try to search data by "date", resources without "period.end" cannot be acquired.
Is there any way to search data of particular period of time and sort the data, even if resource lacks "period.end"?
Also, is it possible to search and sort data by "period.start" only, not by "date"?

**Versions:**
- fhir-works-on-aws-deployment
v4.0.0
- JPCORE
JP-CORE.Draft 1.0.5

**Comment by kcadette** [comment]
Hi @inatam 
We use elastic search for date searches, and based on our [code](https://github.com/awslabs/fhir-works-on-aws-search-es/blob/mainline/src/QueryBuilder/typeQueries/common/prefixRange.ts) it need a period.end. 
You can search for period.start https://build.fhir.org/encounter-search.html#8.11.23

**Comment by ElliotSilver** [comment]
The [FHIR specification](https://www.hl7.org/fhir/search.html#date) details how open-ended periods are handled. Note the mention that "the lower or upper bound might not actually be specified" for a Period, and that "implicitly, a missing lower boundary is 'less than' any actual date. A missing upper boundary is 'greater than' any actual date." The date search logic should take this into consideration; the current behaviour is not compliant.

**Comment by kcadette** [comment]
Hi @ElliotSilver, thanks for pointing that out. I added this to our backlog. 

Best,
Karina

**Comment by inatam** [comment]
Hi @kcadette 

Error response was returned by making the following request:
*My FWoA  environment is version4.

It seems that the method you suggest is supported from version5.
Is there any way to do a similar search in version4?

**Comment by sevu1** [comment]
There is a date search on `Encounter` resource in FHIR r4: https://www.hl7.org/fhir/encounter.html#search

**Comment by inatam** [comment]
Thank you.
