### ISSUE TITLE
Update contention handling

### ISSUE THREAD

**Issue by gonatf** [awslabs/fhir-works-on-aws-deployment#823]
Can someone enlighten me on support for etag/if-match?  I note I get back etags from calls but I am failing to receive a 412 error when the If-Match tag doesn't match.

thanks

**Comment by kcadette** [comment]
Hi @gonatf can you give som more information on what you're looking for?

**Comment by gonatf** [comment]
I'm trying to understand if fhir works supports fhir's resource contention approach, as in http://hl7.org/fhir/R4/http.html#concurrency .  I want to prevent a client updating based on a stale resource version.

**Comment by kcadette** [comment]
HI @gonatf, We currently do not support this. You can submit a feature request and we will prioritize from there.
Thanks,
Karina

**Comment by gonatf** [comment]
Can I just verify that it also isn't supported in the Bundle resource as one of the request attributes?  as in, ifMatch. Are any of the other checks supported?  ifModifiedSince, etc?

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
