### ISSUE TITLE
About Conditional Create at fhir-works-on-aws

### ISSUE THREAD

**Issue by fhir-works-dev01** [awslabs/fhir-works-on-aws-deployment#824]
We have deployed and verified fhir-works-on-aws at the following URL. 

[https://github.com/awslabs/fhir-works-on-aws-deployment/archive/refs/tags/v5.1.0.zip ](https://github.com/awslabs/fhir-works-on-aws-deployment/archive/refs/tags/v5.1.0.zip%C2%A0)

Is Conditional Create supported in this version?
And if it is supported, how do I configure it to enable it?

 It would be helpful if you could guide me.

**Comment by sevu1** [comment]
@fhir-works-dev01 , is it duplicate of [issue 162](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/issues/162)?
Could you please elaborate more on what exactly you are trying to achieve and if possible add some code/request examples with expected input and output

**Comment by fhir-works-dev01** [comment]
@sevu1 
thank you for your reply.
It overlaps with No. 162. very sorry.

"request'': {
"method": "POST",
"url": "Organization",
    "ifNoneExist": "identifier=http://jpfhir.jp/fhir/Common/IdSystem/insurance-medical-institution-no|2219810088"
}

I would like to register when the data does not exist as above, but it is newly registered every time.
Looking at the "metadata" information, "conditionalCreate" is "false".
We believe that changing "false" to "true" will enable registration when data does not exist.

"conditionalCreate": false,
"conditionalRead": "not-supported",
"conditionalUpdate": false,
"conditionalDelete": "not-supported",

Could you tell me how to change "conditionalCreate" to "true"?

**Comment by sevu1** [comment]
Thank you for clarification. Unfortunately we do not support conditional CRUD as you can see [here](https://github.com/awslabs/fhir-works-on-aws-routing/blob/mainline/src/router/metadata/cap.rest.resource.template.ts#L34) and [here](https://github.com/awslabs/fhir-works-on-aws-persistence-ddb/blob/mainline/src/dataServices/dynamoDbDataService.ts#L408)

**Comment by fhir-works-dev01** [comment]
Thank you for answering.
Please let me know for reference.

Do you have any plans to support "conditional CRUD"?

Thank you.

**Comment by Bingjiling** [comment]
Hi,

Appreciate the feedback, but this isn't something we are considering at this time. If more feedback comes on this topic it may be something we could consider at that time, but there are currently no plans.

Thanks,
Yanyu
