### ISSUE TITLE
how are you supposed to figure out the patientPickerEndpoint?

### ISSUE THREAD

**Issue by feroze-shahpurwala-visiontree** [awslabs/fhir-works-on-aws-deployment#827]
Is the patientPickerEndpoint the same as the issuer?

In this issue - https://github.com/awslabs/fhir-works-on-aws-deployment/issues/469#issue-1013498249

The are using the sandbox link as the patientPickerEndpoint. I am so confused. 

I am using [Okta SmartFhir Demo](https://github.com/oktadev/okta-smartfhir-demo)

What about the patient_authorization endpoint? Is that the picker endpoint?
https://smartauth.mydomain.com/patient_authorization

I think the documentation does not make it clear at all.

**Comment by Bingjiling** [comment]
Hi @feroze-shahpurwala-visiontree , 

Thanks for reaching out! I understand your frustration. 

The patientPickerEndpoint is the endpoint of the `OKTA Demo Stack` you deployed. You can find it in terminal outputs or in the AWS account you deployed the stack in. It'll look something like `https://aRandOmsTr1ng.execute-api.us-east-1.amazonaws.com/sandbox-v2`.

Which endpoint are you referring to for `patient_authorization`? Do you mean the `OAUTH_URL` used in Postman? 

The [Okta SmartFhir Demo](https://github.com/oktadev/okta-smartfhir-demo) is owned by the Okta team. I would suggest creating an issue in that repository. Meanwhile, we will also reach out to our contact in Okta team with documentation updates content. 

Thanks,
Yanyu

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at aws-security@amazon.com (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using HealthLake (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
