### ISSUE TITLE
[Misc] validating a QuestionnaireResponse against questionnaire

### ISSUE THREAD

**Issue by kyle-mwnz** [awslabs/fhir-works-on-aws-deployment#828]
The FHIR Validator cli includes a feature to validation a Questionnaire response against the provided `questionnaire` definition which is provided as a canonical URL in the `QuestionnaireResponse.questionnaire`.

Is this a supported feature of the FHIR Works HAPI validator lambda? It appears not (I have compiled the appropriate IG).

https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-Questionnaires

**Comment by ssvegaraju** [comment]
Hi, 
Questionnaire response validation is not supported by FHIR Works on AWS at this time, no. If there is enough interest we can add it to our backlog, or review any contributions pertaining to it but at the moment is not something we are considering. 

Thanks,
Sukeerth

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new
features to this solution. All security issues should be reported directly to AWS Security at aws-
security@amazon.com. If you are new to this solution, we advise you to explore using HealthLake
(https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and
analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to fwoa-migration-support@amazon.com or contact your AWS Account team.
