### ISSUE TITLE
[Feature Request] Support the FHIR History operation

### ISSUE THREAD

**Issue by rsmayda** [awslabs/fhir-works-on-aws-deployment#87]
Create a new package called fhir-works-on-aws-history-es that implements the FHIR specified history api:
- https://www.hl7.org/fhir/http.html#history

This task does not require improvements to the Elasticsearch search capabilities (like searching >= a certain date)

A/C:
- New repository
- Proper testing
- Updating integration tests
- Update this deployment package to use it

**Comment by PrimKruskal** [comment]
Hi rsmayda, 
    Whether work has started on history route enhancement ?  If you have empty repo, I can contribute on that.

**Comment by rsmayda** [comment]
We have not started the work nor do we have an empty repo. We should be able to spin one up in the new year. Just to confirm you guys have a use-case for the [history](https://www.hl7.org/fhir/http.html#history) apis?

Our initial thought is that we can re-use the existing Elasticsearch cluster to search for historical things there. Please let us know if this is a blocking or an important feature we can prioritize unblocking you

**Comment by nisankep** [comment]
FHIR Works on AWS has been moved to maintenance mode. While in maintenance, we will not add any new features to this solution. All security issues should be reported directly to AWS Security at [aws-security@amazon.com] (mailto:security@amazon.com). If you are new to this solution, we advise you to explore using [HealthLake] (https://aws.amazon.com/healthlake), which is our managed service for building FHIR based transactional and analytics applications. You can get started by contacting your AWS Account team. If you are an existing customer
of FHIR Works on AWS, and have additional questions or need immediate help, please reach out to [fwoa-migration-support@amazon.com](mailto:fwoa-migration-support@amazon.com) or contact your AWS Account team.
