### ISSUE TITLE
Installation Errors with AWS Credentials

### ISSUE THREAD

**Issue by jcarta** [awslabs/fhir-works-on-aws-deployment#99]
I am trying to install this using an AWS EC2 instance running RedHat.

When I go to run the install.sh script, I get the following error:

`Could not find any valid AWS credentials. You can configure credentials by running 'aws configure'`

When I run `aws configure`, I get the following:

```
AWS Access Key ID [****************G5FY]:
AWS Secret Access Key [****************ULcV]:
Default region name [us-east-1]:
Default output format [json]:
```

The access key and secret key are both active and were created using IAM. Is there something I am missing?

**Comment by rsmayda** [comment]
Lets see how are you running the install.sh script?
```sh
chmod +x ./scripts/install.sh
sudo ./scripts/install.sh
```
If that doesn't work I am thinking your sudo/root user doesn't have access to your path. Could you try:
```sh
sudo "PATH=$PATH" -E ./scripts/install.sh
```

**Comment by jcarta** [comment]
Here is the output when I run `sudo ./scripts/install.sh`

`AWS CLI cannot be found. Please install or check your PATH.  Aborting.`

When I run `sudo "PATH=$PATH" -E ./scripts/install.sh` I get the same error as before.

I will note that I am using AWS CLI version 2. Not sure if that matters or not. Here is the output of `aws --version`
`aws-cli/2.0.47 Python/3.7.3 Linux/4.18.0-193.el8.x86_64 exe/x86_64.rhel.8`

**Comment by nguyen102** [comment]
We've tested the install script with an Amazon Linux 2 instance. Would you be able to try running the code on a Linux 2 instance instead?
<img width="1349" alt="Screen Shot 2020-09-10 at 7 13 26 PM" src="https://user-images.githubusercontent.com/3661906/92822231-eeca4280-f399-11ea-90d0-f56165847ba2.png">

**Comment by rsmayda** [comment]
What is your local path? Try running. echo $PATH also what is your sudo echo $PATH

**Comment by jcarta** [comment]
> What is your local path? Try running. echo $PATH also what is your sudo echo $PATH

I just opened up a new instance (Amazon Linux 2). Here is the `aws --version` it came with:
`aws-cli/1.18.107 Python/2.7.18 Linux/4.14.193-149.317.amzn2.x86_64 botocore/1.17.31`

My PATH (both sudo and non-sudo) is `/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/ec2-user/.local/bin:/home/ec2-user/bin`

**Comment by jcarta** [comment]
> We've tested the install script with an Amazon Linux 2 instance. Would you be able to try running the code on a Linux 2 instance instead?
> <img alt="Screen Shot 2020-09-10 at 7 13 26 PM" width="1349" src="https://user-images.githubusercontent.com/3661906/92822231-eeca4280-f399-11ea-90d0-f56165847ba2.png">

**Comment by jcarta** [comment]
> > We've tested the install script with an Amazon Linux 2 instance. Would you be able to try running the code on a Linux 2 instance instead?
> > <img alt="Screen Shot 2020-09-10 at 7 13 26 PM" width="1349" src="https://user-images.githubusercontent.com/3661906/92822231-eeca4280-f399-11ea-90d0-f56165847ba2.png">

I still got the same error. Though this time my IAM console registered activity with my Access Key. 
The policy attached to this user is: AdministratorAccess

![image](https://user-images.githubusercontent.com/38144076/92826819-225b9b80-f39f-11ea-97b2-c495062a4414.png)

**Comment by rsmayda** [comment]
Ok I think I am getting closer -- since we are using `sudo` on the install script we must also use `sudo` on `aws configure`. So could you configure your aws cli by using `sudo aws configure`?

I tried that on my side and it worked

**Comment by jcarta** [comment]
> Ok I think I am getting closer -- since we are using `sudo` on the install script we must also use `sudo` on `aws configure`. So could you configure your aws cli by using `sudo aws configure`?
> 
> I tried that on my side and it worked

Looks like adding sudo in front of aws configure did get me past the credentials issue. Thank you! 

The script did run but failed on a few other occasions; both out-of-memory exceptions.

![image](https://user-images.githubusercontent.com/38144076/92934804-edd6f680-f415-11ea-8fcd-d359bfd60a08.png)

and

![image](https://user-images.githubusercontent.com/38144076/92936052-a3ef1000-f417-11ea-8489-9be6c23efd6a.png)

Nothing was written to the Info_Output.yml file...

**Comment by rsmayda** [comment]
Good glad to hear we got through the first hurdle ;) 

Next for Memory  -- as describe in the Prereqs (https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/INSTALL.md#prerequisites) we recommend having at least 4 GB of RAM. Can you confirm what your RAM settings are?

**Comment by jcarta** [comment]
> Good glad to hear we got through the first hurdle ;)
> 
> Next for Memory -- as describe in the Prereqs (https://github.com/awslabs/fhir-works-on-aws-deployment/blob/mainline/INSTALL.md#prerequisites) we recommend having at least 4 GB of RAM. Can you confirm what your RAM settings are?

I switched from a t2.micro instance to a t2.medium instance and it worked! 
Thank you to the AWS team for the quick responses!
